// Code generated by rclgo-gen. DO NOT EDIT.

package octomap_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <octomap_msgs/srv/bounding_box_query.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("octomap_msgs/BoundingBoxQuery", BoundingBoxQueryTypeSupport)
	typemap.RegisterService("octomap_msgs/srv/BoundingBoxQuery", BoundingBoxQueryTypeSupport)
}

type _BoundingBoxQueryTypeSupport struct {}

func (s _BoundingBoxQueryTypeSupport) Request() types.MessageTypeSupport {
	return BoundingBoxQuery_RequestTypeSupport
}

func (s _BoundingBoxQueryTypeSupport) Response() types.MessageTypeSupport {
	return BoundingBoxQuery_ResponseTypeSupport
}

func (s _BoundingBoxQueryTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__octomap_msgs__srv__BoundingBoxQuery())
}

// Modifying this variable is undefined behavior.
var BoundingBoxQueryTypeSupport types.ServiceTypeSupport = _BoundingBoxQueryTypeSupport{}

// BoundingBoxQueryClient wraps rclgo.Client to provide type safe helper
// functions
type BoundingBoxQueryClient struct {
	*rclgo.Client
}

// NewBoundingBoxQueryClient creates and returns a new client for the
// BoundingBoxQuery
func NewBoundingBoxQueryClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*BoundingBoxQueryClient, error) {
	client, err := node.NewClient(serviceName, BoundingBoxQueryTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &BoundingBoxQueryClient{client}, nil
}

func (s *BoundingBoxQueryClient) Send(ctx context.Context, req *BoundingBoxQuery_Request) (*BoundingBoxQuery_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*BoundingBoxQuery_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type BoundingBoxQueryServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s BoundingBoxQueryServiceResponseSender) SendResponse(resp *BoundingBoxQuery_Response) error {
	return s.sender.SendResponse(resp)
}

type BoundingBoxQueryServiceRequestHandler func(*rclgo.ServiceInfo, *BoundingBoxQuery_Request, BoundingBoxQueryServiceResponseSender)

// BoundingBoxQueryService wraps rclgo.Service to provide type safe helper
// functions
type BoundingBoxQueryService struct {
	*rclgo.Service
}

// NewBoundingBoxQueryService creates and returns a new service for the
// BoundingBoxQuery
func NewBoundingBoxQueryService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler BoundingBoxQueryServiceRequestHandler) (*BoundingBoxQueryService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*BoundingBoxQuery_Request)
		responseSender := BoundingBoxQueryServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, BoundingBoxQueryTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &BoundingBoxQueryService{service}, nil
}