// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/srv/get_map2.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/GetMap2_Request", GetMap2_RequestTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/srv/GetMap2_Request", GetMap2_RequestTypeSupport)
}

type GetMap2_Request struct {
	GlobalMap bool `yaml:"global_map"`// request
	Optimized bool `yaml:"optimized"`
	WithImages bool `yaml:"with_images"`
	WithScans bool `yaml:"with_scans"`
	WithUserData bool `yaml:"with_user_data"`
	WithGrids bool `yaml:"with_grids"`
	WithWords bool `yaml:"with_words"`
	WithGlobalDescriptors bool `yaml:"with_global_descriptors"`
}

// NewGetMap2_Request creates a new GetMap2_Request with default values.
func NewGetMap2_Request() *GetMap2_Request {
	self := GetMap2_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetMap2_Request) Clone() *GetMap2_Request {
	c := &GetMap2_Request{}
	c.GlobalMap = t.GlobalMap
	c.Optimized = t.Optimized
	c.WithImages = t.WithImages
	c.WithScans = t.WithScans
	c.WithUserData = t.WithUserData
	c.WithGrids = t.WithGrids
	c.WithWords = t.WithWords
	c.WithGlobalDescriptors = t.WithGlobalDescriptors
	return c
}

func (t *GetMap2_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetMap2_Request) SetDefaults() {
	t.GlobalMap = false
	t.Optimized = false
	t.WithImages = false
	t.WithScans = false
	t.WithUserData = false
	t.WithGrids = false
	t.WithWords = false
	t.WithGlobalDescriptors = false
}

func (t *GetMap2_Request) GetTypeSupport() types.MessageTypeSupport {
	return GetMap2_RequestTypeSupport
}

// GetMap2_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetMap2_RequestPublisher struct {
	*rclgo.Publisher
}

// NewGetMap2_RequestPublisher creates and returns a new publisher for the
// GetMap2_Request
func NewGetMap2_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetMap2_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetMap2_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetMap2_RequestPublisher{pub}, nil
}

func (p *GetMap2_RequestPublisher) Publish(msg *GetMap2_Request) error {
	return p.Publisher.Publish(msg)
}

// GetMap2_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetMap2_RequestSubscription struct {
	*rclgo.Subscription
}

// GetMap2_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a GetMap2_RequestSubscription.
type GetMap2_RequestSubscriptionCallback func(msg *GetMap2_Request, info *rclgo.MessageInfo, err error)

// NewGetMap2_RequestSubscription creates and returns a new subscription for the
// GetMap2_Request
func NewGetMap2_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetMap2_RequestSubscriptionCallback) (*GetMap2_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetMap2_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetMap2_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetMap2_RequestSubscription{sub}, nil
}

func (s *GetMap2_RequestSubscription) TakeMessage(out *GetMap2_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetMap2_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetMap2_RequestSlice(dst, src []GetMap2_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetMap2_RequestTypeSupport types.MessageTypeSupport = _GetMap2_RequestTypeSupport{}

type _GetMap2_RequestTypeSupport struct{}

func (t _GetMap2_RequestTypeSupport) New() types.Message {
	return NewGetMap2_Request()
}

func (t _GetMap2_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__srv__GetMap2_Request
	return (unsafe.Pointer)(C.rtabmap_msgs__srv__GetMap2_Request__create())
}

func (t _GetMap2_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__srv__GetMap2_Request__destroy((*C.rtabmap_msgs__srv__GetMap2_Request)(pointer_to_free))
}

func (t _GetMap2_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetMap2_Request)
	mem := (*C.rtabmap_msgs__srv__GetMap2_Request)(dst)
	mem.global_map = C.bool(m.GlobalMap)
	mem.optimized = C.bool(m.Optimized)
	mem.with_images = C.bool(m.WithImages)
	mem.with_scans = C.bool(m.WithScans)
	mem.with_user_data = C.bool(m.WithUserData)
	mem.with_grids = C.bool(m.WithGrids)
	mem.with_words = C.bool(m.WithWords)
	mem.with_global_descriptors = C.bool(m.WithGlobalDescriptors)
}

func (t _GetMap2_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetMap2_Request)
	mem := (*C.rtabmap_msgs__srv__GetMap2_Request)(ros2_message_buffer)
	m.GlobalMap = bool(mem.global_map)
	m.Optimized = bool(mem.optimized)
	m.WithImages = bool(mem.with_images)
	m.WithScans = bool(mem.with_scans)
	m.WithUserData = bool(mem.with_user_data)
	m.WithGrids = bool(mem.with_grids)
	m.WithWords = bool(mem.with_words)
	m.WithGlobalDescriptors = bool(mem.with_global_descriptors)
}

func (t _GetMap2_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__srv__GetMap2_Request())
}

type CGetMap2_Request = C.rtabmap_msgs__srv__GetMap2_Request
type CGetMap2_Request__Sequence = C.rtabmap_msgs__srv__GetMap2_Request__Sequence

func GetMap2_Request__Sequence_to_Go(goSlice *[]GetMap2_Request, cSlice CGetMap2_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetMap2_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetMap2_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetMap2_Request__Sequence_to_C(cSlice *CGetMap2_Request__Sequence, goSlice []GetMap2_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__srv__GetMap2_Request)(C.malloc(C.sizeof_struct_rtabmap_msgs__srv__GetMap2_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetMap2_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetMap2_Request__Array_to_Go(goSlice []GetMap2_Request, cSlice []CGetMap2_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetMap2_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetMap2_Request__Array_to_C(cSlice []CGetMap2_Request, goSlice []GetMap2_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetMap2_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
