// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rtabmap_msgs/srv/get_node_data.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rtabmap_msgs/GetNodeData", GetNodeDataTypeSupport)
	typemap.RegisterService("rtabmap_msgs/srv/GetNodeData", GetNodeDataTypeSupport)
}

type _GetNodeDataTypeSupport struct {}

func (s _GetNodeDataTypeSupport) Request() types.MessageTypeSupport {
	return GetNodeData_RequestTypeSupport
}

func (s _GetNodeDataTypeSupport) Response() types.MessageTypeSupport {
	return GetNodeData_ResponseTypeSupport
}

func (s _GetNodeDataTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rtabmap_msgs__srv__GetNodeData())
}

// Modifying this variable is undefined behavior.
var GetNodeDataTypeSupport types.ServiceTypeSupport = _GetNodeDataTypeSupport{}

// GetNodeDataClient wraps rclgo.Client to provide type safe helper
// functions
type GetNodeDataClient struct {
	*rclgo.Client
}

// NewGetNodeDataClient creates and returns a new client for the
// GetNodeData
func NewGetNodeDataClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GetNodeDataClient, error) {
	client, err := node.NewClient(serviceName, GetNodeDataTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetNodeDataClient{client}, nil
}

func (s *GetNodeDataClient) Send(ctx context.Context, req *GetNodeData_Request) (*GetNodeData_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetNodeData_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetNodeDataServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GetNodeDataServiceResponseSender) SendResponse(resp *GetNodeData_Response) error {
	return s.sender.SendResponse(resp)
}

type GetNodeDataServiceRequestHandler func(*rclgo.ServiceInfo, *GetNodeData_Request, GetNodeDataServiceResponseSender)

// GetNodeDataService wraps rclgo.Service to provide type safe helper
// functions
type GetNodeDataService struct {
	*rclgo.Service
}

// NewGetNodeDataService creates and returns a new service for the
// GetNodeData
func NewGetNodeDataService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GetNodeDataServiceRequestHandler) (*GetNodeDataService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GetNodeData_Request)
		responseSender := GetNodeDataServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetNodeDataTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetNodeDataService{service}, nil
}