// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/srv/list_labels.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/ListLabels_Response", ListLabels_ResponseTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/srv/ListLabels_Response", ListLabels_ResponseTypeSupport)
}

type ListLabels_Response struct {
	Ids []int32 `yaml:"ids"`// requestresponse
	Labels []string `yaml:"labels"`
}

// NewListLabels_Response creates a new ListLabels_Response with default values.
func NewListLabels_Response() *ListLabels_Response {
	self := ListLabels_Response{}
	self.SetDefaults()
	return &self
}

func (t *ListLabels_Response) Clone() *ListLabels_Response {
	c := &ListLabels_Response{}
	if t.Ids != nil {
		c.Ids = make([]int32, len(t.Ids))
		copy(c.Ids, t.Ids)
	}
	if t.Labels != nil {
		c.Labels = make([]string, len(t.Labels))
		copy(c.Labels, t.Labels)
	}
	return c
}

func (t *ListLabels_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ListLabels_Response) SetDefaults() {
	t.Ids = nil
	t.Labels = nil
}

func (t *ListLabels_Response) GetTypeSupport() types.MessageTypeSupport {
	return ListLabels_ResponseTypeSupport
}

// ListLabels_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ListLabels_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewListLabels_ResponsePublisher creates and returns a new publisher for the
// ListLabels_Response
func NewListLabels_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ListLabels_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ListLabels_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListLabels_ResponsePublisher{pub}, nil
}

func (p *ListLabels_ResponsePublisher) Publish(msg *ListLabels_Response) error {
	return p.Publisher.Publish(msg)
}

// ListLabels_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ListLabels_ResponseSubscription struct {
	*rclgo.Subscription
}

// ListLabels_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ListLabels_ResponseSubscription.
type ListLabels_ResponseSubscriptionCallback func(msg *ListLabels_Response, info *rclgo.MessageInfo, err error)

// NewListLabels_ResponseSubscription creates and returns a new subscription for the
// ListLabels_Response
func NewListLabels_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ListLabels_ResponseSubscriptionCallback) (*ListLabels_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ListLabels_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ListLabels_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ListLabels_ResponseSubscription{sub}, nil
}

func (s *ListLabels_ResponseSubscription) TakeMessage(out *ListLabels_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneListLabels_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneListLabels_ResponseSlice(dst, src []ListLabels_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ListLabels_ResponseTypeSupport types.MessageTypeSupport = _ListLabels_ResponseTypeSupport{}

type _ListLabels_ResponseTypeSupport struct{}

func (t _ListLabels_ResponseTypeSupport) New() types.Message {
	return NewListLabels_Response()
}

func (t _ListLabels_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__srv__ListLabels_Response
	return (unsafe.Pointer)(C.rtabmap_msgs__srv__ListLabels_Response__create())
}

func (t _ListLabels_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__srv__ListLabels_Response__destroy((*C.rtabmap_msgs__srv__ListLabels_Response)(pointer_to_free))
}

func (t _ListLabels_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ListLabels_Response)
	mem := (*C.rtabmap_msgs__srv__ListLabels_Response)(dst)
	primitives.Int32__Sequence_to_C((*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.ids)), m.Ids)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.labels)), m.Labels)
}

func (t _ListLabels_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ListLabels_Response)
	mem := (*C.rtabmap_msgs__srv__ListLabels_Response)(ros2_message_buffer)
	primitives.Int32__Sequence_to_Go(&m.Ids, *(*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.ids)))
	primitives.String__Sequence_to_Go(&m.Labels, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.labels)))
}

func (t _ListLabels_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__srv__ListLabels_Response())
}

type CListLabels_Response = C.rtabmap_msgs__srv__ListLabels_Response
type CListLabels_Response__Sequence = C.rtabmap_msgs__srv__ListLabels_Response__Sequence

func ListLabels_Response__Sequence_to_Go(goSlice *[]ListLabels_Response, cSlice CListLabels_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ListLabels_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ListLabels_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ListLabels_Response__Sequence_to_C(cSlice *CListLabels_Response__Sequence, goSlice []ListLabels_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__srv__ListLabels_Response)(C.malloc(C.sizeof_struct_rtabmap_msgs__srv__ListLabels_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ListLabels_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ListLabels_Response__Array_to_Go(goSlice []ListLabels_Response, cSlice []CListLabels_Response) {
	for i := 0; i < len(cSlice); i++ {
		ListLabels_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ListLabels_Response__Array_to_C(cSlice []CListLabels_Response, goSlice []ListLabels_Response) {
	for i := 0; i < len(goSlice); i++ {
		ListLabels_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
