// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/srv/publish_map.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/PublishMap_Response", PublishMap_ResponseTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/srv/PublishMap_Response", PublishMap_ResponseTypeSupport)
}

type PublishMap_Response struct {
}

// NewPublishMap_Response creates a new PublishMap_Response with default values.
func NewPublishMap_Response() *PublishMap_Response {
	self := PublishMap_Response{}
	self.SetDefaults()
	return &self
}

func (t *PublishMap_Response) Clone() *PublishMap_Response {
	c := &PublishMap_Response{}
	return c
}

func (t *PublishMap_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *PublishMap_Response) SetDefaults() {
}

func (t *PublishMap_Response) GetTypeSupport() types.MessageTypeSupport {
	return PublishMap_ResponseTypeSupport
}

// PublishMap_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type PublishMap_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewPublishMap_ResponsePublisher creates and returns a new publisher for the
// PublishMap_Response
func NewPublishMap_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*PublishMap_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, PublishMap_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PublishMap_ResponsePublisher{pub}, nil
}

func (p *PublishMap_ResponsePublisher) Publish(msg *PublishMap_Response) error {
	return p.Publisher.Publish(msg)
}

// PublishMap_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type PublishMap_ResponseSubscription struct {
	*rclgo.Subscription
}

// PublishMap_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a PublishMap_ResponseSubscription.
type PublishMap_ResponseSubscriptionCallback func(msg *PublishMap_Response, info *rclgo.MessageInfo, err error)

// NewPublishMap_ResponseSubscription creates and returns a new subscription for the
// PublishMap_Response
func NewPublishMap_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback PublishMap_ResponseSubscriptionCallback) (*PublishMap_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg PublishMap_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, PublishMap_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &PublishMap_ResponseSubscription{sub}, nil
}

func (s *PublishMap_ResponseSubscription) TakeMessage(out *PublishMap_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// ClonePublishMap_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePublishMap_ResponseSlice(dst, src []PublishMap_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var PublishMap_ResponseTypeSupport types.MessageTypeSupport = _PublishMap_ResponseTypeSupport{}

type _PublishMap_ResponseTypeSupport struct{}

func (t _PublishMap_ResponseTypeSupport) New() types.Message {
	return NewPublishMap_Response()
}

func (t _PublishMap_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__srv__PublishMap_Response
	return (unsafe.Pointer)(C.rtabmap_msgs__srv__PublishMap_Response__create())
}

func (t _PublishMap_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__srv__PublishMap_Response__destroy((*C.rtabmap_msgs__srv__PublishMap_Response)(pointer_to_free))
}

func (t _PublishMap_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _PublishMap_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _PublishMap_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__srv__PublishMap_Response())
}

type CPublishMap_Response = C.rtabmap_msgs__srv__PublishMap_Response
type CPublishMap_Response__Sequence = C.rtabmap_msgs__srv__PublishMap_Response__Sequence

func PublishMap_Response__Sequence_to_Go(goSlice *[]PublishMap_Response, cSlice CPublishMap_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]PublishMap_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		PublishMap_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func PublishMap_Response__Sequence_to_C(cSlice *CPublishMap_Response__Sequence, goSlice []PublishMap_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__srv__PublishMap_Response)(C.malloc(C.sizeof_struct_rtabmap_msgs__srv__PublishMap_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		PublishMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func PublishMap_Response__Array_to_Go(goSlice []PublishMap_Response, cSlice []CPublishMap_Response) {
	for i := 0; i < len(cSlice); i++ {
		PublishMap_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func PublishMap_Response__Array_to_C(cSlice []CPublishMap_Response, goSlice []PublishMap_Response) {
	for i := 0; i < len(goSlice); i++ {
		PublishMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
