// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rtabmap_msgs/srv/publish_map.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rtabmap_msgs/PublishMap", PublishMapTypeSupport)
	typemap.RegisterService("rtabmap_msgs/srv/PublishMap", PublishMapTypeSupport)
}

type _PublishMapTypeSupport struct {}

func (s _PublishMapTypeSupport) Request() types.MessageTypeSupport {
	return PublishMap_RequestTypeSupport
}

func (s _PublishMapTypeSupport) Response() types.MessageTypeSupport {
	return PublishMap_ResponseTypeSupport
}

func (s _PublishMapTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rtabmap_msgs__srv__PublishMap())
}

// Modifying this variable is undefined behavior.
var PublishMapTypeSupport types.ServiceTypeSupport = _PublishMapTypeSupport{}

// PublishMapClient wraps rclgo.Client to provide type safe helper
// functions
type PublishMapClient struct {
	*rclgo.Client
}

// NewPublishMapClient creates and returns a new client for the
// PublishMap
func NewPublishMapClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*PublishMapClient, error) {
	client, err := node.NewClient(serviceName, PublishMapTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PublishMapClient{client}, nil
}

func (s *PublishMapClient) Send(ctx context.Context, req *PublishMap_Request) (*PublishMap_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*PublishMap_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type PublishMapServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s PublishMapServiceResponseSender) SendResponse(resp *PublishMap_Response) error {
	return s.sender.SendResponse(resp)
}

type PublishMapServiceRequestHandler func(*rclgo.ServiceInfo, *PublishMap_Request, PublishMapServiceResponseSender)

// PublishMapService wraps rclgo.Service to provide type safe helper
// functions
type PublishMapService struct {
	*rclgo.Service
}

// NewPublishMapService creates and returns a new service for the
// PublishMap
func NewPublishMapService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler PublishMapServiceRequestHandler) (*PublishMapService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*PublishMap_Request)
		responseSender := PublishMapServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, PublishMapTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &PublishMapService{service}, nil
}