// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/srv/reset_pose.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/ResetPose_Response", ResetPose_ResponseTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/srv/ResetPose_Response", ResetPose_ResponseTypeSupport)
}

type ResetPose_Response struct {
}

// NewResetPose_Response creates a new ResetPose_Response with default values.
func NewResetPose_Response() *ResetPose_Response {
	self := ResetPose_Response{}
	self.SetDefaults()
	return &self
}

func (t *ResetPose_Response) Clone() *ResetPose_Response {
	c := &ResetPose_Response{}
	return c
}

func (t *ResetPose_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ResetPose_Response) SetDefaults() {
}

func (t *ResetPose_Response) GetTypeSupport() types.MessageTypeSupport {
	return ResetPose_ResponseTypeSupport
}

// ResetPose_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ResetPose_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewResetPose_ResponsePublisher creates and returns a new publisher for the
// ResetPose_Response
func NewResetPose_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ResetPose_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ResetPose_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ResetPose_ResponsePublisher{pub}, nil
}

func (p *ResetPose_ResponsePublisher) Publish(msg *ResetPose_Response) error {
	return p.Publisher.Publish(msg)
}

// ResetPose_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ResetPose_ResponseSubscription struct {
	*rclgo.Subscription
}

// ResetPose_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ResetPose_ResponseSubscription.
type ResetPose_ResponseSubscriptionCallback func(msg *ResetPose_Response, info *rclgo.MessageInfo, err error)

// NewResetPose_ResponseSubscription creates and returns a new subscription for the
// ResetPose_Response
func NewResetPose_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ResetPose_ResponseSubscriptionCallback) (*ResetPose_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ResetPose_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ResetPose_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ResetPose_ResponseSubscription{sub}, nil
}

func (s *ResetPose_ResponseSubscription) TakeMessage(out *ResetPose_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneResetPose_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneResetPose_ResponseSlice(dst, src []ResetPose_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ResetPose_ResponseTypeSupport types.MessageTypeSupport = _ResetPose_ResponseTypeSupport{}

type _ResetPose_ResponseTypeSupport struct{}

func (t _ResetPose_ResponseTypeSupport) New() types.Message {
	return NewResetPose_Response()
}

func (t _ResetPose_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__srv__ResetPose_Response
	return (unsafe.Pointer)(C.rtabmap_msgs__srv__ResetPose_Response__create())
}

func (t _ResetPose_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__srv__ResetPose_Response__destroy((*C.rtabmap_msgs__srv__ResetPose_Response)(pointer_to_free))
}

func (t _ResetPose_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _ResetPose_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _ResetPose_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__srv__ResetPose_Response())
}

type CResetPose_Response = C.rtabmap_msgs__srv__ResetPose_Response
type CResetPose_Response__Sequence = C.rtabmap_msgs__srv__ResetPose_Response__Sequence

func ResetPose_Response__Sequence_to_Go(goSlice *[]ResetPose_Response, cSlice CResetPose_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ResetPose_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ResetPose_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ResetPose_Response__Sequence_to_C(cSlice *CResetPose_Response__Sequence, goSlice []ResetPose_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__srv__ResetPose_Response)(C.malloc(C.sizeof_struct_rtabmap_msgs__srv__ResetPose_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ResetPose_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ResetPose_Response__Array_to_Go(goSlice []ResetPose_Response, cSlice []CResetPose_Response) {
	for i := 0; i < len(cSlice); i++ {
		ResetPose_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ResetPose_Response__Array_to_C(cSlice []CResetPose_Response, goSlice []ResetPose_Response) {
	for i := 0; i < len(goSlice); i++ {
		ResetPose_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
