// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/srv/reset_pose.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/ResetPose_Request", ResetPose_RequestTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/srv/ResetPose_Request", ResetPose_RequestTypeSupport)
}

type ResetPose_Request struct {
	X float32 `yaml:"x"`// request
	Y float32 `yaml:"y"`
	Z float32 `yaml:"z"`
	Roll float32 `yaml:"roll"`
	Pitch float32 `yaml:"pitch"`
	Yaw float32 `yaml:"yaw"`
}

// NewResetPose_Request creates a new ResetPose_Request with default values.
func NewResetPose_Request() *ResetPose_Request {
	self := ResetPose_Request{}
	self.SetDefaults()
	return &self
}

func (t *ResetPose_Request) Clone() *ResetPose_Request {
	c := &ResetPose_Request{}
	c.X = t.X
	c.Y = t.Y
	c.Z = t.Z
	c.Roll = t.Roll
	c.Pitch = t.Pitch
	c.Yaw = t.Yaw
	return c
}

func (t *ResetPose_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ResetPose_Request) SetDefaults() {
	t.X = 0
	t.Y = 0
	t.Z = 0
	t.Roll = 0
	t.Pitch = 0
	t.Yaw = 0
}

func (t *ResetPose_Request) GetTypeSupport() types.MessageTypeSupport {
	return ResetPose_RequestTypeSupport
}

// ResetPose_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ResetPose_RequestPublisher struct {
	*rclgo.Publisher
}

// NewResetPose_RequestPublisher creates and returns a new publisher for the
// ResetPose_Request
func NewResetPose_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ResetPose_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ResetPose_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ResetPose_RequestPublisher{pub}, nil
}

func (p *ResetPose_RequestPublisher) Publish(msg *ResetPose_Request) error {
	return p.Publisher.Publish(msg)
}

// ResetPose_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ResetPose_RequestSubscription struct {
	*rclgo.Subscription
}

// ResetPose_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a ResetPose_RequestSubscription.
type ResetPose_RequestSubscriptionCallback func(msg *ResetPose_Request, info *rclgo.MessageInfo, err error)

// NewResetPose_RequestSubscription creates and returns a new subscription for the
// ResetPose_Request
func NewResetPose_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ResetPose_RequestSubscriptionCallback) (*ResetPose_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ResetPose_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ResetPose_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ResetPose_RequestSubscription{sub}, nil
}

func (s *ResetPose_RequestSubscription) TakeMessage(out *ResetPose_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneResetPose_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneResetPose_RequestSlice(dst, src []ResetPose_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ResetPose_RequestTypeSupport types.MessageTypeSupport = _ResetPose_RequestTypeSupport{}

type _ResetPose_RequestTypeSupport struct{}

func (t _ResetPose_RequestTypeSupport) New() types.Message {
	return NewResetPose_Request()
}

func (t _ResetPose_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__srv__ResetPose_Request
	return (unsafe.Pointer)(C.rtabmap_msgs__srv__ResetPose_Request__create())
}

func (t _ResetPose_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__srv__ResetPose_Request__destroy((*C.rtabmap_msgs__srv__ResetPose_Request)(pointer_to_free))
}

func (t _ResetPose_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ResetPose_Request)
	mem := (*C.rtabmap_msgs__srv__ResetPose_Request)(dst)
	mem.x = C.float(m.X)
	mem.y = C.float(m.Y)
	mem.z = C.float(m.Z)
	mem.roll = C.float(m.Roll)
	mem.pitch = C.float(m.Pitch)
	mem.yaw = C.float(m.Yaw)
}

func (t _ResetPose_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ResetPose_Request)
	mem := (*C.rtabmap_msgs__srv__ResetPose_Request)(ros2_message_buffer)
	m.X = float32(mem.x)
	m.Y = float32(mem.y)
	m.Z = float32(mem.z)
	m.Roll = float32(mem.roll)
	m.Pitch = float32(mem.pitch)
	m.Yaw = float32(mem.yaw)
}

func (t _ResetPose_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__srv__ResetPose_Request())
}

type CResetPose_Request = C.rtabmap_msgs__srv__ResetPose_Request
type CResetPose_Request__Sequence = C.rtabmap_msgs__srv__ResetPose_Request__Sequence

func ResetPose_Request__Sequence_to_Go(goSlice *[]ResetPose_Request, cSlice CResetPose_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ResetPose_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ResetPose_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ResetPose_Request__Sequence_to_C(cSlice *CResetPose_Request__Sequence, goSlice []ResetPose_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__srv__ResetPose_Request)(C.malloc(C.sizeof_struct_rtabmap_msgs__srv__ResetPose_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ResetPose_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ResetPose_Request__Array_to_Go(goSlice []ResetPose_Request, cSlice []CResetPose_Request) {
	for i := 0; i < len(cSlice); i++ {
		ResetPose_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ResetPose_Request__Array_to_C(cSlice []CResetPose_Request, goSlice []ResetPose_Request) {
	for i := 0; i < len(goSlice); i++ {
		ResetPose_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
