// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rtabmap_msgs/srv/set_goal.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rtabmap_msgs/SetGoal", SetGoalTypeSupport)
	typemap.RegisterService("rtabmap_msgs/srv/SetGoal", SetGoalTypeSupport)
}

type _SetGoalTypeSupport struct {}

func (s _SetGoalTypeSupport) Request() types.MessageTypeSupport {
	return SetGoal_RequestTypeSupport
}

func (s _SetGoalTypeSupport) Response() types.MessageTypeSupport {
	return SetGoal_ResponseTypeSupport
}

func (s _SetGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rtabmap_msgs__srv__SetGoal())
}

// Modifying this variable is undefined behavior.
var SetGoalTypeSupport types.ServiceTypeSupport = _SetGoalTypeSupport{}

// SetGoalClient wraps rclgo.Client to provide type safe helper
// functions
type SetGoalClient struct {
	*rclgo.Client
}

// NewSetGoalClient creates and returns a new client for the
// SetGoal
func NewSetGoalClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SetGoalClient, error) {
	client, err := node.NewClient(serviceName, SetGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetGoalClient{client}, nil
}

func (s *SetGoalClient) Send(ctx context.Context, req *SetGoal_Request) (*SetGoal_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetGoalServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SetGoalServiceResponseSender) SendResponse(resp *SetGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type SetGoalServiceRequestHandler func(*rclgo.ServiceInfo, *SetGoal_Request, SetGoalServiceResponseSender)

// SetGoalService wraps rclgo.Service to provide type safe helper
// functions
type SetGoalService struct {
	*rclgo.Service
}

// NewSetGoalService creates and returns a new service for the
// SetGoal
func NewSetGoalService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SetGoalServiceRequestHandler) (*SetGoalService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*SetGoal_Request)
		responseSender := SetGoalServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetGoalService{service}, nil
}