// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "dog-stream-gateway/internal/msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/assisted_teleop.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/AssistedTeleop_Feedback", AssistedTeleop_FeedbackTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/AssistedTeleop_Feedback", AssistedTeleop_FeedbackTypeSupport)
}

type AssistedTeleop_Feedback struct {
	CurrentTeleopDuration builtin_interfaces_msg.Duration `yaml:"current_teleop_duration"`// feedback
}

// NewAssistedTeleop_Feedback creates a new AssistedTeleop_Feedback with default values.
func NewAssistedTeleop_Feedback() *AssistedTeleop_Feedback {
	self := AssistedTeleop_Feedback{}
	self.SetDefaults()
	return &self
}

func (t *AssistedTeleop_Feedback) Clone() *AssistedTeleop_Feedback {
	c := &AssistedTeleop_Feedback{}
	c.CurrentTeleopDuration = *t.CurrentTeleopDuration.Clone()
	return c
}

func (t *AssistedTeleop_Feedback) CloneMsg() types.Message {
	return t.Clone()
}

func (t *AssistedTeleop_Feedback) SetDefaults() {
	t.CurrentTeleopDuration.SetDefaults()
}

func (t *AssistedTeleop_Feedback) GetTypeSupport() types.MessageTypeSupport {
	return AssistedTeleop_FeedbackTypeSupport
}

// AssistedTeleop_FeedbackPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type AssistedTeleop_FeedbackPublisher struct {
	*rclgo.Publisher
}

// NewAssistedTeleop_FeedbackPublisher creates and returns a new publisher for the
// AssistedTeleop_Feedback
func NewAssistedTeleop_FeedbackPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*AssistedTeleop_FeedbackPublisher, error) {
	pub, err := node.NewPublisher(topic_name, AssistedTeleop_FeedbackTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &AssistedTeleop_FeedbackPublisher{pub}, nil
}

func (p *AssistedTeleop_FeedbackPublisher) Publish(msg *AssistedTeleop_Feedback) error {
	return p.Publisher.Publish(msg)
}

// AssistedTeleop_FeedbackSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type AssistedTeleop_FeedbackSubscription struct {
	*rclgo.Subscription
}

// AssistedTeleop_FeedbackSubscriptionCallback type is used to provide a subscription
// handler function for a AssistedTeleop_FeedbackSubscription.
type AssistedTeleop_FeedbackSubscriptionCallback func(msg *AssistedTeleop_Feedback, info *rclgo.MessageInfo, err error)

// NewAssistedTeleop_FeedbackSubscription creates and returns a new subscription for the
// AssistedTeleop_Feedback
func NewAssistedTeleop_FeedbackSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback AssistedTeleop_FeedbackSubscriptionCallback) (*AssistedTeleop_FeedbackSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg AssistedTeleop_Feedback
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, AssistedTeleop_FeedbackTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &AssistedTeleop_FeedbackSubscription{sub}, nil
}

func (s *AssistedTeleop_FeedbackSubscription) TakeMessage(out *AssistedTeleop_Feedback) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneAssistedTeleop_FeedbackSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneAssistedTeleop_FeedbackSlice(dst, src []AssistedTeleop_Feedback) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var AssistedTeleop_FeedbackTypeSupport types.MessageTypeSupport = _AssistedTeleop_FeedbackTypeSupport{}

type _AssistedTeleop_FeedbackTypeSupport struct{}

func (t _AssistedTeleop_FeedbackTypeSupport) New() types.Message {
	return NewAssistedTeleop_Feedback()
}

func (t _AssistedTeleop_FeedbackTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__AssistedTeleop_Feedback
	return (unsafe.Pointer)(C.nav2_msgs__action__AssistedTeleop_Feedback__create())
}

func (t _AssistedTeleop_FeedbackTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__AssistedTeleop_Feedback__destroy((*C.nav2_msgs__action__AssistedTeleop_Feedback)(pointer_to_free))
}

func (t _AssistedTeleop_FeedbackTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*AssistedTeleop_Feedback)
	mem := (*C.nav2_msgs__action__AssistedTeleop_Feedback)(dst)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.current_teleop_duration), &m.CurrentTeleopDuration)
}

func (t _AssistedTeleop_FeedbackTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*AssistedTeleop_Feedback)
	mem := (*C.nav2_msgs__action__AssistedTeleop_Feedback)(ros2_message_buffer)
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.CurrentTeleopDuration, unsafe.Pointer(&mem.current_teleop_duration))
}

func (t _AssistedTeleop_FeedbackTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__AssistedTeleop_Feedback())
}

type CAssistedTeleop_Feedback = C.nav2_msgs__action__AssistedTeleop_Feedback
type CAssistedTeleop_Feedback__Sequence = C.nav2_msgs__action__AssistedTeleop_Feedback__Sequence

func AssistedTeleop_Feedback__Sequence_to_Go(goSlice *[]AssistedTeleop_Feedback, cSlice CAssistedTeleop_Feedback__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]AssistedTeleop_Feedback, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		AssistedTeleop_FeedbackTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func AssistedTeleop_Feedback__Sequence_to_C(cSlice *CAssistedTeleop_Feedback__Sequence, goSlice []AssistedTeleop_Feedback) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__AssistedTeleop_Feedback)(C.malloc(C.sizeof_struct_nav2_msgs__action__AssistedTeleop_Feedback * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		AssistedTeleop_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func AssistedTeleop_Feedback__Array_to_Go(goSlice []AssistedTeleop_Feedback, cSlice []CAssistedTeleop_Feedback) {
	for i := 0; i < len(cSlice); i++ {
		AssistedTeleop_FeedbackTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func AssistedTeleop_Feedback__Array_to_C(cSlice []CAssistedTeleop_Feedback, goSlice []AssistedTeleop_Feedback) {
	for i := 0; i < len(goSlice); i++ {
		AssistedTeleop_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
