// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <nav2_msgs/action/assisted_teleop.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("nav2_msgs/AssistedTeleop_GetResult", AssistedTeleop_GetResultTypeSupport)
	typemap.RegisterService("nav2_msgs/action/AssistedTeleop_GetResult", AssistedTeleop_GetResultTypeSupport)
}

type _AssistedTeleop_GetResultTypeSupport struct {}

func (s _AssistedTeleop_GetResultTypeSupport) Request() types.MessageTypeSupport {
	return AssistedTeleop_GetResult_RequestTypeSupport
}

func (s _AssistedTeleop_GetResultTypeSupport) Response() types.MessageTypeSupport {
	return AssistedTeleop_GetResult_ResponseTypeSupport
}

func (s _AssistedTeleop_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__nav2_msgs__action__AssistedTeleop_GetResult())
}

// Modifying this variable is undefined behavior.
var AssistedTeleop_GetResultTypeSupport types.ServiceTypeSupport = _AssistedTeleop_GetResultTypeSupport{}

// AssistedTeleop_GetResultClient wraps rclgo.Client to provide type safe helper
// functions
type AssistedTeleop_GetResultClient struct {
	*rclgo.Client
}

// NewAssistedTeleop_GetResultClient creates and returns a new client for the
// AssistedTeleop_GetResult
func NewAssistedTeleop_GetResultClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*AssistedTeleop_GetResultClient, error) {
	client, err := node.NewClient(serviceName, AssistedTeleop_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &AssistedTeleop_GetResultClient{client}, nil
}

func (s *AssistedTeleop_GetResultClient) Send(ctx context.Context, req *AssistedTeleop_GetResult_Request) (*AssistedTeleop_GetResult_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*AssistedTeleop_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type AssistedTeleop_GetResultServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s AssistedTeleop_GetResultServiceResponseSender) SendResponse(resp *AssistedTeleop_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type AssistedTeleop_GetResultServiceRequestHandler func(*rclgo.ServiceInfo, *AssistedTeleop_GetResult_Request, AssistedTeleop_GetResultServiceResponseSender)

// AssistedTeleop_GetResultService wraps rclgo.Service to provide type safe helper
// functions
type AssistedTeleop_GetResultService struct {
	*rclgo.Service
}

// NewAssistedTeleop_GetResultService creates and returns a new service for the
// AssistedTeleop_GetResult
func NewAssistedTeleop_GetResultService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler AssistedTeleop_GetResultServiceRequestHandler) (*AssistedTeleop_GetResultService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*AssistedTeleop_GetResult_Request)
		responseSender := AssistedTeleop_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, AssistedTeleop_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &AssistedTeleop_GetResultService{service}, nil
}