// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "dog-stream-gateway/internal/msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/back_up.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/BackUp_FeedbackMessage", BackUp_FeedbackMessageTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/BackUp_FeedbackMessage", BackUp_FeedbackMessageTypeSupport)
}

type BackUp_FeedbackMessage struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Feedback BackUp_Feedback `yaml:"feedback"`
}

// NewBackUp_FeedbackMessage creates a new BackUp_FeedbackMessage with default values.
func NewBackUp_FeedbackMessage() *BackUp_FeedbackMessage {
	self := BackUp_FeedbackMessage{}
	self.SetDefaults()
	return &self
}

func (t *BackUp_FeedbackMessage) Clone() *BackUp_FeedbackMessage {
	c := &BackUp_FeedbackMessage{}
	c.GoalID = *t.GoalID.Clone()
	c.Feedback = *t.Feedback.Clone()
	return c
}

func (t *BackUp_FeedbackMessage) CloneMsg() types.Message {
	return t.Clone()
}

func (t *BackUp_FeedbackMessage) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Feedback.SetDefaults()
}

func (t *BackUp_FeedbackMessage) GetTypeSupport() types.MessageTypeSupport {
	return BackUp_FeedbackMessageTypeSupport
}
func (t *BackUp_FeedbackMessage) GetGoalID() *types.GoalID {
	return (*types.GoalID)(&t.GoalID.Uuid)
}

func (t *BackUp_FeedbackMessage) SetGoalID(id *types.GoalID) {
	t.GoalID.Uuid = *id
}

// BackUp_FeedbackMessagePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type BackUp_FeedbackMessagePublisher struct {
	*rclgo.Publisher
}

// NewBackUp_FeedbackMessagePublisher creates and returns a new publisher for the
// BackUp_FeedbackMessage
func NewBackUp_FeedbackMessagePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*BackUp_FeedbackMessagePublisher, error) {
	pub, err := node.NewPublisher(topic_name, BackUp_FeedbackMessageTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &BackUp_FeedbackMessagePublisher{pub}, nil
}

func (p *BackUp_FeedbackMessagePublisher) Publish(msg *BackUp_FeedbackMessage) error {
	return p.Publisher.Publish(msg)
}

// BackUp_FeedbackMessageSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type BackUp_FeedbackMessageSubscription struct {
	*rclgo.Subscription
}

// BackUp_FeedbackMessageSubscriptionCallback type is used to provide a subscription
// handler function for a BackUp_FeedbackMessageSubscription.
type BackUp_FeedbackMessageSubscriptionCallback func(msg *BackUp_FeedbackMessage, info *rclgo.MessageInfo, err error)

// NewBackUp_FeedbackMessageSubscription creates and returns a new subscription for the
// BackUp_FeedbackMessage
func NewBackUp_FeedbackMessageSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback BackUp_FeedbackMessageSubscriptionCallback) (*BackUp_FeedbackMessageSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg BackUp_FeedbackMessage
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, BackUp_FeedbackMessageTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &BackUp_FeedbackMessageSubscription{sub}, nil
}

func (s *BackUp_FeedbackMessageSubscription) TakeMessage(out *BackUp_FeedbackMessage) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneBackUp_FeedbackMessageSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneBackUp_FeedbackMessageSlice(dst, src []BackUp_FeedbackMessage) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var BackUp_FeedbackMessageTypeSupport types.MessageTypeSupport = _BackUp_FeedbackMessageTypeSupport{}

type _BackUp_FeedbackMessageTypeSupport struct{}

func (t _BackUp_FeedbackMessageTypeSupport) New() types.Message {
	return NewBackUp_FeedbackMessage()
}

func (t _BackUp_FeedbackMessageTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__BackUp_FeedbackMessage
	return (unsafe.Pointer)(C.nav2_msgs__action__BackUp_FeedbackMessage__create())
}

func (t _BackUp_FeedbackMessageTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__BackUp_FeedbackMessage__destroy((*C.nav2_msgs__action__BackUp_FeedbackMessage)(pointer_to_free))
}

func (t _BackUp_FeedbackMessageTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*BackUp_FeedbackMessage)
	mem := (*C.nav2_msgs__action__BackUp_FeedbackMessage)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	BackUp_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&mem.feedback), &m.Feedback)
}

func (t _BackUp_FeedbackMessageTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*BackUp_FeedbackMessage)
	mem := (*C.nav2_msgs__action__BackUp_FeedbackMessage)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	BackUp_FeedbackTypeSupport.AsGoStruct(&m.Feedback, unsafe.Pointer(&mem.feedback))
}

func (t _BackUp_FeedbackMessageTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__BackUp_FeedbackMessage())
}

type CBackUp_FeedbackMessage = C.nav2_msgs__action__BackUp_FeedbackMessage
type CBackUp_FeedbackMessage__Sequence = C.nav2_msgs__action__BackUp_FeedbackMessage__Sequence

func BackUp_FeedbackMessage__Sequence_to_Go(goSlice *[]BackUp_FeedbackMessage, cSlice CBackUp_FeedbackMessage__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]BackUp_FeedbackMessage, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		BackUp_FeedbackMessageTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func BackUp_FeedbackMessage__Sequence_to_C(cSlice *CBackUp_FeedbackMessage__Sequence, goSlice []BackUp_FeedbackMessage) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__BackUp_FeedbackMessage)(C.malloc(C.sizeof_struct_nav2_msgs__action__BackUp_FeedbackMessage * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		BackUp_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func BackUp_FeedbackMessage__Array_to_Go(goSlice []BackUp_FeedbackMessage, cSlice []CBackUp_FeedbackMessage) {
	for i := 0; i < len(cSlice); i++ {
		BackUp_FeedbackMessageTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func BackUp_FeedbackMessage__Array_to_C(cSlice []CBackUp_FeedbackMessage, goSlice []BackUp_FeedbackMessage) {
	for i := 0; i < len(goSlice); i++ {
		BackUp_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
