// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/compute_and_track_route.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/ComputeAndTrackRoute_GetResult_Response", ComputeAndTrackRoute_GetResult_ResponseTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/ComputeAndTrackRoute_GetResult_Response", ComputeAndTrackRoute_GetResult_ResponseTypeSupport)
}

type ComputeAndTrackRoute_GetResult_Response struct {
	Status int8 `yaml:"status"`
	Result ComputeAndTrackRoute_Result `yaml:"result"`
}

// NewComputeAndTrackRoute_GetResult_Response creates a new ComputeAndTrackRoute_GetResult_Response with default values.
func NewComputeAndTrackRoute_GetResult_Response() *ComputeAndTrackRoute_GetResult_Response {
	self := ComputeAndTrackRoute_GetResult_Response{}
	self.SetDefaults()
	return &self
}

func (t *ComputeAndTrackRoute_GetResult_Response) Clone() *ComputeAndTrackRoute_GetResult_Response {
	c := &ComputeAndTrackRoute_GetResult_Response{}
	c.Status = t.Status
	c.Result = *t.Result.Clone()
	return c
}

func (t *ComputeAndTrackRoute_GetResult_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ComputeAndTrackRoute_GetResult_Response) SetDefaults() {
	t.Status = 0
	t.Result.SetDefaults()
}

func (t *ComputeAndTrackRoute_GetResult_Response) GetTypeSupport() types.MessageTypeSupport {
	return ComputeAndTrackRoute_GetResult_ResponseTypeSupport
}

// ComputeAndTrackRoute_GetResult_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ComputeAndTrackRoute_GetResult_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewComputeAndTrackRoute_GetResult_ResponsePublisher creates and returns a new publisher for the
// ComputeAndTrackRoute_GetResult_Response
func NewComputeAndTrackRoute_GetResult_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ComputeAndTrackRoute_GetResult_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ComputeAndTrackRoute_GetResult_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ComputeAndTrackRoute_GetResult_ResponsePublisher{pub}, nil
}

func (p *ComputeAndTrackRoute_GetResult_ResponsePublisher) Publish(msg *ComputeAndTrackRoute_GetResult_Response) error {
	return p.Publisher.Publish(msg)
}

// ComputeAndTrackRoute_GetResult_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ComputeAndTrackRoute_GetResult_ResponseSubscription struct {
	*rclgo.Subscription
}

// ComputeAndTrackRoute_GetResult_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ComputeAndTrackRoute_GetResult_ResponseSubscription.
type ComputeAndTrackRoute_GetResult_ResponseSubscriptionCallback func(msg *ComputeAndTrackRoute_GetResult_Response, info *rclgo.MessageInfo, err error)

// NewComputeAndTrackRoute_GetResult_ResponseSubscription creates and returns a new subscription for the
// ComputeAndTrackRoute_GetResult_Response
func NewComputeAndTrackRoute_GetResult_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ComputeAndTrackRoute_GetResult_ResponseSubscriptionCallback) (*ComputeAndTrackRoute_GetResult_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ComputeAndTrackRoute_GetResult_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ComputeAndTrackRoute_GetResult_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ComputeAndTrackRoute_GetResult_ResponseSubscription{sub}, nil
}

func (s *ComputeAndTrackRoute_GetResult_ResponseSubscription) TakeMessage(out *ComputeAndTrackRoute_GetResult_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneComputeAndTrackRoute_GetResult_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneComputeAndTrackRoute_GetResult_ResponseSlice(dst, src []ComputeAndTrackRoute_GetResult_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ComputeAndTrackRoute_GetResult_ResponseTypeSupport types.MessageTypeSupport = _ComputeAndTrackRoute_GetResult_ResponseTypeSupport{}

type _ComputeAndTrackRoute_GetResult_ResponseTypeSupport struct{}

func (t _ComputeAndTrackRoute_GetResult_ResponseTypeSupport) New() types.Message {
	return NewComputeAndTrackRoute_GetResult_Response()
}

func (t _ComputeAndTrackRoute_GetResult_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response
	return (unsafe.Pointer)(C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response__create())
}

func (t _ComputeAndTrackRoute_GetResult_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response__destroy((*C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response)(pointer_to_free))
}

func (t _ComputeAndTrackRoute_GetResult_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ComputeAndTrackRoute_GetResult_Response)
	mem := (*C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response)(dst)
	mem.status = C.int8_t(m.Status)
	ComputeAndTrackRoute_ResultTypeSupport.AsCStruct(unsafe.Pointer(&mem.result), &m.Result)
}

func (t _ComputeAndTrackRoute_GetResult_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ComputeAndTrackRoute_GetResult_Response)
	mem := (*C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response)(ros2_message_buffer)
	m.Status = int8(mem.status)
	ComputeAndTrackRoute_ResultTypeSupport.AsGoStruct(&m.Result, unsafe.Pointer(&mem.result))
}

func (t _ComputeAndTrackRoute_GetResult_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response())
}

type CComputeAndTrackRoute_GetResult_Response = C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response
type CComputeAndTrackRoute_GetResult_Response__Sequence = C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response__Sequence

func ComputeAndTrackRoute_GetResult_Response__Sequence_to_Go(goSlice *[]ComputeAndTrackRoute_GetResult_Response, cSlice CComputeAndTrackRoute_GetResult_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ComputeAndTrackRoute_GetResult_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ComputeAndTrackRoute_GetResult_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ComputeAndTrackRoute_GetResult_Response__Sequence_to_C(cSlice *CComputeAndTrackRoute_GetResult_Response__Sequence, goSlice []ComputeAndTrackRoute_GetResult_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response)(C.malloc(C.sizeof_struct_nav2_msgs__action__ComputeAndTrackRoute_GetResult_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ComputeAndTrackRoute_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ComputeAndTrackRoute_GetResult_Response__Array_to_Go(goSlice []ComputeAndTrackRoute_GetResult_Response, cSlice []CComputeAndTrackRoute_GetResult_Response) {
	for i := 0; i < len(cSlice); i++ {
		ComputeAndTrackRoute_GetResult_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ComputeAndTrackRoute_GetResult_Response__Array_to_C(cSlice []CComputeAndTrackRoute_GetResult_Response, goSlice []ComputeAndTrackRoute_GetResult_Response) {
	for i := 0; i < len(goSlice); i++ {
		ComputeAndTrackRoute_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
