// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/compute_path_through_poses.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/ComputePathThroughPoses_Feedback", ComputePathThroughPoses_FeedbackTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/ComputePathThroughPoses_Feedback", ComputePathThroughPoses_FeedbackTypeSupport)
}

type ComputePathThroughPoses_Feedback struct {
}

// NewComputePathThroughPoses_Feedback creates a new ComputePathThroughPoses_Feedback with default values.
func NewComputePathThroughPoses_Feedback() *ComputePathThroughPoses_Feedback {
	self := ComputePathThroughPoses_Feedback{}
	self.SetDefaults()
	return &self
}

func (t *ComputePathThroughPoses_Feedback) Clone() *ComputePathThroughPoses_Feedback {
	c := &ComputePathThroughPoses_Feedback{}
	return c
}

func (t *ComputePathThroughPoses_Feedback) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ComputePathThroughPoses_Feedback) SetDefaults() {
}

func (t *ComputePathThroughPoses_Feedback) GetTypeSupport() types.MessageTypeSupport {
	return ComputePathThroughPoses_FeedbackTypeSupport
}

// ComputePathThroughPoses_FeedbackPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ComputePathThroughPoses_FeedbackPublisher struct {
	*rclgo.Publisher
}

// NewComputePathThroughPoses_FeedbackPublisher creates and returns a new publisher for the
// ComputePathThroughPoses_Feedback
func NewComputePathThroughPoses_FeedbackPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ComputePathThroughPoses_FeedbackPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ComputePathThroughPoses_FeedbackTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ComputePathThroughPoses_FeedbackPublisher{pub}, nil
}

func (p *ComputePathThroughPoses_FeedbackPublisher) Publish(msg *ComputePathThroughPoses_Feedback) error {
	return p.Publisher.Publish(msg)
}

// ComputePathThroughPoses_FeedbackSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ComputePathThroughPoses_FeedbackSubscription struct {
	*rclgo.Subscription
}

// ComputePathThroughPoses_FeedbackSubscriptionCallback type is used to provide a subscription
// handler function for a ComputePathThroughPoses_FeedbackSubscription.
type ComputePathThroughPoses_FeedbackSubscriptionCallback func(msg *ComputePathThroughPoses_Feedback, info *rclgo.MessageInfo, err error)

// NewComputePathThroughPoses_FeedbackSubscription creates and returns a new subscription for the
// ComputePathThroughPoses_Feedback
func NewComputePathThroughPoses_FeedbackSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ComputePathThroughPoses_FeedbackSubscriptionCallback) (*ComputePathThroughPoses_FeedbackSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ComputePathThroughPoses_Feedback
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ComputePathThroughPoses_FeedbackTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ComputePathThroughPoses_FeedbackSubscription{sub}, nil
}

func (s *ComputePathThroughPoses_FeedbackSubscription) TakeMessage(out *ComputePathThroughPoses_Feedback) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneComputePathThroughPoses_FeedbackSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneComputePathThroughPoses_FeedbackSlice(dst, src []ComputePathThroughPoses_Feedback) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ComputePathThroughPoses_FeedbackTypeSupport types.MessageTypeSupport = _ComputePathThroughPoses_FeedbackTypeSupport{}

type _ComputePathThroughPoses_FeedbackTypeSupport struct{}

func (t _ComputePathThroughPoses_FeedbackTypeSupport) New() types.Message {
	return NewComputePathThroughPoses_Feedback()
}

func (t _ComputePathThroughPoses_FeedbackTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__ComputePathThroughPoses_Feedback
	return (unsafe.Pointer)(C.nav2_msgs__action__ComputePathThroughPoses_Feedback__create())
}

func (t _ComputePathThroughPoses_FeedbackTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__ComputePathThroughPoses_Feedback__destroy((*C.nav2_msgs__action__ComputePathThroughPoses_Feedback)(pointer_to_free))
}

func (t _ComputePathThroughPoses_FeedbackTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _ComputePathThroughPoses_FeedbackTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _ComputePathThroughPoses_FeedbackTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__ComputePathThroughPoses_Feedback())
}

type CComputePathThroughPoses_Feedback = C.nav2_msgs__action__ComputePathThroughPoses_Feedback
type CComputePathThroughPoses_Feedback__Sequence = C.nav2_msgs__action__ComputePathThroughPoses_Feedback__Sequence

func ComputePathThroughPoses_Feedback__Sequence_to_Go(goSlice *[]ComputePathThroughPoses_Feedback, cSlice CComputePathThroughPoses_Feedback__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ComputePathThroughPoses_Feedback, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ComputePathThroughPoses_FeedbackTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ComputePathThroughPoses_Feedback__Sequence_to_C(cSlice *CComputePathThroughPoses_Feedback__Sequence, goSlice []ComputePathThroughPoses_Feedback) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__ComputePathThroughPoses_Feedback)(C.malloc(C.sizeof_struct_nav2_msgs__action__ComputePathThroughPoses_Feedback * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ComputePathThroughPoses_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ComputePathThroughPoses_Feedback__Array_to_Go(goSlice []ComputePathThroughPoses_Feedback, cSlice []CComputePathThroughPoses_Feedback) {
	for i := 0; i < len(cSlice); i++ {
		ComputePathThroughPoses_FeedbackTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ComputePathThroughPoses_Feedback__Array_to_C(cSlice []CComputePathThroughPoses_Feedback, goSlice []ComputePathThroughPoses_Feedback) {
	for i := 0; i < len(goSlice); i++ {
		ComputePathThroughPoses_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
