// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <nav2_msgs/action/compute_path_through_poses.h>
*/
import "C"

import (
	"context"
	"time"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"

	action_msgs_msg "dog-stream-gateway/internal/msgs/action_msgs/msg"
	action_msgs_srv "dog-stream-gateway/internal/msgs/action_msgs/srv"
)

func init() {
	typemap.RegisterAction("nav2_msgs/ComputePathThroughPoses", ComputePathThroughPosesTypeSupport)
	typemap.RegisterAction("nav2_msgs/action/ComputePathThroughPoses", ComputePathThroughPosesTypeSupport)
}

type _ComputePathThroughPosesTypeSupport struct {}

func (s _ComputePathThroughPosesTypeSupport) Goal() types.MessageTypeSupport {
	return ComputePathThroughPoses_GoalTypeSupport
}

func (s _ComputePathThroughPosesTypeSupport) SendGoal() types.ServiceTypeSupport {
	return ComputePathThroughPoses_SendGoalTypeSupport
}

func (s _ComputePathThroughPosesTypeSupport) NewSendGoalResponse(accepted bool, stamp time.Duration) types.Message {
	msg := NewComputePathThroughPoses_SendGoal_Response()
	msg.Accepted = accepted
	secs := stamp.Truncate(time.Second)
	msg.Stamp.Sec = int32(secs)
	msg.Stamp.Nanosec = uint32(stamp - secs)
	return msg
}

func (s _ComputePathThroughPosesTypeSupport) Result() types.MessageTypeSupport {
	return ComputePathThroughPoses_ResultTypeSupport
}

func (s _ComputePathThroughPosesTypeSupport) GetResult() types.ServiceTypeSupport {
	return ComputePathThroughPoses_GetResultTypeSupport
}

func (s _ComputePathThroughPosesTypeSupport) NewGetResultResponse(status int8, result types.Message) types.Message {
	msg := NewComputePathThroughPoses_GetResult_Response()
	msg.Status = status
	if result == nil {
		msg.Result = *NewComputePathThroughPoses_Result()
	} else {
		msg.Result = *result.(*ComputePathThroughPoses_Result)
	}
	return msg
}

func (s _ComputePathThroughPosesTypeSupport) CancelGoal() types.ServiceTypeSupport {
	return action_msgs_srv.CancelGoalTypeSupport
}

func (s _ComputePathThroughPosesTypeSupport) Feedback() types.MessageTypeSupport {
	return ComputePathThroughPoses_FeedbackTypeSupport
}

func (s _ComputePathThroughPosesTypeSupport) FeedbackMessage() types.MessageTypeSupport {
	return ComputePathThroughPoses_FeedbackMessageTypeSupport
}

func (s _ComputePathThroughPosesTypeSupport) NewFeedbackMessage(goalID *types.GoalID, feedback types.Message) types.Message {
	msg := NewComputePathThroughPoses_FeedbackMessage()
	msg.GoalID.Uuid = *goalID
	msg.Feedback = *feedback.(*ComputePathThroughPoses_Feedback)
	return msg
}

func (s _ComputePathThroughPosesTypeSupport) GoalStatusArray() types.MessageTypeSupport {
	return action_msgs_msg.GoalStatusArrayTypeSupport
}

func (s _ComputePathThroughPosesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_action_type_support_handle__nav2_msgs__action__ComputePathThroughPoses())
}

// Modifying this variable is undefined behavior.
var ComputePathThroughPosesTypeSupport types.ActionTypeSupport = _ComputePathThroughPosesTypeSupport{}

type ComputePathThroughPosesFeedbackSender struct {
	sender rclgo.FeedbackSender
}

func (s *ComputePathThroughPosesFeedbackSender) Send(msg *ComputePathThroughPoses_Feedback) error {
	return s.sender.Send(msg)
}

type ComputePathThroughPosesGoalHandle struct{
	*rclgo.GoalHandle

	Description *ComputePathThroughPoses_Goal
}

func (g *ComputePathThroughPosesGoalHandle) Accept() (*ComputePathThroughPosesFeedbackSender, error) {
	s, err := g.GoalHandle.Accept()
	if err != nil {
		return nil, err
	}
	return &ComputePathThroughPosesFeedbackSender{*s}, nil
}

type ComputePathThroughPosesAction interface {
	ExecuteGoal(context.Context, *ComputePathThroughPosesGoalHandle) (*ComputePathThroughPoses_Result, error)
}

func NewComputePathThroughPosesAction(
	executeGoal func(context.Context, *ComputePathThroughPosesGoalHandle) (*ComputePathThroughPoses_Result, error),
) ComputePathThroughPosesAction {
	return _ComputePathThroughPosesFuncAction(executeGoal)
}

type _ComputePathThroughPosesFuncAction func(context.Context, *ComputePathThroughPosesGoalHandle) (*ComputePathThroughPoses_Result, error)

func (a _ComputePathThroughPosesFuncAction) ExecuteGoal(
	ctx context.Context, goal *ComputePathThroughPosesGoalHandle,
) (*ComputePathThroughPoses_Result, error) {
	return a(ctx, goal)
}

type _ComputePathThroughPosesAction struct {
	action ComputePathThroughPosesAction
}

func (a _ComputePathThroughPosesAction) ExecuteGoal(ctx context.Context, handle *rclgo.GoalHandle) (types.Message, error) {
	return a.action.ExecuteGoal(ctx, &ComputePathThroughPosesGoalHandle{
		GoalHandle:  handle,
		Description: handle.Description.(*ComputePathThroughPoses_Goal),
	})
}

func (a _ComputePathThroughPosesAction) TypeSupport() types.ActionTypeSupport {
	return ComputePathThroughPosesTypeSupport
}

type ComputePathThroughPosesServer struct{
	*rclgo.ActionServer
}

func NewComputePathThroughPosesServer(node *rclgo.Node, name string, action ComputePathThroughPosesAction, opts *rclgo.ActionServerOptions) (*ComputePathThroughPosesServer, error) {
	server, err := node.NewActionServer(name, _ComputePathThroughPosesAction{action}, opts)
	if err != nil {
		return nil, err
	}
	return &ComputePathThroughPosesServer{server}, nil
}

type ComputePathThroughPosesFeedbackHandler func(context.Context, *ComputePathThroughPoses_FeedbackMessage)

type ComputePathThroughPosesStatusHandler func(context.Context, *action_msgs_msg.GoalStatus)

type ComputePathThroughPosesClient struct{
	*rclgo.ActionClient
}

func NewComputePathThroughPosesClient(node *rclgo.Node, name string, opts *rclgo.ActionClientOptions) (*ComputePathThroughPosesClient, error) {
	client, err := node.NewActionClient(name, ComputePathThroughPosesTypeSupport, opts)
	if err != nil {
		return nil, err
	}
	return &ComputePathThroughPosesClient{client}, nil
}

func (c *ComputePathThroughPosesClient) WatchGoal(ctx context.Context, goal *ComputePathThroughPoses_Goal, onFeedback ComputePathThroughPosesFeedbackHandler) (*ComputePathThroughPoses_GetResult_Response, *types.GoalID, error) {
	var resp types.Message
	var goalID *types.GoalID
	var err error
	if onFeedback == nil {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, nil)
	} else {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, func(ctx context.Context, msg types.Message) {
			onFeedback(ctx, msg.(*ComputePathThroughPoses_FeedbackMessage))
		})
	}
	if r, ok := resp.(*ComputePathThroughPoses_GetResult_Response); ok {
		return r, goalID, err
	}
	return nil, goalID, err
}

func (c *ComputePathThroughPosesClient) SendGoal(ctx context.Context, goal *ComputePathThroughPoses_Goal) (*ComputePathThroughPoses_SendGoal_Response, *types.GoalID, error) {
	resp, id, err := c.ActionClient.SendGoal(ctx, goal)
	if r, ok := resp.(*ComputePathThroughPoses_SendGoal_Response); ok {
		return r, id, err
	}
	return nil, id, err
}

func (c *ComputePathThroughPosesClient) SendGoalRequest(ctx context.Context, request *ComputePathThroughPoses_SendGoal_Request) (*ComputePathThroughPoses_SendGoal_Response, error) {
	resp, err := c.ActionClient.SendGoalRequest(ctx, request)
	if r, ok := resp.(*ComputePathThroughPoses_SendGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *ComputePathThroughPosesClient) GetResult(ctx context.Context, goalID *types.GoalID) (*ComputePathThroughPoses_GetResult_Response, error) {
	resp, err := c.ActionClient.GetResult(ctx, goalID)
	if r, ok := resp.(*ComputePathThroughPoses_GetResult_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *ComputePathThroughPosesClient) CancelGoal(ctx context.Context, request *action_msgs_srv.CancelGoal_Request) (*action_msgs_srv.CancelGoal_Response, error) {
	resp, err := c.ActionClient.CancelGoal(ctx, request)
	if r, ok := resp.(*action_msgs_srv.CancelGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *ComputePathThroughPosesClient) WatchFeedback(ctx context.Context, goalID *types.GoalID, handler ComputePathThroughPosesFeedbackHandler) <-chan error {
	return c.ActionClient.WatchFeedback(ctx, goalID, func(ctx context.Context, msg types.Message) {
		handler(ctx, msg.(*ComputePathThroughPoses_FeedbackMessage))
	})
}

func (c *ComputePathThroughPosesClient) WatchStatus(ctx context.Context, goalID *types.GoalID, handler ComputePathThroughPosesStatusHandler) <-chan error {
	return c.ActionClient.WatchStatus(ctx, goalID, func(ctx context.Context, msg types.Message) {
		handler(ctx, msg.(*action_msgs_msg.GoalStatus))
	})
}
