// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	nav2_msgs_msg "dog-stream-gateway/internal/msgs/nav2_msgs/msg"
	nav_msgs_msg "dog-stream-gateway/internal/msgs/nav_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/compute_and_track_route.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/ComputeAndTrackRoute_Feedback", ComputeAndTrackRoute_FeedbackTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/ComputeAndTrackRoute_Feedback", ComputeAndTrackRoute_FeedbackTypeSupport)
}

type ComputeAndTrackRoute_Feedback struct {
	LastNodeId uint16 `yaml:"last_node_id"`// feedback definition
	NextNodeId uint16 `yaml:"next_node_id"`
	CurrentEdgeId uint16 `yaml:"current_edge_id"`
	Route nav2_msgs_msg.Route `yaml:"route"`
	Path nav_msgs_msg.Path `yaml:"path"`
	OperationsTriggered []string `yaml:"operations_triggered"`
	Rerouted bool `yaml:"rerouted"`
}

// NewComputeAndTrackRoute_Feedback creates a new ComputeAndTrackRoute_Feedback with default values.
func NewComputeAndTrackRoute_Feedback() *ComputeAndTrackRoute_Feedback {
	self := ComputeAndTrackRoute_Feedback{}
	self.SetDefaults()
	return &self
}

func (t *ComputeAndTrackRoute_Feedback) Clone() *ComputeAndTrackRoute_Feedback {
	c := &ComputeAndTrackRoute_Feedback{}
	c.LastNodeId = t.LastNodeId
	c.NextNodeId = t.NextNodeId
	c.CurrentEdgeId = t.CurrentEdgeId
	c.Route = *t.Route.Clone()
	c.Path = *t.Path.Clone()
	if t.OperationsTriggered != nil {
		c.OperationsTriggered = make([]string, len(t.OperationsTriggered))
		copy(c.OperationsTriggered, t.OperationsTriggered)
	}
	c.Rerouted = t.Rerouted
	return c
}

func (t *ComputeAndTrackRoute_Feedback) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ComputeAndTrackRoute_Feedback) SetDefaults() {
	t.LastNodeId = 0
	t.NextNodeId = 0
	t.CurrentEdgeId = 0
	t.Route.SetDefaults()
	t.Path.SetDefaults()
	t.OperationsTriggered = nil
	t.Rerouted = false
}

func (t *ComputeAndTrackRoute_Feedback) GetTypeSupport() types.MessageTypeSupport {
	return ComputeAndTrackRoute_FeedbackTypeSupport
}

// ComputeAndTrackRoute_FeedbackPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ComputeAndTrackRoute_FeedbackPublisher struct {
	*rclgo.Publisher
}

// NewComputeAndTrackRoute_FeedbackPublisher creates and returns a new publisher for the
// ComputeAndTrackRoute_Feedback
func NewComputeAndTrackRoute_FeedbackPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ComputeAndTrackRoute_FeedbackPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ComputeAndTrackRoute_FeedbackTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ComputeAndTrackRoute_FeedbackPublisher{pub}, nil
}

func (p *ComputeAndTrackRoute_FeedbackPublisher) Publish(msg *ComputeAndTrackRoute_Feedback) error {
	return p.Publisher.Publish(msg)
}

// ComputeAndTrackRoute_FeedbackSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ComputeAndTrackRoute_FeedbackSubscription struct {
	*rclgo.Subscription
}

// ComputeAndTrackRoute_FeedbackSubscriptionCallback type is used to provide a subscription
// handler function for a ComputeAndTrackRoute_FeedbackSubscription.
type ComputeAndTrackRoute_FeedbackSubscriptionCallback func(msg *ComputeAndTrackRoute_Feedback, info *rclgo.MessageInfo, err error)

// NewComputeAndTrackRoute_FeedbackSubscription creates and returns a new subscription for the
// ComputeAndTrackRoute_Feedback
func NewComputeAndTrackRoute_FeedbackSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ComputeAndTrackRoute_FeedbackSubscriptionCallback) (*ComputeAndTrackRoute_FeedbackSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ComputeAndTrackRoute_Feedback
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ComputeAndTrackRoute_FeedbackTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ComputeAndTrackRoute_FeedbackSubscription{sub}, nil
}

func (s *ComputeAndTrackRoute_FeedbackSubscription) TakeMessage(out *ComputeAndTrackRoute_Feedback) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneComputeAndTrackRoute_FeedbackSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneComputeAndTrackRoute_FeedbackSlice(dst, src []ComputeAndTrackRoute_Feedback) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ComputeAndTrackRoute_FeedbackTypeSupport types.MessageTypeSupport = _ComputeAndTrackRoute_FeedbackTypeSupport{}

type _ComputeAndTrackRoute_FeedbackTypeSupport struct{}

func (t _ComputeAndTrackRoute_FeedbackTypeSupport) New() types.Message {
	return NewComputeAndTrackRoute_Feedback()
}

func (t _ComputeAndTrackRoute_FeedbackTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__ComputeAndTrackRoute_Feedback
	return (unsafe.Pointer)(C.nav2_msgs__action__ComputeAndTrackRoute_Feedback__create())
}

func (t _ComputeAndTrackRoute_FeedbackTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__ComputeAndTrackRoute_Feedback__destroy((*C.nav2_msgs__action__ComputeAndTrackRoute_Feedback)(pointer_to_free))
}

func (t _ComputeAndTrackRoute_FeedbackTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ComputeAndTrackRoute_Feedback)
	mem := (*C.nav2_msgs__action__ComputeAndTrackRoute_Feedback)(dst)
	mem.last_node_id = C.uint16_t(m.LastNodeId)
	mem.next_node_id = C.uint16_t(m.NextNodeId)
	mem.current_edge_id = C.uint16_t(m.CurrentEdgeId)
	nav2_msgs_msg.RouteTypeSupport.AsCStruct(unsafe.Pointer(&mem.route), &m.Route)
	nav_msgs_msg.PathTypeSupport.AsCStruct(unsafe.Pointer(&mem.path), &m.Path)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.operations_triggered)), m.OperationsTriggered)
	mem.rerouted = C.bool(m.Rerouted)
}

func (t _ComputeAndTrackRoute_FeedbackTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ComputeAndTrackRoute_Feedback)
	mem := (*C.nav2_msgs__action__ComputeAndTrackRoute_Feedback)(ros2_message_buffer)
	m.LastNodeId = uint16(mem.last_node_id)
	m.NextNodeId = uint16(mem.next_node_id)
	m.CurrentEdgeId = uint16(mem.current_edge_id)
	nav2_msgs_msg.RouteTypeSupport.AsGoStruct(&m.Route, unsafe.Pointer(&mem.route))
	nav_msgs_msg.PathTypeSupport.AsGoStruct(&m.Path, unsafe.Pointer(&mem.path))
	primitives.String__Sequence_to_Go(&m.OperationsTriggered, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.operations_triggered)))
	m.Rerouted = bool(mem.rerouted)
}

func (t _ComputeAndTrackRoute_FeedbackTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__ComputeAndTrackRoute_Feedback())
}

type CComputeAndTrackRoute_Feedback = C.nav2_msgs__action__ComputeAndTrackRoute_Feedback
type CComputeAndTrackRoute_Feedback__Sequence = C.nav2_msgs__action__ComputeAndTrackRoute_Feedback__Sequence

func ComputeAndTrackRoute_Feedback__Sequence_to_Go(goSlice *[]ComputeAndTrackRoute_Feedback, cSlice CComputeAndTrackRoute_Feedback__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ComputeAndTrackRoute_Feedback, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ComputeAndTrackRoute_FeedbackTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ComputeAndTrackRoute_Feedback__Sequence_to_C(cSlice *CComputeAndTrackRoute_Feedback__Sequence, goSlice []ComputeAndTrackRoute_Feedback) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__ComputeAndTrackRoute_Feedback)(C.malloc(C.sizeof_struct_nav2_msgs__action__ComputeAndTrackRoute_Feedback * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ComputeAndTrackRoute_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ComputeAndTrackRoute_Feedback__Array_to_Go(goSlice []ComputeAndTrackRoute_Feedback, cSlice []CComputeAndTrackRoute_Feedback) {
	for i := 0; i < len(cSlice); i++ {
		ComputeAndTrackRoute_FeedbackTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ComputeAndTrackRoute_Feedback__Array_to_C(cSlice []CComputeAndTrackRoute_Feedback, goSlice []ComputeAndTrackRoute_Feedback) {
	for i := 0; i < len(goSlice); i++ {
		ComputeAndTrackRoute_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
