// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "dog-stream-gateway/internal/msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/compute_path_through_poses.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/ComputePathThroughPoses_SendGoal_Response", ComputePathThroughPoses_SendGoal_ResponseTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/ComputePathThroughPoses_SendGoal_Response", ComputePathThroughPoses_SendGoal_ResponseTypeSupport)
}

type ComputePathThroughPoses_SendGoal_Response struct {
	Accepted bool `yaml:"accepted"`
	Stamp builtin_interfaces_msg.Time `yaml:"stamp"`
}

// NewComputePathThroughPoses_SendGoal_Response creates a new ComputePathThroughPoses_SendGoal_Response with default values.
func NewComputePathThroughPoses_SendGoal_Response() *ComputePathThroughPoses_SendGoal_Response {
	self := ComputePathThroughPoses_SendGoal_Response{}
	self.SetDefaults()
	return &self
}

func (t *ComputePathThroughPoses_SendGoal_Response) Clone() *ComputePathThroughPoses_SendGoal_Response {
	c := &ComputePathThroughPoses_SendGoal_Response{}
	c.Accepted = t.Accepted
	c.Stamp = *t.Stamp.Clone()
	return c
}

func (t *ComputePathThroughPoses_SendGoal_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ComputePathThroughPoses_SendGoal_Response) SetDefaults() {
	t.Accepted = false
	t.Stamp.SetDefaults()
}

func (t *ComputePathThroughPoses_SendGoal_Response) GetTypeSupport() types.MessageTypeSupport {
	return ComputePathThroughPoses_SendGoal_ResponseTypeSupport
}
func (t *ComputePathThroughPoses_SendGoal_Response) GetGoalAccepted() bool {
	return t.Accepted
}

// ComputePathThroughPoses_SendGoal_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ComputePathThroughPoses_SendGoal_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewComputePathThroughPoses_SendGoal_ResponsePublisher creates and returns a new publisher for the
// ComputePathThroughPoses_SendGoal_Response
func NewComputePathThroughPoses_SendGoal_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ComputePathThroughPoses_SendGoal_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, ComputePathThroughPoses_SendGoal_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ComputePathThroughPoses_SendGoal_ResponsePublisher{pub}, nil
}

func (p *ComputePathThroughPoses_SendGoal_ResponsePublisher) Publish(msg *ComputePathThroughPoses_SendGoal_Response) error {
	return p.Publisher.Publish(msg)
}

// ComputePathThroughPoses_SendGoal_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ComputePathThroughPoses_SendGoal_ResponseSubscription struct {
	*rclgo.Subscription
}

// ComputePathThroughPoses_SendGoal_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a ComputePathThroughPoses_SendGoal_ResponseSubscription.
type ComputePathThroughPoses_SendGoal_ResponseSubscriptionCallback func(msg *ComputePathThroughPoses_SendGoal_Response, info *rclgo.MessageInfo, err error)

// NewComputePathThroughPoses_SendGoal_ResponseSubscription creates and returns a new subscription for the
// ComputePathThroughPoses_SendGoal_Response
func NewComputePathThroughPoses_SendGoal_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ComputePathThroughPoses_SendGoal_ResponseSubscriptionCallback) (*ComputePathThroughPoses_SendGoal_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ComputePathThroughPoses_SendGoal_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ComputePathThroughPoses_SendGoal_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ComputePathThroughPoses_SendGoal_ResponseSubscription{sub}, nil
}

func (s *ComputePathThroughPoses_SendGoal_ResponseSubscription) TakeMessage(out *ComputePathThroughPoses_SendGoal_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneComputePathThroughPoses_SendGoal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneComputePathThroughPoses_SendGoal_ResponseSlice(dst, src []ComputePathThroughPoses_SendGoal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ComputePathThroughPoses_SendGoal_ResponseTypeSupport types.MessageTypeSupport = _ComputePathThroughPoses_SendGoal_ResponseTypeSupport{}

type _ComputePathThroughPoses_SendGoal_ResponseTypeSupport struct{}

func (t _ComputePathThroughPoses_SendGoal_ResponseTypeSupport) New() types.Message {
	return NewComputePathThroughPoses_SendGoal_Response()
}

func (t _ComputePathThroughPoses_SendGoal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response
	return (unsafe.Pointer)(C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response__create())
}

func (t _ComputePathThroughPoses_SendGoal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response__destroy((*C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response)(pointer_to_free))
}

func (t _ComputePathThroughPoses_SendGoal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ComputePathThroughPoses_SendGoal_Response)
	mem := (*C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response)(dst)
	mem.accepted = C.bool(m.Accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.stamp), &m.Stamp)
}

func (t _ComputePathThroughPoses_SendGoal_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ComputePathThroughPoses_SendGoal_Response)
	mem := (*C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response)(ros2_message_buffer)
	m.Accepted = bool(mem.accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Stamp, unsafe.Pointer(&mem.stamp))
}

func (t _ComputePathThroughPoses_SendGoal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response())
}

type CComputePathThroughPoses_SendGoal_Response = C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response
type CComputePathThroughPoses_SendGoal_Response__Sequence = C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response__Sequence

func ComputePathThroughPoses_SendGoal_Response__Sequence_to_Go(goSlice *[]ComputePathThroughPoses_SendGoal_Response, cSlice CComputePathThroughPoses_SendGoal_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ComputePathThroughPoses_SendGoal_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ComputePathThroughPoses_SendGoal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ComputePathThroughPoses_SendGoal_Response__Sequence_to_C(cSlice *CComputePathThroughPoses_SendGoal_Response__Sequence, goSlice []ComputePathThroughPoses_SendGoal_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response)(C.malloc(C.sizeof_struct_nav2_msgs__action__ComputePathThroughPoses_SendGoal_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ComputePathThroughPoses_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ComputePathThroughPoses_SendGoal_Response__Array_to_Go(goSlice []ComputePathThroughPoses_SendGoal_Response, cSlice []CComputePathThroughPoses_SendGoal_Response) {
	for i := 0; i < len(cSlice); i++ {
		ComputePathThroughPoses_SendGoal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ComputePathThroughPoses_SendGoal_Response__Array_to_C(cSlice []CComputePathThroughPoses_SendGoal_Response, goSlice []ComputePathThroughPoses_SendGoal_Response) {
	for i := 0; i < len(goSlice); i++ {
		ComputePathThroughPoses_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
