// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "dog-stream-gateway/internal/msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/dummy_behavior.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/DummyBehavior_SendGoal_Request", DummyBehavior_SendGoal_RequestTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/DummyBehavior_SendGoal_Request", DummyBehavior_SendGoal_RequestTypeSupport)
}

type DummyBehavior_SendGoal_Request struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Goal DummyBehavior_Goal `yaml:"goal"`
}

// NewDummyBehavior_SendGoal_Request creates a new DummyBehavior_SendGoal_Request with default values.
func NewDummyBehavior_SendGoal_Request() *DummyBehavior_SendGoal_Request {
	self := DummyBehavior_SendGoal_Request{}
	self.SetDefaults()
	return &self
}

func (t *DummyBehavior_SendGoal_Request) Clone() *DummyBehavior_SendGoal_Request {
	c := &DummyBehavior_SendGoal_Request{}
	c.GoalID = *t.GoalID.Clone()
	c.Goal = *t.Goal.Clone()
	return c
}

func (t *DummyBehavior_SendGoal_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *DummyBehavior_SendGoal_Request) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Goal.SetDefaults()
}

func (t *DummyBehavior_SendGoal_Request) GetTypeSupport() types.MessageTypeSupport {
	return DummyBehavior_SendGoal_RequestTypeSupport
}
func (t *DummyBehavior_SendGoal_Request) GetGoalID() *types.GoalID {
	return (*types.GoalID)(&t.GoalID.Uuid)
}

func (t *DummyBehavior_SendGoal_Request) SetGoalID(id *types.GoalID) {
	t.GoalID.Uuid = *id
}
func (t *DummyBehavior_SendGoal_Request) GetGoalDescription() types.Message {
	return &t.Goal
}

func (t *DummyBehavior_SendGoal_Request) SetGoalDescription(desc types.Message) {
	t.Goal = *desc.(*DummyBehavior_Goal)
}

// DummyBehavior_SendGoal_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type DummyBehavior_SendGoal_RequestPublisher struct {
	*rclgo.Publisher
}

// NewDummyBehavior_SendGoal_RequestPublisher creates and returns a new publisher for the
// DummyBehavior_SendGoal_Request
func NewDummyBehavior_SendGoal_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*DummyBehavior_SendGoal_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, DummyBehavior_SendGoal_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DummyBehavior_SendGoal_RequestPublisher{pub}, nil
}

func (p *DummyBehavior_SendGoal_RequestPublisher) Publish(msg *DummyBehavior_SendGoal_Request) error {
	return p.Publisher.Publish(msg)
}

// DummyBehavior_SendGoal_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type DummyBehavior_SendGoal_RequestSubscription struct {
	*rclgo.Subscription
}

// DummyBehavior_SendGoal_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a DummyBehavior_SendGoal_RequestSubscription.
type DummyBehavior_SendGoal_RequestSubscriptionCallback func(msg *DummyBehavior_SendGoal_Request, info *rclgo.MessageInfo, err error)

// NewDummyBehavior_SendGoal_RequestSubscription creates and returns a new subscription for the
// DummyBehavior_SendGoal_Request
func NewDummyBehavior_SendGoal_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback DummyBehavior_SendGoal_RequestSubscriptionCallback) (*DummyBehavior_SendGoal_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg DummyBehavior_SendGoal_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, DummyBehavior_SendGoal_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &DummyBehavior_SendGoal_RequestSubscription{sub}, nil
}

func (s *DummyBehavior_SendGoal_RequestSubscription) TakeMessage(out *DummyBehavior_SendGoal_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneDummyBehavior_SendGoal_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneDummyBehavior_SendGoal_RequestSlice(dst, src []DummyBehavior_SendGoal_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var DummyBehavior_SendGoal_RequestTypeSupport types.MessageTypeSupport = _DummyBehavior_SendGoal_RequestTypeSupport{}

type _DummyBehavior_SendGoal_RequestTypeSupport struct{}

func (t _DummyBehavior_SendGoal_RequestTypeSupport) New() types.Message {
	return NewDummyBehavior_SendGoal_Request()
}

func (t _DummyBehavior_SendGoal_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__DummyBehavior_SendGoal_Request
	return (unsafe.Pointer)(C.nav2_msgs__action__DummyBehavior_SendGoal_Request__create())
}

func (t _DummyBehavior_SendGoal_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__DummyBehavior_SendGoal_Request__destroy((*C.nav2_msgs__action__DummyBehavior_SendGoal_Request)(pointer_to_free))
}

func (t _DummyBehavior_SendGoal_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*DummyBehavior_SendGoal_Request)
	mem := (*C.nav2_msgs__action__DummyBehavior_SendGoal_Request)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	DummyBehavior_GoalTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal), &m.Goal)
}

func (t _DummyBehavior_SendGoal_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*DummyBehavior_SendGoal_Request)
	mem := (*C.nav2_msgs__action__DummyBehavior_SendGoal_Request)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	DummyBehavior_GoalTypeSupport.AsGoStruct(&m.Goal, unsafe.Pointer(&mem.goal))
}

func (t _DummyBehavior_SendGoal_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__DummyBehavior_SendGoal_Request())
}

type CDummyBehavior_SendGoal_Request = C.nav2_msgs__action__DummyBehavior_SendGoal_Request
type CDummyBehavior_SendGoal_Request__Sequence = C.nav2_msgs__action__DummyBehavior_SendGoal_Request__Sequence

func DummyBehavior_SendGoal_Request__Sequence_to_Go(goSlice *[]DummyBehavior_SendGoal_Request, cSlice CDummyBehavior_SendGoal_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]DummyBehavior_SendGoal_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		DummyBehavior_SendGoal_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func DummyBehavior_SendGoal_Request__Sequence_to_C(cSlice *CDummyBehavior_SendGoal_Request__Sequence, goSlice []DummyBehavior_SendGoal_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__DummyBehavior_SendGoal_Request)(C.malloc(C.sizeof_struct_nav2_msgs__action__DummyBehavior_SendGoal_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		DummyBehavior_SendGoal_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func DummyBehavior_SendGoal_Request__Array_to_Go(goSlice []DummyBehavior_SendGoal_Request, cSlice []CDummyBehavior_SendGoal_Request) {
	for i := 0; i < len(cSlice); i++ {
		DummyBehavior_SendGoal_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func DummyBehavior_SendGoal_Request__Array_to_C(cSlice []CDummyBehavior_SendGoal_Request, goSlice []DummyBehavior_SendGoal_Request) {
	for i := 0; i < len(goSlice); i++ {
		DummyBehavior_SendGoal_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
