// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <nav2_msgs/action/follow_path.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("nav2_msgs/FollowPath_GetResult", FollowPath_GetResultTypeSupport)
	typemap.RegisterService("nav2_msgs/action/FollowPath_GetResult", FollowPath_GetResultTypeSupport)
}

type _FollowPath_GetResultTypeSupport struct {}

func (s _FollowPath_GetResultTypeSupport) Request() types.MessageTypeSupport {
	return FollowPath_GetResult_RequestTypeSupport
}

func (s _FollowPath_GetResultTypeSupport) Response() types.MessageTypeSupport {
	return FollowPath_GetResult_ResponseTypeSupport
}

func (s _FollowPath_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__nav2_msgs__action__FollowPath_GetResult())
}

// Modifying this variable is undefined behavior.
var FollowPath_GetResultTypeSupport types.ServiceTypeSupport = _FollowPath_GetResultTypeSupport{}

// FollowPath_GetResultClient wraps rclgo.Client to provide type safe helper
// functions
type FollowPath_GetResultClient struct {
	*rclgo.Client
}

// NewFollowPath_GetResultClient creates and returns a new client for the
// FollowPath_GetResult
func NewFollowPath_GetResultClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*FollowPath_GetResultClient, error) {
	client, err := node.NewClient(serviceName, FollowPath_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowPath_GetResultClient{client}, nil
}

func (s *FollowPath_GetResultClient) Send(ctx context.Context, req *FollowPath_GetResult_Request) (*FollowPath_GetResult_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FollowPath_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FollowPath_GetResultServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s FollowPath_GetResultServiceResponseSender) SendResponse(resp *FollowPath_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type FollowPath_GetResultServiceRequestHandler func(*rclgo.ServiceInfo, *FollowPath_GetResult_Request, FollowPath_GetResultServiceResponseSender)

// FollowPath_GetResultService wraps rclgo.Service to provide type safe helper
// functions
type FollowPath_GetResultService struct {
	*rclgo.Service
}

// NewFollowPath_GetResultService creates and returns a new service for the
// FollowPath_GetResult
func NewFollowPath_GetResultService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler FollowPath_GetResultServiceRequestHandler) (*FollowPath_GetResultService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*FollowPath_GetResult_Request)
		responseSender := FollowPath_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FollowPath_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FollowPath_GetResultService{service}, nil
}