// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "dog-stream-gateway/internal/msgs/builtin_interfaces/msg"
	geometry_msgs_msg "dog-stream-gateway/internal/msgs/geometry_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/navigate_through_poses.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/NavigateThroughPoses_Feedback", NavigateThroughPoses_FeedbackTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/NavigateThroughPoses_Feedback", NavigateThroughPoses_FeedbackTypeSupport)
}

type NavigateThroughPoses_Feedback struct {
	CurrentPose geometry_msgs_msg.PoseStamped `yaml:"current_pose"`// feedback definition
	NavigationTime builtin_interfaces_msg.Duration `yaml:"navigation_time"`
	EstimatedTimeRemaining builtin_interfaces_msg.Duration `yaml:"estimated_time_remaining"`
	NumberOfRecoveries int16 `yaml:"number_of_recoveries"`
	DistanceRemaining float32 `yaml:"distance_remaining"`
	NumberOfPosesRemaining int16 `yaml:"number_of_poses_remaining"`
}

// NewNavigateThroughPoses_Feedback creates a new NavigateThroughPoses_Feedback with default values.
func NewNavigateThroughPoses_Feedback() *NavigateThroughPoses_Feedback {
	self := NavigateThroughPoses_Feedback{}
	self.SetDefaults()
	return &self
}

func (t *NavigateThroughPoses_Feedback) Clone() *NavigateThroughPoses_Feedback {
	c := &NavigateThroughPoses_Feedback{}
	c.CurrentPose = *t.CurrentPose.Clone()
	c.NavigationTime = *t.NavigationTime.Clone()
	c.EstimatedTimeRemaining = *t.EstimatedTimeRemaining.Clone()
	c.NumberOfRecoveries = t.NumberOfRecoveries
	c.DistanceRemaining = t.DistanceRemaining
	c.NumberOfPosesRemaining = t.NumberOfPosesRemaining
	return c
}

func (t *NavigateThroughPoses_Feedback) CloneMsg() types.Message {
	return t.Clone()
}

func (t *NavigateThroughPoses_Feedback) SetDefaults() {
	t.CurrentPose.SetDefaults()
	t.NavigationTime.SetDefaults()
	t.EstimatedTimeRemaining.SetDefaults()
	t.NumberOfRecoveries = 0
	t.DistanceRemaining = 0
	t.NumberOfPosesRemaining = 0
}

func (t *NavigateThroughPoses_Feedback) GetTypeSupport() types.MessageTypeSupport {
	return NavigateThroughPoses_FeedbackTypeSupport
}

// NavigateThroughPoses_FeedbackPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type NavigateThroughPoses_FeedbackPublisher struct {
	*rclgo.Publisher
}

// NewNavigateThroughPoses_FeedbackPublisher creates and returns a new publisher for the
// NavigateThroughPoses_Feedback
func NewNavigateThroughPoses_FeedbackPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*NavigateThroughPoses_FeedbackPublisher, error) {
	pub, err := node.NewPublisher(topic_name, NavigateThroughPoses_FeedbackTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &NavigateThroughPoses_FeedbackPublisher{pub}, nil
}

func (p *NavigateThroughPoses_FeedbackPublisher) Publish(msg *NavigateThroughPoses_Feedback) error {
	return p.Publisher.Publish(msg)
}

// NavigateThroughPoses_FeedbackSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type NavigateThroughPoses_FeedbackSubscription struct {
	*rclgo.Subscription
}

// NavigateThroughPoses_FeedbackSubscriptionCallback type is used to provide a subscription
// handler function for a NavigateThroughPoses_FeedbackSubscription.
type NavigateThroughPoses_FeedbackSubscriptionCallback func(msg *NavigateThroughPoses_Feedback, info *rclgo.MessageInfo, err error)

// NewNavigateThroughPoses_FeedbackSubscription creates and returns a new subscription for the
// NavigateThroughPoses_Feedback
func NewNavigateThroughPoses_FeedbackSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback NavigateThroughPoses_FeedbackSubscriptionCallback) (*NavigateThroughPoses_FeedbackSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg NavigateThroughPoses_Feedback
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, NavigateThroughPoses_FeedbackTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &NavigateThroughPoses_FeedbackSubscription{sub}, nil
}

func (s *NavigateThroughPoses_FeedbackSubscription) TakeMessage(out *NavigateThroughPoses_Feedback) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneNavigateThroughPoses_FeedbackSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneNavigateThroughPoses_FeedbackSlice(dst, src []NavigateThroughPoses_Feedback) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var NavigateThroughPoses_FeedbackTypeSupport types.MessageTypeSupport = _NavigateThroughPoses_FeedbackTypeSupport{}

type _NavigateThroughPoses_FeedbackTypeSupport struct{}

func (t _NavigateThroughPoses_FeedbackTypeSupport) New() types.Message {
	return NewNavigateThroughPoses_Feedback()
}

func (t _NavigateThroughPoses_FeedbackTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__NavigateThroughPoses_Feedback
	return (unsafe.Pointer)(C.nav2_msgs__action__NavigateThroughPoses_Feedback__create())
}

func (t _NavigateThroughPoses_FeedbackTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__NavigateThroughPoses_Feedback__destroy((*C.nav2_msgs__action__NavigateThroughPoses_Feedback)(pointer_to_free))
}

func (t _NavigateThroughPoses_FeedbackTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*NavigateThroughPoses_Feedback)
	mem := (*C.nav2_msgs__action__NavigateThroughPoses_Feedback)(dst)
	geometry_msgs_msg.PoseStampedTypeSupport.AsCStruct(unsafe.Pointer(&mem.current_pose), &m.CurrentPose)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.navigation_time), &m.NavigationTime)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.estimated_time_remaining), &m.EstimatedTimeRemaining)
	mem.number_of_recoveries = C.int16_t(m.NumberOfRecoveries)
	mem.distance_remaining = C.float(m.DistanceRemaining)
	mem.number_of_poses_remaining = C.int16_t(m.NumberOfPosesRemaining)
}

func (t _NavigateThroughPoses_FeedbackTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*NavigateThroughPoses_Feedback)
	mem := (*C.nav2_msgs__action__NavigateThroughPoses_Feedback)(ros2_message_buffer)
	geometry_msgs_msg.PoseStampedTypeSupport.AsGoStruct(&m.CurrentPose, unsafe.Pointer(&mem.current_pose))
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.NavigationTime, unsafe.Pointer(&mem.navigation_time))
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.EstimatedTimeRemaining, unsafe.Pointer(&mem.estimated_time_remaining))
	m.NumberOfRecoveries = int16(mem.number_of_recoveries)
	m.DistanceRemaining = float32(mem.distance_remaining)
	m.NumberOfPosesRemaining = int16(mem.number_of_poses_remaining)
}

func (t _NavigateThroughPoses_FeedbackTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__NavigateThroughPoses_Feedback())
}

type CNavigateThroughPoses_Feedback = C.nav2_msgs__action__NavigateThroughPoses_Feedback
type CNavigateThroughPoses_Feedback__Sequence = C.nav2_msgs__action__NavigateThroughPoses_Feedback__Sequence

func NavigateThroughPoses_Feedback__Sequence_to_Go(goSlice *[]NavigateThroughPoses_Feedback, cSlice CNavigateThroughPoses_Feedback__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]NavigateThroughPoses_Feedback, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		NavigateThroughPoses_FeedbackTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func NavigateThroughPoses_Feedback__Sequence_to_C(cSlice *CNavigateThroughPoses_Feedback__Sequence, goSlice []NavigateThroughPoses_Feedback) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__NavigateThroughPoses_Feedback)(C.malloc(C.sizeof_struct_nav2_msgs__action__NavigateThroughPoses_Feedback * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		NavigateThroughPoses_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func NavigateThroughPoses_Feedback__Array_to_Go(goSlice []NavigateThroughPoses_Feedback, cSlice []CNavigateThroughPoses_Feedback) {
	for i := 0; i < len(cSlice); i++ {
		NavigateThroughPoses_FeedbackTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func NavigateThroughPoses_Feedback__Array_to_C(cSlice []CNavigateThroughPoses_Feedback, goSlice []NavigateThroughPoses_Feedback) {
	for i := 0; i < len(goSlice); i++ {
		NavigateThroughPoses_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
