// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "dog-stream-gateway/internal/msgs/builtin_interfaces/msg"
	geometry_msgs_msg "dog-stream-gateway/internal/msgs/geometry_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/navigate_to_pose.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/NavigateToPose_Feedback", NavigateToPose_FeedbackTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/NavigateToPose_Feedback", NavigateToPose_FeedbackTypeSupport)
}

type NavigateToPose_Feedback struct {
	CurrentPose geometry_msgs_msg.PoseStamped `yaml:"current_pose"`// feedback definition
	NavigationTime builtin_interfaces_msg.Duration `yaml:"navigation_time"`
	EstimatedTimeRemaining builtin_interfaces_msg.Duration `yaml:"estimated_time_remaining"`
	NumberOfRecoveries int16 `yaml:"number_of_recoveries"`
	DistanceRemaining float32 `yaml:"distance_remaining"`
}

// NewNavigateToPose_Feedback creates a new NavigateToPose_Feedback with default values.
func NewNavigateToPose_Feedback() *NavigateToPose_Feedback {
	self := NavigateToPose_Feedback{}
	self.SetDefaults()
	return &self
}

func (t *NavigateToPose_Feedback) Clone() *NavigateToPose_Feedback {
	c := &NavigateToPose_Feedback{}
	c.CurrentPose = *t.CurrentPose.Clone()
	c.NavigationTime = *t.NavigationTime.Clone()
	c.EstimatedTimeRemaining = *t.EstimatedTimeRemaining.Clone()
	c.NumberOfRecoveries = t.NumberOfRecoveries
	c.DistanceRemaining = t.DistanceRemaining
	return c
}

func (t *NavigateToPose_Feedback) CloneMsg() types.Message {
	return t.Clone()
}

func (t *NavigateToPose_Feedback) SetDefaults() {
	t.CurrentPose.SetDefaults()
	t.NavigationTime.SetDefaults()
	t.EstimatedTimeRemaining.SetDefaults()
	t.NumberOfRecoveries = 0
	t.DistanceRemaining = 0
}

func (t *NavigateToPose_Feedback) GetTypeSupport() types.MessageTypeSupport {
	return NavigateToPose_FeedbackTypeSupport
}

// NavigateToPose_FeedbackPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type NavigateToPose_FeedbackPublisher struct {
	*rclgo.Publisher
}

// NewNavigateToPose_FeedbackPublisher creates and returns a new publisher for the
// NavigateToPose_Feedback
func NewNavigateToPose_FeedbackPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*NavigateToPose_FeedbackPublisher, error) {
	pub, err := node.NewPublisher(topic_name, NavigateToPose_FeedbackTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &NavigateToPose_FeedbackPublisher{pub}, nil
}

func (p *NavigateToPose_FeedbackPublisher) Publish(msg *NavigateToPose_Feedback) error {
	return p.Publisher.Publish(msg)
}

// NavigateToPose_FeedbackSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type NavigateToPose_FeedbackSubscription struct {
	*rclgo.Subscription
}

// NavigateToPose_FeedbackSubscriptionCallback type is used to provide a subscription
// handler function for a NavigateToPose_FeedbackSubscription.
type NavigateToPose_FeedbackSubscriptionCallback func(msg *NavigateToPose_Feedback, info *rclgo.MessageInfo, err error)

// NewNavigateToPose_FeedbackSubscription creates and returns a new subscription for the
// NavigateToPose_Feedback
func NewNavigateToPose_FeedbackSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback NavigateToPose_FeedbackSubscriptionCallback) (*NavigateToPose_FeedbackSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg NavigateToPose_Feedback
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, NavigateToPose_FeedbackTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &NavigateToPose_FeedbackSubscription{sub}, nil
}

func (s *NavigateToPose_FeedbackSubscription) TakeMessage(out *NavigateToPose_Feedback) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneNavigateToPose_FeedbackSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneNavigateToPose_FeedbackSlice(dst, src []NavigateToPose_Feedback) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var NavigateToPose_FeedbackTypeSupport types.MessageTypeSupport = _NavigateToPose_FeedbackTypeSupport{}

type _NavigateToPose_FeedbackTypeSupport struct{}

func (t _NavigateToPose_FeedbackTypeSupport) New() types.Message {
	return NewNavigateToPose_Feedback()
}

func (t _NavigateToPose_FeedbackTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__NavigateToPose_Feedback
	return (unsafe.Pointer)(C.nav2_msgs__action__NavigateToPose_Feedback__create())
}

func (t _NavigateToPose_FeedbackTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__NavigateToPose_Feedback__destroy((*C.nav2_msgs__action__NavigateToPose_Feedback)(pointer_to_free))
}

func (t _NavigateToPose_FeedbackTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*NavigateToPose_Feedback)
	mem := (*C.nav2_msgs__action__NavigateToPose_Feedback)(dst)
	geometry_msgs_msg.PoseStampedTypeSupport.AsCStruct(unsafe.Pointer(&mem.current_pose), &m.CurrentPose)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.navigation_time), &m.NavigationTime)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.estimated_time_remaining), &m.EstimatedTimeRemaining)
	mem.number_of_recoveries = C.int16_t(m.NumberOfRecoveries)
	mem.distance_remaining = C.float(m.DistanceRemaining)
}

func (t _NavigateToPose_FeedbackTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*NavigateToPose_Feedback)
	mem := (*C.nav2_msgs__action__NavigateToPose_Feedback)(ros2_message_buffer)
	geometry_msgs_msg.PoseStampedTypeSupport.AsGoStruct(&m.CurrentPose, unsafe.Pointer(&mem.current_pose))
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.NavigationTime, unsafe.Pointer(&mem.navigation_time))
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.EstimatedTimeRemaining, unsafe.Pointer(&mem.estimated_time_remaining))
	m.NumberOfRecoveries = int16(mem.number_of_recoveries)
	m.DistanceRemaining = float32(mem.distance_remaining)
}

func (t _NavigateToPose_FeedbackTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__NavigateToPose_Feedback())
}

type CNavigateToPose_Feedback = C.nav2_msgs__action__NavigateToPose_Feedback
type CNavigateToPose_Feedback__Sequence = C.nav2_msgs__action__NavigateToPose_Feedback__Sequence

func NavigateToPose_Feedback__Sequence_to_Go(goSlice *[]NavigateToPose_Feedback, cSlice CNavigateToPose_Feedback__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]NavigateToPose_Feedback, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		NavigateToPose_FeedbackTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func NavigateToPose_Feedback__Sequence_to_C(cSlice *CNavigateToPose_Feedback__Sequence, goSlice []NavigateToPose_Feedback) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__NavigateToPose_Feedback)(C.malloc(C.sizeof_struct_nav2_msgs__action__NavigateToPose_Feedback * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		NavigateToPose_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func NavigateToPose_Feedback__Array_to_Go(goSlice []NavigateToPose_Feedback, cSlice []CNavigateToPose_Feedback) {
	for i := 0; i < len(cSlice); i++ {
		NavigateToPose_FeedbackTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func NavigateToPose_Feedback__Array_to_C(cSlice []CNavigateToPose_Feedback, goSlice []NavigateToPose_Feedback) {
	for i := 0; i < len(goSlice); i++ {
		NavigateToPose_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
