// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "dog-stream-gateway/internal/msgs/builtin_interfaces/msg"
	nav_msgs_msg "dog-stream-gateway/internal/msgs/nav_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/smooth_path.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/SmoothPath_Goal", SmoothPath_GoalTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/SmoothPath_Goal", SmoothPath_GoalTypeSupport)
}

type SmoothPath_Goal struct {
	Path nav_msgs_msg.Path `yaml:"path"`// goal definition
	SmootherId string `yaml:"smoother_id"`
	MaxSmoothingDuration builtin_interfaces_msg.Duration `yaml:"max_smoothing_duration"`
	CheckForCollisions bool `yaml:"check_for_collisions"`
}

// NewSmoothPath_Goal creates a new SmoothPath_Goal with default values.
func NewSmoothPath_Goal() *SmoothPath_Goal {
	self := SmoothPath_Goal{}
	self.SetDefaults()
	return &self
}

func (t *SmoothPath_Goal) Clone() *SmoothPath_Goal {
	c := &SmoothPath_Goal{}
	c.Path = *t.Path.Clone()
	c.SmootherId = t.SmootherId
	c.MaxSmoothingDuration = *t.MaxSmoothingDuration.Clone()
	c.CheckForCollisions = t.CheckForCollisions
	return c
}

func (t *SmoothPath_Goal) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SmoothPath_Goal) SetDefaults() {
	t.Path.SetDefaults()
	t.SmootherId = ""
	t.MaxSmoothingDuration.SetDefaults()
	t.CheckForCollisions = false
}

func (t *SmoothPath_Goal) GetTypeSupport() types.MessageTypeSupport {
	return SmoothPath_GoalTypeSupport
}

// SmoothPath_GoalPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SmoothPath_GoalPublisher struct {
	*rclgo.Publisher
}

// NewSmoothPath_GoalPublisher creates and returns a new publisher for the
// SmoothPath_Goal
func NewSmoothPath_GoalPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SmoothPath_GoalPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SmoothPath_GoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SmoothPath_GoalPublisher{pub}, nil
}

func (p *SmoothPath_GoalPublisher) Publish(msg *SmoothPath_Goal) error {
	return p.Publisher.Publish(msg)
}

// SmoothPath_GoalSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SmoothPath_GoalSubscription struct {
	*rclgo.Subscription
}

// SmoothPath_GoalSubscriptionCallback type is used to provide a subscription
// handler function for a SmoothPath_GoalSubscription.
type SmoothPath_GoalSubscriptionCallback func(msg *SmoothPath_Goal, info *rclgo.MessageInfo, err error)

// NewSmoothPath_GoalSubscription creates and returns a new subscription for the
// SmoothPath_Goal
func NewSmoothPath_GoalSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SmoothPath_GoalSubscriptionCallback) (*SmoothPath_GoalSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SmoothPath_Goal
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SmoothPath_GoalTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SmoothPath_GoalSubscription{sub}, nil
}

func (s *SmoothPath_GoalSubscription) TakeMessage(out *SmoothPath_Goal) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSmoothPath_GoalSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSmoothPath_GoalSlice(dst, src []SmoothPath_Goal) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SmoothPath_GoalTypeSupport types.MessageTypeSupport = _SmoothPath_GoalTypeSupport{}

type _SmoothPath_GoalTypeSupport struct{}

func (t _SmoothPath_GoalTypeSupport) New() types.Message {
	return NewSmoothPath_Goal()
}

func (t _SmoothPath_GoalTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__SmoothPath_Goal
	return (unsafe.Pointer)(C.nav2_msgs__action__SmoothPath_Goal__create())
}

func (t _SmoothPath_GoalTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__SmoothPath_Goal__destroy((*C.nav2_msgs__action__SmoothPath_Goal)(pointer_to_free))
}

func (t _SmoothPath_GoalTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SmoothPath_Goal)
	mem := (*C.nav2_msgs__action__SmoothPath_Goal)(dst)
	nav_msgs_msg.PathTypeSupport.AsCStruct(unsafe.Pointer(&mem.path), &m.Path)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.smoother_id), m.SmootherId)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.max_smoothing_duration), &m.MaxSmoothingDuration)
	mem.check_for_collisions = C.bool(m.CheckForCollisions)
}

func (t _SmoothPath_GoalTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SmoothPath_Goal)
	mem := (*C.nav2_msgs__action__SmoothPath_Goal)(ros2_message_buffer)
	nav_msgs_msg.PathTypeSupport.AsGoStruct(&m.Path, unsafe.Pointer(&mem.path))
	primitives.StringAsGoStruct(&m.SmootherId, unsafe.Pointer(&mem.smoother_id))
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.MaxSmoothingDuration, unsafe.Pointer(&mem.max_smoothing_duration))
	m.CheckForCollisions = bool(mem.check_for_collisions)
}

func (t _SmoothPath_GoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__SmoothPath_Goal())
}

type CSmoothPath_Goal = C.nav2_msgs__action__SmoothPath_Goal
type CSmoothPath_Goal__Sequence = C.nav2_msgs__action__SmoothPath_Goal__Sequence

func SmoothPath_Goal__Sequence_to_Go(goSlice *[]SmoothPath_Goal, cSlice CSmoothPath_Goal__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SmoothPath_Goal, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SmoothPath_GoalTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SmoothPath_Goal__Sequence_to_C(cSlice *CSmoothPath_Goal__Sequence, goSlice []SmoothPath_Goal) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__SmoothPath_Goal)(C.malloc(C.sizeof_struct_nav2_msgs__action__SmoothPath_Goal * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SmoothPath_GoalTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SmoothPath_Goal__Array_to_Go(goSlice []SmoothPath_Goal, cSlice []CSmoothPath_Goal) {
	for i := 0; i < len(cSlice); i++ {
		SmoothPath_GoalTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SmoothPath_Goal__Array_to_C(cSlice []CSmoothPath_Goal, goSlice []SmoothPath_Goal) {
	for i := 0; i < len(goSlice); i++ {
		SmoothPath_GoalTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
