// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/smooth_path.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/SmoothPath_Feedback", SmoothPath_FeedbackTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/SmoothPath_Feedback", SmoothPath_FeedbackTypeSupport)
}

type SmoothPath_Feedback struct {
}

// NewSmoothPath_Feedback creates a new SmoothPath_Feedback with default values.
func NewSmoothPath_Feedback() *SmoothPath_Feedback {
	self := SmoothPath_Feedback{}
	self.SetDefaults()
	return &self
}

func (t *SmoothPath_Feedback) Clone() *SmoothPath_Feedback {
	c := &SmoothPath_Feedback{}
	return c
}

func (t *SmoothPath_Feedback) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SmoothPath_Feedback) SetDefaults() {
}

func (t *SmoothPath_Feedback) GetTypeSupport() types.MessageTypeSupport {
	return SmoothPath_FeedbackTypeSupport
}

// SmoothPath_FeedbackPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SmoothPath_FeedbackPublisher struct {
	*rclgo.Publisher
}

// NewSmoothPath_FeedbackPublisher creates and returns a new publisher for the
// SmoothPath_Feedback
func NewSmoothPath_FeedbackPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SmoothPath_FeedbackPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SmoothPath_FeedbackTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SmoothPath_FeedbackPublisher{pub}, nil
}

func (p *SmoothPath_FeedbackPublisher) Publish(msg *SmoothPath_Feedback) error {
	return p.Publisher.Publish(msg)
}

// SmoothPath_FeedbackSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SmoothPath_FeedbackSubscription struct {
	*rclgo.Subscription
}

// SmoothPath_FeedbackSubscriptionCallback type is used to provide a subscription
// handler function for a SmoothPath_FeedbackSubscription.
type SmoothPath_FeedbackSubscriptionCallback func(msg *SmoothPath_Feedback, info *rclgo.MessageInfo, err error)

// NewSmoothPath_FeedbackSubscription creates and returns a new subscription for the
// SmoothPath_Feedback
func NewSmoothPath_FeedbackSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SmoothPath_FeedbackSubscriptionCallback) (*SmoothPath_FeedbackSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SmoothPath_Feedback
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SmoothPath_FeedbackTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SmoothPath_FeedbackSubscription{sub}, nil
}

func (s *SmoothPath_FeedbackSubscription) TakeMessage(out *SmoothPath_Feedback) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSmoothPath_FeedbackSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSmoothPath_FeedbackSlice(dst, src []SmoothPath_Feedback) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SmoothPath_FeedbackTypeSupport types.MessageTypeSupport = _SmoothPath_FeedbackTypeSupport{}

type _SmoothPath_FeedbackTypeSupport struct{}

func (t _SmoothPath_FeedbackTypeSupport) New() types.Message {
	return NewSmoothPath_Feedback()
}

func (t _SmoothPath_FeedbackTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__SmoothPath_Feedback
	return (unsafe.Pointer)(C.nav2_msgs__action__SmoothPath_Feedback__create())
}

func (t _SmoothPath_FeedbackTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__SmoothPath_Feedback__destroy((*C.nav2_msgs__action__SmoothPath_Feedback)(pointer_to_free))
}

func (t _SmoothPath_FeedbackTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _SmoothPath_FeedbackTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _SmoothPath_FeedbackTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__SmoothPath_Feedback())
}

type CSmoothPath_Feedback = C.nav2_msgs__action__SmoothPath_Feedback
type CSmoothPath_Feedback__Sequence = C.nav2_msgs__action__SmoothPath_Feedback__Sequence

func SmoothPath_Feedback__Sequence_to_Go(goSlice *[]SmoothPath_Feedback, cSlice CSmoothPath_Feedback__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SmoothPath_Feedback, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SmoothPath_FeedbackTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SmoothPath_Feedback__Sequence_to_C(cSlice *CSmoothPath_Feedback__Sequence, goSlice []SmoothPath_Feedback) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__SmoothPath_Feedback)(C.malloc(C.sizeof_struct_nav2_msgs__action__SmoothPath_Feedback * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SmoothPath_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SmoothPath_Feedback__Array_to_Go(goSlice []SmoothPath_Feedback, cSlice []CSmoothPath_Feedback) {
	for i := 0; i < len(cSlice); i++ {
		SmoothPath_FeedbackTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SmoothPath_Feedback__Array_to_C(cSlice []CSmoothPath_Feedback, goSlice []SmoothPath_Feedback) {
	for i := 0; i < len(goSlice); i++ {
		SmoothPath_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
