// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "dog-stream-gateway/internal/msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/smooth_path.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/SmoothPath_FeedbackMessage", SmoothPath_FeedbackMessageTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/SmoothPath_FeedbackMessage", SmoothPath_FeedbackMessageTypeSupport)
}

type SmoothPath_FeedbackMessage struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Feedback SmoothPath_Feedback `yaml:"feedback"`
}

// NewSmoothPath_FeedbackMessage creates a new SmoothPath_FeedbackMessage with default values.
func NewSmoothPath_FeedbackMessage() *SmoothPath_FeedbackMessage {
	self := SmoothPath_FeedbackMessage{}
	self.SetDefaults()
	return &self
}

func (t *SmoothPath_FeedbackMessage) Clone() *SmoothPath_FeedbackMessage {
	c := &SmoothPath_FeedbackMessage{}
	c.GoalID = *t.GoalID.Clone()
	c.Feedback = *t.Feedback.Clone()
	return c
}

func (t *SmoothPath_FeedbackMessage) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SmoothPath_FeedbackMessage) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Feedback.SetDefaults()
}

func (t *SmoothPath_FeedbackMessage) GetTypeSupport() types.MessageTypeSupport {
	return SmoothPath_FeedbackMessageTypeSupport
}
func (t *SmoothPath_FeedbackMessage) GetGoalID() *types.GoalID {
	return (*types.GoalID)(&t.GoalID.Uuid)
}

func (t *SmoothPath_FeedbackMessage) SetGoalID(id *types.GoalID) {
	t.GoalID.Uuid = *id
}

// SmoothPath_FeedbackMessagePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SmoothPath_FeedbackMessagePublisher struct {
	*rclgo.Publisher
}

// NewSmoothPath_FeedbackMessagePublisher creates and returns a new publisher for the
// SmoothPath_FeedbackMessage
func NewSmoothPath_FeedbackMessagePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SmoothPath_FeedbackMessagePublisher, error) {
	pub, err := node.NewPublisher(topic_name, SmoothPath_FeedbackMessageTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SmoothPath_FeedbackMessagePublisher{pub}, nil
}

func (p *SmoothPath_FeedbackMessagePublisher) Publish(msg *SmoothPath_FeedbackMessage) error {
	return p.Publisher.Publish(msg)
}

// SmoothPath_FeedbackMessageSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SmoothPath_FeedbackMessageSubscription struct {
	*rclgo.Subscription
}

// SmoothPath_FeedbackMessageSubscriptionCallback type is used to provide a subscription
// handler function for a SmoothPath_FeedbackMessageSubscription.
type SmoothPath_FeedbackMessageSubscriptionCallback func(msg *SmoothPath_FeedbackMessage, info *rclgo.MessageInfo, err error)

// NewSmoothPath_FeedbackMessageSubscription creates and returns a new subscription for the
// SmoothPath_FeedbackMessage
func NewSmoothPath_FeedbackMessageSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SmoothPath_FeedbackMessageSubscriptionCallback) (*SmoothPath_FeedbackMessageSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SmoothPath_FeedbackMessage
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SmoothPath_FeedbackMessageTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SmoothPath_FeedbackMessageSubscription{sub}, nil
}

func (s *SmoothPath_FeedbackMessageSubscription) TakeMessage(out *SmoothPath_FeedbackMessage) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSmoothPath_FeedbackMessageSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSmoothPath_FeedbackMessageSlice(dst, src []SmoothPath_FeedbackMessage) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SmoothPath_FeedbackMessageTypeSupport types.MessageTypeSupport = _SmoothPath_FeedbackMessageTypeSupport{}

type _SmoothPath_FeedbackMessageTypeSupport struct{}

func (t _SmoothPath_FeedbackMessageTypeSupport) New() types.Message {
	return NewSmoothPath_FeedbackMessage()
}

func (t _SmoothPath_FeedbackMessageTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__SmoothPath_FeedbackMessage
	return (unsafe.Pointer)(C.nav2_msgs__action__SmoothPath_FeedbackMessage__create())
}

func (t _SmoothPath_FeedbackMessageTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__SmoothPath_FeedbackMessage__destroy((*C.nav2_msgs__action__SmoothPath_FeedbackMessage)(pointer_to_free))
}

func (t _SmoothPath_FeedbackMessageTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SmoothPath_FeedbackMessage)
	mem := (*C.nav2_msgs__action__SmoothPath_FeedbackMessage)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	SmoothPath_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&mem.feedback), &m.Feedback)
}

func (t _SmoothPath_FeedbackMessageTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SmoothPath_FeedbackMessage)
	mem := (*C.nav2_msgs__action__SmoothPath_FeedbackMessage)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	SmoothPath_FeedbackTypeSupport.AsGoStruct(&m.Feedback, unsafe.Pointer(&mem.feedback))
}

func (t _SmoothPath_FeedbackMessageTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__SmoothPath_FeedbackMessage())
}

type CSmoothPath_FeedbackMessage = C.nav2_msgs__action__SmoothPath_FeedbackMessage
type CSmoothPath_FeedbackMessage__Sequence = C.nav2_msgs__action__SmoothPath_FeedbackMessage__Sequence

func SmoothPath_FeedbackMessage__Sequence_to_Go(goSlice *[]SmoothPath_FeedbackMessage, cSlice CSmoothPath_FeedbackMessage__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SmoothPath_FeedbackMessage, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SmoothPath_FeedbackMessageTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SmoothPath_FeedbackMessage__Sequence_to_C(cSlice *CSmoothPath_FeedbackMessage__Sequence, goSlice []SmoothPath_FeedbackMessage) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__SmoothPath_FeedbackMessage)(C.malloc(C.sizeof_struct_nav2_msgs__action__SmoothPath_FeedbackMessage * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SmoothPath_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SmoothPath_FeedbackMessage__Array_to_Go(goSlice []SmoothPath_FeedbackMessage, cSlice []CSmoothPath_FeedbackMessage) {
	for i := 0; i < len(cSlice); i++ {
		SmoothPath_FeedbackMessageTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SmoothPath_FeedbackMessage__Array_to_C(cSlice []CSmoothPath_FeedbackMessage, goSlice []SmoothPath_FeedbackMessage) {
	for i := 0; i < len(goSlice); i++ {
		SmoothPath_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
