// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <nav2_msgs/action/spin.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("nav2_msgs/Spin_GetResult", Spin_GetResultTypeSupport)
	typemap.RegisterService("nav2_msgs/action/Spin_GetResult", Spin_GetResultTypeSupport)
}

type _Spin_GetResultTypeSupport struct {}

func (s _Spin_GetResultTypeSupport) Request() types.MessageTypeSupport {
	return Spin_GetResult_RequestTypeSupport
}

func (s _Spin_GetResultTypeSupport) Response() types.MessageTypeSupport {
	return Spin_GetResult_ResponseTypeSupport
}

func (s _Spin_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__nav2_msgs__action__Spin_GetResult())
}

// Modifying this variable is undefined behavior.
var Spin_GetResultTypeSupport types.ServiceTypeSupport = _Spin_GetResultTypeSupport{}

// Spin_GetResultClient wraps rclgo.Client to provide type safe helper
// functions
type Spin_GetResultClient struct {
	*rclgo.Client
}

// NewSpin_GetResultClient creates and returns a new client for the
// Spin_GetResult
func NewSpin_GetResultClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*Spin_GetResultClient, error) {
	client, err := node.NewClient(serviceName, Spin_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Spin_GetResultClient{client}, nil
}

func (s *Spin_GetResultClient) Send(ctx context.Context, req *Spin_GetResult_Request) (*Spin_GetResult_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Spin_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type Spin_GetResultServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s Spin_GetResultServiceResponseSender) SendResponse(resp *Spin_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type Spin_GetResultServiceRequestHandler func(*rclgo.ServiceInfo, *Spin_GetResult_Request, Spin_GetResultServiceResponseSender)

// Spin_GetResultService wraps rclgo.Service to provide type safe helper
// functions
type Spin_GetResultService struct {
	*rclgo.Service
}

// NewSpin_GetResultService creates and returns a new service for the
// Spin_GetResult
func NewSpin_GetResultService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler Spin_GetResultServiceRequestHandler) (*Spin_GetResultService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*Spin_GetResult_Request)
		responseSender := Spin_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, Spin_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &Spin_GetResultService{service}, nil
}