// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_action
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "dog-stream-gateway/internal/msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/action/wait.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/Wait_Goal", Wait_GoalTypeSupport)
	typemap.RegisterMessage("nav2_msgs/action/Wait_Goal", Wait_GoalTypeSupport)
}

type Wait_Goal struct {
	Time builtin_interfaces_msg.Duration `yaml:"time"`// goal definition
}

// NewWait_Goal creates a new Wait_Goal with default values.
func NewWait_Goal() *Wait_Goal {
	self := Wait_Goal{}
	self.SetDefaults()
	return &self
}

func (t *Wait_Goal) Clone() *Wait_Goal {
	c := &Wait_Goal{}
	c.Time = *t.Time.Clone()
	return c
}

func (t *Wait_Goal) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Wait_Goal) SetDefaults() {
	t.Time.SetDefaults()
}

func (t *Wait_Goal) GetTypeSupport() types.MessageTypeSupport {
	return Wait_GoalTypeSupport
}

// Wait_GoalPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Wait_GoalPublisher struct {
	*rclgo.Publisher
}

// NewWait_GoalPublisher creates and returns a new publisher for the
// Wait_Goal
func NewWait_GoalPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Wait_GoalPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Wait_GoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Wait_GoalPublisher{pub}, nil
}

func (p *Wait_GoalPublisher) Publish(msg *Wait_Goal) error {
	return p.Publisher.Publish(msg)
}

// Wait_GoalSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Wait_GoalSubscription struct {
	*rclgo.Subscription
}

// Wait_GoalSubscriptionCallback type is used to provide a subscription
// handler function for a Wait_GoalSubscription.
type Wait_GoalSubscriptionCallback func(msg *Wait_Goal, info *rclgo.MessageInfo, err error)

// NewWait_GoalSubscription creates and returns a new subscription for the
// Wait_Goal
func NewWait_GoalSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Wait_GoalSubscriptionCallback) (*Wait_GoalSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Wait_Goal
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Wait_GoalTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Wait_GoalSubscription{sub}, nil
}

func (s *Wait_GoalSubscription) TakeMessage(out *Wait_Goal) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneWait_GoalSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneWait_GoalSlice(dst, src []Wait_Goal) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Wait_GoalTypeSupport types.MessageTypeSupport = _Wait_GoalTypeSupport{}

type _Wait_GoalTypeSupport struct{}

func (t _Wait_GoalTypeSupport) New() types.Message {
	return NewWait_Goal()
}

func (t _Wait_GoalTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__action__Wait_Goal
	return (unsafe.Pointer)(C.nav2_msgs__action__Wait_Goal__create())
}

func (t _Wait_GoalTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__action__Wait_Goal__destroy((*C.nav2_msgs__action__Wait_Goal)(pointer_to_free))
}

func (t _Wait_GoalTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Wait_Goal)
	mem := (*C.nav2_msgs__action__Wait_Goal)(dst)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.time), &m.Time)
}

func (t _Wait_GoalTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Wait_Goal)
	mem := (*C.nav2_msgs__action__Wait_Goal)(ros2_message_buffer)
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.Time, unsafe.Pointer(&mem.time))
}

func (t _Wait_GoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__action__Wait_Goal())
}

type CWait_Goal = C.nav2_msgs__action__Wait_Goal
type CWait_Goal__Sequence = C.nav2_msgs__action__Wait_Goal__Sequence

func Wait_Goal__Sequence_to_Go(goSlice *[]Wait_Goal, cSlice CWait_Goal__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Wait_Goal, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Wait_GoalTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Wait_Goal__Sequence_to_C(cSlice *CWait_Goal__Sequence, goSlice []Wait_Goal) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__action__Wait_Goal)(C.malloc(C.sizeof_struct_nav2_msgs__action__Wait_Goal * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Wait_GoalTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Wait_Goal__Array_to_Go(goSlice []Wait_Goal, cSlice []CWait_Goal) {
	for i := 0; i < len(cSlice); i++ {
		Wait_GoalTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Wait_Goal__Array_to_C(cSlice []CWait_Goal, goSlice []Wait_Goal) {
	for i := 0; i < len(goSlice); i++ {
		Wait_GoalTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
