// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosapi_msgs/srv/action_result_details.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosapi_msgs/ActionResultDetails", ActionResultDetailsTypeSupport)
	typemap.RegisterService("rosapi_msgs/srv/ActionResultDetails", ActionResultDetailsTypeSupport)
}

type _ActionResultDetailsTypeSupport struct {}

func (s _ActionResultDetailsTypeSupport) Request() types.MessageTypeSupport {
	return ActionResultDetails_RequestTypeSupport
}

func (s _ActionResultDetailsTypeSupport) Response() types.MessageTypeSupport {
	return ActionResultDetails_ResponseTypeSupport
}

func (s _ActionResultDetailsTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosapi_msgs__srv__ActionResultDetails())
}

// Modifying this variable is undefined behavior.
var ActionResultDetailsTypeSupport types.ServiceTypeSupport = _ActionResultDetailsTypeSupport{}

// ActionResultDetailsClient wraps rclgo.Client to provide type safe helper
// functions
type ActionResultDetailsClient struct {
	*rclgo.Client
}

// NewActionResultDetailsClient creates and returns a new client for the
// ActionResultDetails
func NewActionResultDetailsClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ActionResultDetailsClient, error) {
	client, err := node.NewClient(serviceName, ActionResultDetailsTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ActionResultDetailsClient{client}, nil
}

func (s *ActionResultDetailsClient) Send(ctx context.Context, req *ActionResultDetails_Request) (*ActionResultDetails_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ActionResultDetails_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ActionResultDetailsServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ActionResultDetailsServiceResponseSender) SendResponse(resp *ActionResultDetails_Response) error {
	return s.sender.SendResponse(resp)
}

type ActionResultDetailsServiceRequestHandler func(*rclgo.ServiceInfo, *ActionResultDetails_Request, ActionResultDetailsServiceResponseSender)

// ActionResultDetailsService wraps rclgo.Service to provide type safe helper
// functions
type ActionResultDetailsService struct {
	*rclgo.Service
}

// NewActionResultDetailsService creates and returns a new service for the
// ActionResultDetails
func NewActionResultDetailsService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ActionResultDetailsServiceRequestHandler) (*ActionResultDetailsService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ActionResultDetails_Request)
		responseSender := ActionResultDetailsServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ActionResultDetailsTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ActionResultDetailsService{service}, nil
}