// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosapi_msgs/srv/action_type.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosapi_msgs/ActionType", ActionTypeTypeSupport)
	typemap.RegisterService("rosapi_msgs/srv/ActionType", ActionTypeTypeSupport)
}

type _ActionTypeTypeSupport struct {}

func (s _ActionTypeTypeSupport) Request() types.MessageTypeSupport {
	return ActionType_RequestTypeSupport
}

func (s _ActionTypeTypeSupport) Response() types.MessageTypeSupport {
	return ActionType_ResponseTypeSupport
}

func (s _ActionTypeTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosapi_msgs__srv__ActionType())
}

// Modifying this variable is undefined behavior.
var ActionTypeTypeSupport types.ServiceTypeSupport = _ActionTypeTypeSupport{}

// ActionTypeClient wraps rclgo.Client to provide type safe helper
// functions
type ActionTypeClient struct {
	*rclgo.Client
}

// NewActionTypeClient creates and returns a new client for the
// ActionType
func NewActionTypeClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ActionTypeClient, error) {
	client, err := node.NewClient(serviceName, ActionTypeTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ActionTypeClient{client}, nil
}

func (s *ActionTypeClient) Send(ctx context.Context, req *ActionType_Request) (*ActionType_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ActionType_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ActionTypeServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ActionTypeServiceResponseSender) SendResponse(resp *ActionType_Response) error {
	return s.sender.SendResponse(resp)
}

type ActionTypeServiceRequestHandler func(*rclgo.ServiceInfo, *ActionType_Request, ActionTypeServiceResponseSender)

// ActionTypeService wraps rclgo.Service to provide type safe helper
// functions
type ActionTypeService struct {
	*rclgo.Service
}

// NewActionTypeService creates and returns a new service for the
// ActionType
func NewActionTypeService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ActionTypeServiceRequestHandler) (*ActionTypeService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ActionType_Request)
		responseSender := ActionTypeServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ActionTypeTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ActionTypeService{service}, nil
}