// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/action_result_details.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/ActionResultDetails_Request", ActionResultDetails_RequestTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/ActionResultDetails_Request", ActionResultDetails_RequestTypeSupport)
}

type ActionResultDetails_Request struct {
	Type string `yaml:"type"`
}

// NewActionResultDetails_Request creates a new ActionResultDetails_Request with default values.
func NewActionResultDetails_Request() *ActionResultDetails_Request {
	self := ActionResultDetails_Request{}
	self.SetDefaults()
	return &self
}

func (t *ActionResultDetails_Request) Clone() *ActionResultDetails_Request {
	c := &ActionResultDetails_Request{}
	c.Type = t.Type
	return c
}

func (t *ActionResultDetails_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ActionResultDetails_Request) SetDefaults() {
	t.Type = ""
}

func (t *ActionResultDetails_Request) GetTypeSupport() types.MessageTypeSupport {
	return ActionResultDetails_RequestTypeSupport
}

// ActionResultDetails_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type ActionResultDetails_RequestPublisher struct {
	*rclgo.Publisher
}

// NewActionResultDetails_RequestPublisher creates and returns a new publisher for the
// ActionResultDetails_Request
func NewActionResultDetails_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*ActionResultDetails_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, ActionResultDetails_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ActionResultDetails_RequestPublisher{pub}, nil
}

func (p *ActionResultDetails_RequestPublisher) Publish(msg *ActionResultDetails_Request) error {
	return p.Publisher.Publish(msg)
}

// ActionResultDetails_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type ActionResultDetails_RequestSubscription struct {
	*rclgo.Subscription
}

// ActionResultDetails_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a ActionResultDetails_RequestSubscription.
type ActionResultDetails_RequestSubscriptionCallback func(msg *ActionResultDetails_Request, info *rclgo.MessageInfo, err error)

// NewActionResultDetails_RequestSubscription creates and returns a new subscription for the
// ActionResultDetails_Request
func NewActionResultDetails_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback ActionResultDetails_RequestSubscriptionCallback) (*ActionResultDetails_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg ActionResultDetails_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, ActionResultDetails_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ActionResultDetails_RequestSubscription{sub}, nil
}

func (s *ActionResultDetails_RequestSubscription) TakeMessage(out *ActionResultDetails_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneActionResultDetails_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneActionResultDetails_RequestSlice(dst, src []ActionResultDetails_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ActionResultDetails_RequestTypeSupport types.MessageTypeSupport = _ActionResultDetails_RequestTypeSupport{}

type _ActionResultDetails_RequestTypeSupport struct{}

func (t _ActionResultDetails_RequestTypeSupport) New() types.Message {
	return NewActionResultDetails_Request()
}

func (t _ActionResultDetails_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__ActionResultDetails_Request
	return (unsafe.Pointer)(C.rosapi_msgs__srv__ActionResultDetails_Request__create())
}

func (t _ActionResultDetails_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__ActionResultDetails_Request__destroy((*C.rosapi_msgs__srv__ActionResultDetails_Request)(pointer_to_free))
}

func (t _ActionResultDetails_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ActionResultDetails_Request)
	mem := (*C.rosapi_msgs__srv__ActionResultDetails_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem._type), m.Type)
}

func (t _ActionResultDetails_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ActionResultDetails_Request)
	mem := (*C.rosapi_msgs__srv__ActionResultDetails_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Type, unsafe.Pointer(&mem._type))
}

func (t _ActionResultDetails_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__ActionResultDetails_Request())
}

type CActionResultDetails_Request = C.rosapi_msgs__srv__ActionResultDetails_Request
type CActionResultDetails_Request__Sequence = C.rosapi_msgs__srv__ActionResultDetails_Request__Sequence

func ActionResultDetails_Request__Sequence_to_Go(goSlice *[]ActionResultDetails_Request, cSlice CActionResultDetails_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ActionResultDetails_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ActionResultDetails_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func ActionResultDetails_Request__Sequence_to_C(cSlice *CActionResultDetails_Request__Sequence, goSlice []ActionResultDetails_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__ActionResultDetails_Request)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__ActionResultDetails_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ActionResultDetails_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func ActionResultDetails_Request__Array_to_Go(goSlice []ActionResultDetails_Request, cSlice []CActionResultDetails_Request) {
	for i := 0; i < len(cSlice); i++ {
		ActionResultDetails_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ActionResultDetails_Request__Array_to_C(cSlice []CActionResultDetails_Request, goSlice []ActionResultDetails_Request) {
	for i := 0; i < len(goSlice); i++ {
		ActionResultDetails_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
