// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/get_param_names.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/GetParamNames_Response", GetParamNames_ResponseTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/GetParamNames_Response", GetParamNames_ResponseTypeSupport)
}

type GetParamNames_Response struct {
	Names []string `yaml:"names"`
}

// NewGetParamNames_Response creates a new GetParamNames_Response with default values.
func NewGetParamNames_Response() *GetParamNames_Response {
	self := GetParamNames_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetParamNames_Response) Clone() *GetParamNames_Response {
	c := &GetParamNames_Response{}
	if t.Names != nil {
		c.Names = make([]string, len(t.Names))
		copy(c.Names, t.Names)
	}
	return c
}

func (t *GetParamNames_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetParamNames_Response) SetDefaults() {
	t.Names = nil
}

func (t *GetParamNames_Response) GetTypeSupport() types.MessageTypeSupport {
	return GetParamNames_ResponseTypeSupport
}

// GetParamNames_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetParamNames_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGetParamNames_ResponsePublisher creates and returns a new publisher for the
// GetParamNames_Response
func NewGetParamNames_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetParamNames_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetParamNames_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetParamNames_ResponsePublisher{pub}, nil
}

func (p *GetParamNames_ResponsePublisher) Publish(msg *GetParamNames_Response) error {
	return p.Publisher.Publish(msg)
}

// GetParamNames_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetParamNames_ResponseSubscription struct {
	*rclgo.Subscription
}

// GetParamNames_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GetParamNames_ResponseSubscription.
type GetParamNames_ResponseSubscriptionCallback func(msg *GetParamNames_Response, info *rclgo.MessageInfo, err error)

// NewGetParamNames_ResponseSubscription creates and returns a new subscription for the
// GetParamNames_Response
func NewGetParamNames_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetParamNames_ResponseSubscriptionCallback) (*GetParamNames_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetParamNames_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetParamNames_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetParamNames_ResponseSubscription{sub}, nil
}

func (s *GetParamNames_ResponseSubscription) TakeMessage(out *GetParamNames_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetParamNames_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetParamNames_ResponseSlice(dst, src []GetParamNames_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetParamNames_ResponseTypeSupport types.MessageTypeSupport = _GetParamNames_ResponseTypeSupport{}

type _GetParamNames_ResponseTypeSupport struct{}

func (t _GetParamNames_ResponseTypeSupport) New() types.Message {
	return NewGetParamNames_Response()
}

func (t _GetParamNames_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__GetParamNames_Response
	return (unsafe.Pointer)(C.rosapi_msgs__srv__GetParamNames_Response__create())
}

func (t _GetParamNames_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__GetParamNames_Response__destroy((*C.rosapi_msgs__srv__GetParamNames_Response)(pointer_to_free))
}

func (t _GetParamNames_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetParamNames_Response)
	mem := (*C.rosapi_msgs__srv__GetParamNames_Response)(dst)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.names)), m.Names)
}

func (t _GetParamNames_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetParamNames_Response)
	mem := (*C.rosapi_msgs__srv__GetParamNames_Response)(ros2_message_buffer)
	primitives.String__Sequence_to_Go(&m.Names, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.names)))
}

func (t _GetParamNames_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__GetParamNames_Response())
}

type CGetParamNames_Response = C.rosapi_msgs__srv__GetParamNames_Response
type CGetParamNames_Response__Sequence = C.rosapi_msgs__srv__GetParamNames_Response__Sequence

func GetParamNames_Response__Sequence_to_Go(goSlice *[]GetParamNames_Response, cSlice CGetParamNames_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetParamNames_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetParamNames_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetParamNames_Response__Sequence_to_C(cSlice *CGetParamNames_Response__Sequence, goSlice []GetParamNames_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__GetParamNames_Response)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__GetParamNames_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetParamNames_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetParamNames_Response__Array_to_Go(goSlice []GetParamNames_Response, cSlice []CGetParamNames_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetParamNames_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetParamNames_Response__Array_to_C(cSlice []CGetParamNames_Response, goSlice []GetParamNames_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetParamNames_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
