// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosapi_msgs/srv/get_ros_version.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosapi_msgs/GetROSVersion", GetROSVersionTypeSupport)
	typemap.RegisterService("rosapi_msgs/srv/GetROSVersion", GetROSVersionTypeSupport)
}

type _GetROSVersionTypeSupport struct {}

func (s _GetROSVersionTypeSupport) Request() types.MessageTypeSupport {
	return GetROSVersion_RequestTypeSupport
}

func (s _GetROSVersionTypeSupport) Response() types.MessageTypeSupport {
	return GetROSVersion_ResponseTypeSupport
}

func (s _GetROSVersionTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosapi_msgs__srv__GetROSVersion())
}

// Modifying this variable is undefined behavior.
var GetROSVersionTypeSupport types.ServiceTypeSupport = _GetROSVersionTypeSupport{}

// GetROSVersionClient wraps rclgo.Client to provide type safe helper
// functions
type GetROSVersionClient struct {
	*rclgo.Client
}

// NewGetROSVersionClient creates and returns a new client for the
// GetROSVersion
func NewGetROSVersionClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GetROSVersionClient, error) {
	client, err := node.NewClient(serviceName, GetROSVersionTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetROSVersionClient{client}, nil
}

func (s *GetROSVersionClient) Send(ctx context.Context, req *GetROSVersion_Request) (*GetROSVersion_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetROSVersion_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetROSVersionServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GetROSVersionServiceResponseSender) SendResponse(resp *GetROSVersion_Response) error {
	return s.sender.SendResponse(resp)
}

type GetROSVersionServiceRequestHandler func(*rclgo.ServiceInfo, *GetROSVersion_Request, GetROSVersionServiceResponseSender)

// GetROSVersionService wraps rclgo.Service to provide type safe helper
// functions
type GetROSVersionService struct {
	*rclgo.Service
}

// NewGetROSVersionService creates and returns a new service for the
// GetROSVersion
func NewGetROSVersionService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GetROSVersionServiceRequestHandler) (*GetROSVersionService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GetROSVersion_Request)
		responseSender := GetROSVersionServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetROSVersionTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetROSVersionService{service}, nil
}