// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/get_time.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/GetTime_Request", GetTime_RequestTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/GetTime_Request", GetTime_RequestTypeSupport)
}

type GetTime_Request struct {
}

// NewGetTime_Request creates a new GetTime_Request with default values.
func NewGetTime_Request() *GetTime_Request {
	self := GetTime_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetTime_Request) Clone() *GetTime_Request {
	c := &GetTime_Request{}
	return c
}

func (t *GetTime_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetTime_Request) SetDefaults() {
}

func (t *GetTime_Request) GetTypeSupport() types.MessageTypeSupport {
	return GetTime_RequestTypeSupport
}

// GetTime_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetTime_RequestPublisher struct {
	*rclgo.Publisher
}

// NewGetTime_RequestPublisher creates and returns a new publisher for the
// GetTime_Request
func NewGetTime_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetTime_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetTime_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetTime_RequestPublisher{pub}, nil
}

func (p *GetTime_RequestPublisher) Publish(msg *GetTime_Request) error {
	return p.Publisher.Publish(msg)
}

// GetTime_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetTime_RequestSubscription struct {
	*rclgo.Subscription
}

// GetTime_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a GetTime_RequestSubscription.
type GetTime_RequestSubscriptionCallback func(msg *GetTime_Request, info *rclgo.MessageInfo, err error)

// NewGetTime_RequestSubscription creates and returns a new subscription for the
// GetTime_Request
func NewGetTime_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetTime_RequestSubscriptionCallback) (*GetTime_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetTime_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetTime_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetTime_RequestSubscription{sub}, nil
}

func (s *GetTime_RequestSubscription) TakeMessage(out *GetTime_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetTime_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetTime_RequestSlice(dst, src []GetTime_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetTime_RequestTypeSupport types.MessageTypeSupport = _GetTime_RequestTypeSupport{}

type _GetTime_RequestTypeSupport struct{}

func (t _GetTime_RequestTypeSupport) New() types.Message {
	return NewGetTime_Request()
}

func (t _GetTime_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__GetTime_Request
	return (unsafe.Pointer)(C.rosapi_msgs__srv__GetTime_Request__create())
}

func (t _GetTime_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__GetTime_Request__destroy((*C.rosapi_msgs__srv__GetTime_Request)(pointer_to_free))
}

func (t _GetTime_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _GetTime_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _GetTime_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__GetTime_Request())
}

type CGetTime_Request = C.rosapi_msgs__srv__GetTime_Request
type CGetTime_Request__Sequence = C.rosapi_msgs__srv__GetTime_Request__Sequence

func GetTime_Request__Sequence_to_Go(goSlice *[]GetTime_Request, cSlice CGetTime_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetTime_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetTime_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetTime_Request__Sequence_to_C(cSlice *CGetTime_Request__Sequence, goSlice []GetTime_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__GetTime_Request)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__GetTime_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetTime_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetTime_Request__Array_to_Go(goSlice []GetTime_Request, cSlice []CGetTime_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetTime_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetTime_Request__Array_to_C(cSlice []CGetTime_Request, goSlice []GetTime_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetTime_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
