// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/has_param.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/HasParam_Request", HasParam_RequestTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/HasParam_Request", HasParam_RequestTypeSupport)
}

type HasParam_Request struct {
	Name string `yaml:"name"`
}

// NewHasParam_Request creates a new HasParam_Request with default values.
func NewHasParam_Request() *HasParam_Request {
	self := HasParam_Request{}
	self.SetDefaults()
	return &self
}

func (t *HasParam_Request) Clone() *HasParam_Request {
	c := &HasParam_Request{}
	c.Name = t.Name
	return c
}

func (t *HasParam_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *HasParam_Request) SetDefaults() {
	t.Name = ""
}

func (t *HasParam_Request) GetTypeSupport() types.MessageTypeSupport {
	return HasParam_RequestTypeSupport
}

// HasParam_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type HasParam_RequestPublisher struct {
	*rclgo.Publisher
}

// NewHasParam_RequestPublisher creates and returns a new publisher for the
// HasParam_Request
func NewHasParam_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*HasParam_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, HasParam_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &HasParam_RequestPublisher{pub}, nil
}

func (p *HasParam_RequestPublisher) Publish(msg *HasParam_Request) error {
	return p.Publisher.Publish(msg)
}

// HasParam_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type HasParam_RequestSubscription struct {
	*rclgo.Subscription
}

// HasParam_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a HasParam_RequestSubscription.
type HasParam_RequestSubscriptionCallback func(msg *HasParam_Request, info *rclgo.MessageInfo, err error)

// NewHasParam_RequestSubscription creates and returns a new subscription for the
// HasParam_Request
func NewHasParam_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback HasParam_RequestSubscriptionCallback) (*HasParam_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg HasParam_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, HasParam_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &HasParam_RequestSubscription{sub}, nil
}

func (s *HasParam_RequestSubscription) TakeMessage(out *HasParam_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneHasParam_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneHasParam_RequestSlice(dst, src []HasParam_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var HasParam_RequestTypeSupport types.MessageTypeSupport = _HasParam_RequestTypeSupport{}

type _HasParam_RequestTypeSupport struct{}

func (t _HasParam_RequestTypeSupport) New() types.Message {
	return NewHasParam_Request()
}

func (t _HasParam_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__HasParam_Request
	return (unsafe.Pointer)(C.rosapi_msgs__srv__HasParam_Request__create())
}

func (t _HasParam_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__HasParam_Request__destroy((*C.rosapi_msgs__srv__HasParam_Request)(pointer_to_free))
}

func (t _HasParam_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*HasParam_Request)
	mem := (*C.rosapi_msgs__srv__HasParam_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.name), m.Name)
}

func (t _HasParam_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*HasParam_Request)
	mem := (*C.rosapi_msgs__srv__HasParam_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Name, unsafe.Pointer(&mem.name))
}

func (t _HasParam_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__HasParam_Request())
}

type CHasParam_Request = C.rosapi_msgs__srv__HasParam_Request
type CHasParam_Request__Sequence = C.rosapi_msgs__srv__HasParam_Request__Sequence

func HasParam_Request__Sequence_to_Go(goSlice *[]HasParam_Request, cSlice CHasParam_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]HasParam_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		HasParam_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func HasParam_Request__Sequence_to_C(cSlice *CHasParam_Request__Sequence, goSlice []HasParam_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__HasParam_Request)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__HasParam_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		HasParam_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func HasParam_Request__Array_to_Go(goSlice []HasParam_Request, cSlice []CHasParam_Request) {
	for i := 0; i < len(cSlice); i++ {
		HasParam_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func HasParam_Request__Array_to_C(cSlice []CHasParam_Request, goSlice []HasParam_Request) {
	for i := 0; i < len(goSlice); i++ {
		HasParam_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
