// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/interfaces.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/Interfaces_Response", Interfaces_ResponseTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/Interfaces_Response", Interfaces_ResponseTypeSupport)
}

type Interfaces_Response struct {
	Interfaces []string `yaml:"interfaces"`
}

// NewInterfaces_Response creates a new Interfaces_Response with default values.
func NewInterfaces_Response() *Interfaces_Response {
	self := Interfaces_Response{}
	self.SetDefaults()
	return &self
}

func (t *Interfaces_Response) Clone() *Interfaces_Response {
	c := &Interfaces_Response{}
	if t.Interfaces != nil {
		c.Interfaces = make([]string, len(t.Interfaces))
		copy(c.Interfaces, t.Interfaces)
	}
	return c
}

func (t *Interfaces_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Interfaces_Response) SetDefaults() {
	t.Interfaces = nil
}

func (t *Interfaces_Response) GetTypeSupport() types.MessageTypeSupport {
	return Interfaces_ResponseTypeSupport
}

// Interfaces_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Interfaces_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewInterfaces_ResponsePublisher creates and returns a new publisher for the
// Interfaces_Response
func NewInterfaces_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Interfaces_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, Interfaces_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Interfaces_ResponsePublisher{pub}, nil
}

func (p *Interfaces_ResponsePublisher) Publish(msg *Interfaces_Response) error {
	return p.Publisher.Publish(msg)
}

// Interfaces_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Interfaces_ResponseSubscription struct {
	*rclgo.Subscription
}

// Interfaces_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Interfaces_ResponseSubscription.
type Interfaces_ResponseSubscriptionCallback func(msg *Interfaces_Response, info *rclgo.MessageInfo, err error)

// NewInterfaces_ResponseSubscription creates and returns a new subscription for the
// Interfaces_Response
func NewInterfaces_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Interfaces_ResponseSubscriptionCallback) (*Interfaces_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Interfaces_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Interfaces_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Interfaces_ResponseSubscription{sub}, nil
}

func (s *Interfaces_ResponseSubscription) TakeMessage(out *Interfaces_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneInterfaces_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneInterfaces_ResponseSlice(dst, src []Interfaces_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Interfaces_ResponseTypeSupport types.MessageTypeSupport = _Interfaces_ResponseTypeSupport{}

type _Interfaces_ResponseTypeSupport struct{}

func (t _Interfaces_ResponseTypeSupport) New() types.Message {
	return NewInterfaces_Response()
}

func (t _Interfaces_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__Interfaces_Response
	return (unsafe.Pointer)(C.rosapi_msgs__srv__Interfaces_Response__create())
}

func (t _Interfaces_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__Interfaces_Response__destroy((*C.rosapi_msgs__srv__Interfaces_Response)(pointer_to_free))
}

func (t _Interfaces_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Interfaces_Response)
	mem := (*C.rosapi_msgs__srv__Interfaces_Response)(dst)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.interfaces)), m.Interfaces)
}

func (t _Interfaces_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Interfaces_Response)
	mem := (*C.rosapi_msgs__srv__Interfaces_Response)(ros2_message_buffer)
	primitives.String__Sequence_to_Go(&m.Interfaces, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.interfaces)))
}

func (t _Interfaces_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__Interfaces_Response())
}

type CInterfaces_Response = C.rosapi_msgs__srv__Interfaces_Response
type CInterfaces_Response__Sequence = C.rosapi_msgs__srv__Interfaces_Response__Sequence

func Interfaces_Response__Sequence_to_Go(goSlice *[]Interfaces_Response, cSlice CInterfaces_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Interfaces_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Interfaces_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Interfaces_Response__Sequence_to_C(cSlice *CInterfaces_Response__Sequence, goSlice []Interfaces_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__Interfaces_Response)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__Interfaces_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Interfaces_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Interfaces_Response__Array_to_Go(goSlice []Interfaces_Response, cSlice []CInterfaces_Response) {
	for i := 0; i < len(cSlice); i++ {
		Interfaces_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Interfaces_Response__Array_to_C(cSlice []CInterfaces_Response, goSlice []Interfaces_Response) {
	for i := 0; i < len(goSlice); i++ {
		Interfaces_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
