// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/nodes.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/Nodes_Response", Nodes_ResponseTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/Nodes_Response", Nodes_ResponseTypeSupport)
}

type Nodes_Response struct {
	Nodes []string `yaml:"nodes"`
}

// NewNodes_Response creates a new Nodes_Response with default values.
func NewNodes_Response() *Nodes_Response {
	self := Nodes_Response{}
	self.SetDefaults()
	return &self
}

func (t *Nodes_Response) Clone() *Nodes_Response {
	c := &Nodes_Response{}
	if t.Nodes != nil {
		c.Nodes = make([]string, len(t.Nodes))
		copy(c.Nodes, t.Nodes)
	}
	return c
}

func (t *Nodes_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Nodes_Response) SetDefaults() {
	t.Nodes = nil
}

func (t *Nodes_Response) GetTypeSupport() types.MessageTypeSupport {
	return Nodes_ResponseTypeSupport
}

// Nodes_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Nodes_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewNodes_ResponsePublisher creates and returns a new publisher for the
// Nodes_Response
func NewNodes_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Nodes_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, Nodes_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Nodes_ResponsePublisher{pub}, nil
}

func (p *Nodes_ResponsePublisher) Publish(msg *Nodes_Response) error {
	return p.Publisher.Publish(msg)
}

// Nodes_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Nodes_ResponseSubscription struct {
	*rclgo.Subscription
}

// Nodes_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Nodes_ResponseSubscription.
type Nodes_ResponseSubscriptionCallback func(msg *Nodes_Response, info *rclgo.MessageInfo, err error)

// NewNodes_ResponseSubscription creates and returns a new subscription for the
// Nodes_Response
func NewNodes_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Nodes_ResponseSubscriptionCallback) (*Nodes_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Nodes_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Nodes_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Nodes_ResponseSubscription{sub}, nil
}

func (s *Nodes_ResponseSubscription) TakeMessage(out *Nodes_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneNodes_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneNodes_ResponseSlice(dst, src []Nodes_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Nodes_ResponseTypeSupport types.MessageTypeSupport = _Nodes_ResponseTypeSupport{}

type _Nodes_ResponseTypeSupport struct{}

func (t _Nodes_ResponseTypeSupport) New() types.Message {
	return NewNodes_Response()
}

func (t _Nodes_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__Nodes_Response
	return (unsafe.Pointer)(C.rosapi_msgs__srv__Nodes_Response__create())
}

func (t _Nodes_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__Nodes_Response__destroy((*C.rosapi_msgs__srv__Nodes_Response)(pointer_to_free))
}

func (t _Nodes_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Nodes_Response)
	mem := (*C.rosapi_msgs__srv__Nodes_Response)(dst)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.nodes)), m.Nodes)
}

func (t _Nodes_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Nodes_Response)
	mem := (*C.rosapi_msgs__srv__Nodes_Response)(ros2_message_buffer)
	primitives.String__Sequence_to_Go(&m.Nodes, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.nodes)))
}

func (t _Nodes_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__Nodes_Response())
}

type CNodes_Response = C.rosapi_msgs__srv__Nodes_Response
type CNodes_Response__Sequence = C.rosapi_msgs__srv__Nodes_Response__Sequence

func Nodes_Response__Sequence_to_Go(goSlice *[]Nodes_Response, cSlice CNodes_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Nodes_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Nodes_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Nodes_Response__Sequence_to_C(cSlice *CNodes_Response__Sequence, goSlice []Nodes_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__Nodes_Response)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__Nodes_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Nodes_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Nodes_Response__Array_to_Go(goSlice []Nodes_Response, cSlice []CNodes_Response) {
	for i := 0; i < len(cSlice); i++ {
		Nodes_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Nodes_Response__Array_to_C(cSlice []CNodes_Response, goSlice []Nodes_Response) {
	for i := 0; i < len(goSlice); i++ {
		Nodes_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
