// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosapi_msgs/srv/node_details.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosapi_msgs/NodeDetails", NodeDetailsTypeSupport)
	typemap.RegisterService("rosapi_msgs/srv/NodeDetails", NodeDetailsTypeSupport)
}

type _NodeDetailsTypeSupport struct {}

func (s _NodeDetailsTypeSupport) Request() types.MessageTypeSupport {
	return NodeDetails_RequestTypeSupport
}

func (s _NodeDetailsTypeSupport) Response() types.MessageTypeSupport {
	return NodeDetails_ResponseTypeSupport
}

func (s _NodeDetailsTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosapi_msgs__srv__NodeDetails())
}

// Modifying this variable is undefined behavior.
var NodeDetailsTypeSupport types.ServiceTypeSupport = _NodeDetailsTypeSupport{}

// NodeDetailsClient wraps rclgo.Client to provide type safe helper
// functions
type NodeDetailsClient struct {
	*rclgo.Client
}

// NewNodeDetailsClient creates and returns a new client for the
// NodeDetails
func NewNodeDetailsClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*NodeDetailsClient, error) {
	client, err := node.NewClient(serviceName, NodeDetailsTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &NodeDetailsClient{client}, nil
}

func (s *NodeDetailsClient) Send(ctx context.Context, req *NodeDetails_Request) (*NodeDetails_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*NodeDetails_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type NodeDetailsServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s NodeDetailsServiceResponseSender) SendResponse(resp *NodeDetails_Response) error {
	return s.sender.SendResponse(resp)
}

type NodeDetailsServiceRequestHandler func(*rclgo.ServiceInfo, *NodeDetails_Request, NodeDetailsServiceResponseSender)

// NodeDetailsService wraps rclgo.Service to provide type safe helper
// functions
type NodeDetailsService struct {
	*rclgo.Service
}

// NewNodeDetailsService creates and returns a new service for the
// NodeDetails
func NewNodeDetailsService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler NodeDetailsServiceRequestHandler) (*NodeDetailsService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*NodeDetails_Request)
		responseSender := NodeDetailsServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, NodeDetailsTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &NodeDetailsService{service}, nil
}