// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/publishers.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/Publishers_Request", Publishers_RequestTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/Publishers_Request", Publishers_RequestTypeSupport)
}

type Publishers_Request struct {
	Topic string `yaml:"topic"`
}

// NewPublishers_Request creates a new Publishers_Request with default values.
func NewPublishers_Request() *Publishers_Request {
	self := Publishers_Request{}
	self.SetDefaults()
	return &self
}

func (t *Publishers_Request) Clone() *Publishers_Request {
	c := &Publishers_Request{}
	c.Topic = t.Topic
	return c
}

func (t *Publishers_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Publishers_Request) SetDefaults() {
	t.Topic = ""
}

func (t *Publishers_Request) GetTypeSupport() types.MessageTypeSupport {
	return Publishers_RequestTypeSupport
}

// Publishers_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Publishers_RequestPublisher struct {
	*rclgo.Publisher
}

// NewPublishers_RequestPublisher creates and returns a new publisher for the
// Publishers_Request
func NewPublishers_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Publishers_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Publishers_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Publishers_RequestPublisher{pub}, nil
}

func (p *Publishers_RequestPublisher) Publish(msg *Publishers_Request) error {
	return p.Publisher.Publish(msg)
}

// Publishers_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Publishers_RequestSubscription struct {
	*rclgo.Subscription
}

// Publishers_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a Publishers_RequestSubscription.
type Publishers_RequestSubscriptionCallback func(msg *Publishers_Request, info *rclgo.MessageInfo, err error)

// NewPublishers_RequestSubscription creates and returns a new subscription for the
// Publishers_Request
func NewPublishers_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Publishers_RequestSubscriptionCallback) (*Publishers_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Publishers_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Publishers_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Publishers_RequestSubscription{sub}, nil
}

func (s *Publishers_RequestSubscription) TakeMessage(out *Publishers_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// ClonePublishers_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePublishers_RequestSlice(dst, src []Publishers_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Publishers_RequestTypeSupport types.MessageTypeSupport = _Publishers_RequestTypeSupport{}

type _Publishers_RequestTypeSupport struct{}

func (t _Publishers_RequestTypeSupport) New() types.Message {
	return NewPublishers_Request()
}

func (t _Publishers_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__Publishers_Request
	return (unsafe.Pointer)(C.rosapi_msgs__srv__Publishers_Request__create())
}

func (t _Publishers_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__Publishers_Request__destroy((*C.rosapi_msgs__srv__Publishers_Request)(pointer_to_free))
}

func (t _Publishers_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Publishers_Request)
	mem := (*C.rosapi_msgs__srv__Publishers_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.topic), m.Topic)
}

func (t _Publishers_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Publishers_Request)
	mem := (*C.rosapi_msgs__srv__Publishers_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Topic, unsafe.Pointer(&mem.topic))
}

func (t _Publishers_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__Publishers_Request())
}

type CPublishers_Request = C.rosapi_msgs__srv__Publishers_Request
type CPublishers_Request__Sequence = C.rosapi_msgs__srv__Publishers_Request__Sequence

func Publishers_Request__Sequence_to_Go(goSlice *[]Publishers_Request, cSlice CPublishers_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Publishers_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Publishers_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Publishers_Request__Sequence_to_C(cSlice *CPublishers_Request__Sequence, goSlice []Publishers_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__Publishers_Request)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__Publishers_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Publishers_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Publishers_Request__Array_to_Go(goSlice []Publishers_Request, cSlice []CPublishers_Request) {
	for i := 0; i < len(cSlice); i++ {
		Publishers_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Publishers_Request__Array_to_C(cSlice []CPublishers_Request, goSlice []Publishers_Request) {
	for i := 0; i < len(goSlice); i++ {
		Publishers_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
