// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosapi_msgs/srv/services_for_type.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosapi_msgs/ServicesForType", ServicesForTypeTypeSupport)
	typemap.RegisterService("rosapi_msgs/srv/ServicesForType", ServicesForTypeTypeSupport)
}

type _ServicesForTypeTypeSupport struct {}

func (s _ServicesForTypeTypeSupport) Request() types.MessageTypeSupport {
	return ServicesForType_RequestTypeSupport
}

func (s _ServicesForTypeTypeSupport) Response() types.MessageTypeSupport {
	return ServicesForType_ResponseTypeSupport
}

func (s _ServicesForTypeTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosapi_msgs__srv__ServicesForType())
}

// Modifying this variable is undefined behavior.
var ServicesForTypeTypeSupport types.ServiceTypeSupport = _ServicesForTypeTypeSupport{}

// ServicesForTypeClient wraps rclgo.Client to provide type safe helper
// functions
type ServicesForTypeClient struct {
	*rclgo.Client
}

// NewServicesForTypeClient creates and returns a new client for the
// ServicesForType
func NewServicesForTypeClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ServicesForTypeClient, error) {
	client, err := node.NewClient(serviceName, ServicesForTypeTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ServicesForTypeClient{client}, nil
}

func (s *ServicesForTypeClient) Send(ctx context.Context, req *ServicesForType_Request) (*ServicesForType_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ServicesForType_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ServicesForTypeServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ServicesForTypeServiceResponseSender) SendResponse(resp *ServicesForType_Response) error {
	return s.sender.SendResponse(resp)
}

type ServicesForTypeServiceRequestHandler func(*rclgo.ServiceInfo, *ServicesForType_Request, ServicesForTypeServiceResponseSender)

// ServicesForTypeService wraps rclgo.Service to provide type safe helper
// functions
type ServicesForTypeService struct {
	*rclgo.Service
}

// NewServicesForTypeService creates and returns a new service for the
// ServicesForType
func NewServicesForTypeService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ServicesForTypeServiceRequestHandler) (*ServicesForTypeService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ServicesForType_Request)
		responseSender := ServicesForTypeServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ServicesForTypeTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ServicesForTypeService{service}, nil
}