// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosapi_msgs/srv/service_request_details.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosapi_msgs/ServiceRequestDetails", ServiceRequestDetailsTypeSupport)
	typemap.RegisterService("rosapi_msgs/srv/ServiceRequestDetails", ServiceRequestDetailsTypeSupport)
}

type _ServiceRequestDetailsTypeSupport struct {}

func (s _ServiceRequestDetailsTypeSupport) Request() types.MessageTypeSupport {
	return ServiceRequestDetails_RequestTypeSupport
}

func (s _ServiceRequestDetailsTypeSupport) Response() types.MessageTypeSupport {
	return ServiceRequestDetails_ResponseTypeSupport
}

func (s _ServiceRequestDetailsTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosapi_msgs__srv__ServiceRequestDetails())
}

// Modifying this variable is undefined behavior.
var ServiceRequestDetailsTypeSupport types.ServiceTypeSupport = _ServiceRequestDetailsTypeSupport{}

// ServiceRequestDetailsClient wraps rclgo.Client to provide type safe helper
// functions
type ServiceRequestDetailsClient struct {
	*rclgo.Client
}

// NewServiceRequestDetailsClient creates and returns a new client for the
// ServiceRequestDetails
func NewServiceRequestDetailsClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ServiceRequestDetailsClient, error) {
	client, err := node.NewClient(serviceName, ServiceRequestDetailsTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ServiceRequestDetailsClient{client}, nil
}

func (s *ServiceRequestDetailsClient) Send(ctx context.Context, req *ServiceRequestDetails_Request) (*ServiceRequestDetails_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ServiceRequestDetails_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ServiceRequestDetailsServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ServiceRequestDetailsServiceResponseSender) SendResponse(resp *ServiceRequestDetails_Response) error {
	return s.sender.SendResponse(resp)
}

type ServiceRequestDetailsServiceRequestHandler func(*rclgo.ServiceInfo, *ServiceRequestDetails_Request, ServiceRequestDetailsServiceResponseSender)

// ServiceRequestDetailsService wraps rclgo.Service to provide type safe helper
// functions
type ServiceRequestDetailsService struct {
	*rclgo.Service
}

// NewServiceRequestDetailsService creates and returns a new service for the
// ServiceRequestDetails
func NewServiceRequestDetailsService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ServiceRequestDetailsServiceRequestHandler) (*ServiceRequestDetailsService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ServiceRequestDetails_Request)
		responseSender := ServiceRequestDetailsServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ServiceRequestDetailsTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ServiceRequestDetailsService{service}, nil
}