// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosapi_msgs/srv/service_type.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("rosapi_msgs/ServiceType", ServiceTypeTypeSupport)
	typemap.RegisterService("rosapi_msgs/srv/ServiceType", ServiceTypeTypeSupport)
}

type _ServiceTypeTypeSupport struct {}

func (s _ServiceTypeTypeSupport) Request() types.MessageTypeSupport {
	return ServiceType_RequestTypeSupport
}

func (s _ServiceTypeTypeSupport) Response() types.MessageTypeSupport {
	return ServiceType_ResponseTypeSupport
}

func (s _ServiceTypeTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosapi_msgs__srv__ServiceType())
}

// Modifying this variable is undefined behavior.
var ServiceTypeTypeSupport types.ServiceTypeSupport = _ServiceTypeTypeSupport{}

// ServiceTypeClient wraps rclgo.Client to provide type safe helper
// functions
type ServiceTypeClient struct {
	*rclgo.Client
}

// NewServiceTypeClient creates and returns a new client for the
// ServiceType
func NewServiceTypeClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ServiceTypeClient, error) {
	client, err := node.NewClient(serviceName, ServiceTypeTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ServiceTypeClient{client}, nil
}

func (s *ServiceTypeClient) Send(ctx context.Context, req *ServiceType_Request) (*ServiceType_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ServiceType_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ServiceTypeServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ServiceTypeServiceResponseSender) SendResponse(resp *ServiceType_Response) error {
	return s.sender.SendResponse(resp)
}

type ServiceTypeServiceRequestHandler func(*rclgo.ServiceInfo, *ServiceType_Request, ServiceTypeServiceResponseSender)

// ServiceTypeService wraps rclgo.Service to provide type safe helper
// functions
type ServiceTypeService struct {
	*rclgo.Service
}

// NewServiceTypeService creates and returns a new service for the
// ServiceType
func NewServiceTypeService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ServiceTypeServiceRequestHandler) (*ServiceTypeService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ServiceType_Request)
		responseSender := ServiceTypeServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ServiceTypeTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ServiceTypeService{service}, nil
}