// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/set_param.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/SetParam_Response", SetParam_ResponseTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/SetParam_Response", SetParam_ResponseTypeSupport)
}

type SetParam_Response struct {
}

// NewSetParam_Response creates a new SetParam_Response with default values.
func NewSetParam_Response() *SetParam_Response {
	self := SetParam_Response{}
	self.SetDefaults()
	return &self
}

func (t *SetParam_Response) Clone() *SetParam_Response {
	c := &SetParam_Response{}
	return c
}

func (t *SetParam_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetParam_Response) SetDefaults() {
}

func (t *SetParam_Response) GetTypeSupport() types.MessageTypeSupport {
	return SetParam_ResponseTypeSupport
}

// SetParam_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetParam_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewSetParam_ResponsePublisher creates and returns a new publisher for the
// SetParam_Response
func NewSetParam_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetParam_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetParam_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetParam_ResponsePublisher{pub}, nil
}

func (p *SetParam_ResponsePublisher) Publish(msg *SetParam_Response) error {
	return p.Publisher.Publish(msg)
}

// SetParam_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetParam_ResponseSubscription struct {
	*rclgo.Subscription
}

// SetParam_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SetParam_ResponseSubscription.
type SetParam_ResponseSubscriptionCallback func(msg *SetParam_Response, info *rclgo.MessageInfo, err error)

// NewSetParam_ResponseSubscription creates and returns a new subscription for the
// SetParam_Response
func NewSetParam_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetParam_ResponseSubscriptionCallback) (*SetParam_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetParam_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetParam_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetParam_ResponseSubscription{sub}, nil
}

func (s *SetParam_ResponseSubscription) TakeMessage(out *SetParam_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetParam_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetParam_ResponseSlice(dst, src []SetParam_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetParam_ResponseTypeSupport types.MessageTypeSupport = _SetParam_ResponseTypeSupport{}

type _SetParam_ResponseTypeSupport struct{}

func (t _SetParam_ResponseTypeSupport) New() types.Message {
	return NewSetParam_Response()
}

func (t _SetParam_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__SetParam_Response
	return (unsafe.Pointer)(C.rosapi_msgs__srv__SetParam_Response__create())
}

func (t _SetParam_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__SetParam_Response__destroy((*C.rosapi_msgs__srv__SetParam_Response)(pointer_to_free))
}

func (t _SetParam_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _SetParam_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _SetParam_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__SetParam_Response())
}

type CSetParam_Response = C.rosapi_msgs__srv__SetParam_Response
type CSetParam_Response__Sequence = C.rosapi_msgs__srv__SetParam_Response__Sequence

func SetParam_Response__Sequence_to_Go(goSlice *[]SetParam_Response, cSlice CSetParam_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetParam_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetParam_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetParam_Response__Sequence_to_C(cSlice *CSetParam_Response__Sequence, goSlice []SetParam_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__SetParam_Response)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__SetParam_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetParam_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetParam_Response__Array_to_Go(goSlice []SetParam_Response, cSlice []CSetParam_Response) {
	for i := 0; i < len(cSlice); i++ {
		SetParam_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetParam_Response__Array_to_C(cSlice []CSetParam_Response, goSlice []SetParam_Response) {
	for i := 0; i < len(goSlice); i++ {
		SetParam_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
