// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/set_param.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/SetParam_Request", SetParam_RequestTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/SetParam_Request", SetParam_RequestTypeSupport)
}

type SetParam_Request struct {
	Name string `yaml:"name"`
	Value string `yaml:"value"`
}

// NewSetParam_Request creates a new SetParam_Request with default values.
func NewSetParam_Request() *SetParam_Request {
	self := SetParam_Request{}
	self.SetDefaults()
	return &self
}

func (t *SetParam_Request) Clone() *SetParam_Request {
	c := &SetParam_Request{}
	c.Name = t.Name
	c.Value = t.Value
	return c
}

func (t *SetParam_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetParam_Request) SetDefaults() {
	t.Name = ""
	t.Value = ""
}

func (t *SetParam_Request) GetTypeSupport() types.MessageTypeSupport {
	return SetParam_RequestTypeSupport
}

// SetParam_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SetParam_RequestPublisher struct {
	*rclgo.Publisher
}

// NewSetParam_RequestPublisher creates and returns a new publisher for the
// SetParam_Request
func NewSetParam_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SetParam_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SetParam_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetParam_RequestPublisher{pub}, nil
}

func (p *SetParam_RequestPublisher) Publish(msg *SetParam_Request) error {
	return p.Publisher.Publish(msg)
}

// SetParam_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SetParam_RequestSubscription struct {
	*rclgo.Subscription
}

// SetParam_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a SetParam_RequestSubscription.
type SetParam_RequestSubscriptionCallback func(msg *SetParam_Request, info *rclgo.MessageInfo, err error)

// NewSetParam_RequestSubscription creates and returns a new subscription for the
// SetParam_Request
func NewSetParam_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SetParam_RequestSubscriptionCallback) (*SetParam_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SetParam_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SetParam_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetParam_RequestSubscription{sub}, nil
}

func (s *SetParam_RequestSubscription) TakeMessage(out *SetParam_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetParam_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetParam_RequestSlice(dst, src []SetParam_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetParam_RequestTypeSupport types.MessageTypeSupport = _SetParam_RequestTypeSupport{}

type _SetParam_RequestTypeSupport struct{}

func (t _SetParam_RequestTypeSupport) New() types.Message {
	return NewSetParam_Request()
}

func (t _SetParam_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__SetParam_Request
	return (unsafe.Pointer)(C.rosapi_msgs__srv__SetParam_Request__create())
}

func (t _SetParam_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__SetParam_Request__destroy((*C.rosapi_msgs__srv__SetParam_Request)(pointer_to_free))
}

func (t _SetParam_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetParam_Request)
	mem := (*C.rosapi_msgs__srv__SetParam_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.name), m.Name)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.value), m.Value)
}

func (t _SetParam_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetParam_Request)
	mem := (*C.rosapi_msgs__srv__SetParam_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Name, unsafe.Pointer(&mem.name))
	primitives.StringAsGoStruct(&m.Value, unsafe.Pointer(&mem.value))
}

func (t _SetParam_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__SetParam_Request())
}

type CSetParam_Request = C.rosapi_msgs__srv__SetParam_Request
type CSetParam_Request__Sequence = C.rosapi_msgs__srv__SetParam_Request__Sequence

func SetParam_Request__Sequence_to_Go(goSlice *[]SetParam_Request, cSlice CSetParam_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetParam_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetParam_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SetParam_Request__Sequence_to_C(cSlice *CSetParam_Request__Sequence, goSlice []SetParam_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__SetParam_Request)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__SetParam_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetParam_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SetParam_Request__Array_to_Go(goSlice []SetParam_Request, cSlice []CSetParam_Request) {
	for i := 0; i < len(cSlice); i++ {
		SetParam_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetParam_Request__Array_to_C(cSlice []CSetParam_Request, goSlice []SetParam_Request) {
	for i := 0; i < len(goSlice); i++ {
		SetParam_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
