// Code generated by rclgo-gen. DO NOT EDIT.

package rosapi_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosapi_msgs/srv/topics_for_type.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosapi_msgs/TopicsForType_Request", TopicsForType_RequestTypeSupport)
	typemap.RegisterMessage("rosapi_msgs/srv/TopicsForType_Request", TopicsForType_RequestTypeSupport)
}

type TopicsForType_Request struct {
	Type string `yaml:"type"`
}

// NewTopicsForType_Request creates a new TopicsForType_Request with default values.
func NewTopicsForType_Request() *TopicsForType_Request {
	self := TopicsForType_Request{}
	self.SetDefaults()
	return &self
}

func (t *TopicsForType_Request) Clone() *TopicsForType_Request {
	c := &TopicsForType_Request{}
	c.Type = t.Type
	return c
}

func (t *TopicsForType_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *TopicsForType_Request) SetDefaults() {
	t.Type = ""
}

func (t *TopicsForType_Request) GetTypeSupport() types.MessageTypeSupport {
	return TopicsForType_RequestTypeSupport
}

// TopicsForType_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type TopicsForType_RequestPublisher struct {
	*rclgo.Publisher
}

// NewTopicsForType_RequestPublisher creates and returns a new publisher for the
// TopicsForType_Request
func NewTopicsForType_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*TopicsForType_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, TopicsForType_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &TopicsForType_RequestPublisher{pub}, nil
}

func (p *TopicsForType_RequestPublisher) Publish(msg *TopicsForType_Request) error {
	return p.Publisher.Publish(msg)
}

// TopicsForType_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type TopicsForType_RequestSubscription struct {
	*rclgo.Subscription
}

// TopicsForType_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a TopicsForType_RequestSubscription.
type TopicsForType_RequestSubscriptionCallback func(msg *TopicsForType_Request, info *rclgo.MessageInfo, err error)

// NewTopicsForType_RequestSubscription creates and returns a new subscription for the
// TopicsForType_Request
func NewTopicsForType_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback TopicsForType_RequestSubscriptionCallback) (*TopicsForType_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg TopicsForType_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, TopicsForType_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &TopicsForType_RequestSubscription{sub}, nil
}

func (s *TopicsForType_RequestSubscription) TakeMessage(out *TopicsForType_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneTopicsForType_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneTopicsForType_RequestSlice(dst, src []TopicsForType_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var TopicsForType_RequestTypeSupport types.MessageTypeSupport = _TopicsForType_RequestTypeSupport{}

type _TopicsForType_RequestTypeSupport struct{}

func (t _TopicsForType_RequestTypeSupport) New() types.Message {
	return NewTopicsForType_Request()
}

func (t _TopicsForType_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosapi_msgs__srv__TopicsForType_Request
	return (unsafe.Pointer)(C.rosapi_msgs__srv__TopicsForType_Request__create())
}

func (t _TopicsForType_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosapi_msgs__srv__TopicsForType_Request__destroy((*C.rosapi_msgs__srv__TopicsForType_Request)(pointer_to_free))
}

func (t _TopicsForType_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*TopicsForType_Request)
	mem := (*C.rosapi_msgs__srv__TopicsForType_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem._type), m.Type)
}

func (t _TopicsForType_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*TopicsForType_Request)
	mem := (*C.rosapi_msgs__srv__TopicsForType_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Type, unsafe.Pointer(&mem._type))
}

func (t _TopicsForType_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosapi_msgs__srv__TopicsForType_Request())
}

type CTopicsForType_Request = C.rosapi_msgs__srv__TopicsForType_Request
type CTopicsForType_Request__Sequence = C.rosapi_msgs__srv__TopicsForType_Request__Sequence

func TopicsForType_Request__Sequence_to_Go(goSlice *[]TopicsForType_Request, cSlice CTopicsForType_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]TopicsForType_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		TopicsForType_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func TopicsForType_Request__Sequence_to_C(cSlice *CTopicsForType_Request__Sequence, goSlice []TopicsForType_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rosapi_msgs__srv__TopicsForType_Request)(C.malloc(C.sizeof_struct_rosapi_msgs__srv__TopicsForType_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		TopicsForType_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func TopicsForType_Request__Array_to_Go(goSlice []TopicsForType_Request, cSlice []CTopicsForType_Request) {
	for i := 0; i < len(cSlice); i++ {
		TopicsForType_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func TopicsForType_Request__Array_to_C(cSlice []CTopicsForType_Request, goSlice []TopicsForType_Request) {
	for i := 0; i < len(goSlice); i++ {
		TopicsForType_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
