// Code generated by rclgo-gen. DO NOT EDIT.

package aruco_opencv_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geometry_msgs_msg "dog-stream-gateway/internal/msgs/geometry_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <aruco_opencv_msgs/msg/board_pose.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("aruco_opencv_msgs/BoardPose", BoardPoseTypeSupport)
	typemap.RegisterMessage("aruco_opencv_msgs/msg/BoardPose", BoardPoseTypeSupport)
}

type BoardPose struct {
	BoardName string `yaml:"board_name"`
	Pose geometry_msgs_msg.Pose `yaml:"pose"`
}

// NewBoardPose creates a new BoardPose with default values.
func NewBoardPose() *BoardPose {
	self := BoardPose{}
	self.SetDefaults()
	return &self
}

func (t *BoardPose) Clone() *BoardPose {
	c := &BoardPose{}
	c.BoardName = t.BoardName
	c.Pose = *t.Pose.Clone()
	return c
}

func (t *BoardPose) CloneMsg() types.Message {
	return t.Clone()
}

func (t *BoardPose) SetDefaults() {
	t.BoardName = ""
	t.Pose.SetDefaults()
}

func (t *BoardPose) GetTypeSupport() types.MessageTypeSupport {
	return BoardPoseTypeSupport
}

// BoardPosePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type BoardPosePublisher struct {
	*rclgo.Publisher
}

// NewBoardPosePublisher creates and returns a new publisher for the
// BoardPose
func NewBoardPosePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*BoardPosePublisher, error) {
	pub, err := node.NewPublisher(topic_name, BoardPoseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &BoardPosePublisher{pub}, nil
}

func (p *BoardPosePublisher) Publish(msg *BoardPose) error {
	return p.Publisher.Publish(msg)
}

// BoardPoseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type BoardPoseSubscription struct {
	*rclgo.Subscription
}

// BoardPoseSubscriptionCallback type is used to provide a subscription
// handler function for a BoardPoseSubscription.
type BoardPoseSubscriptionCallback func(msg *BoardPose, info *rclgo.MessageInfo, err error)

// NewBoardPoseSubscription creates and returns a new subscription for the
// BoardPose
func NewBoardPoseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback BoardPoseSubscriptionCallback) (*BoardPoseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg BoardPose
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, BoardPoseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &BoardPoseSubscription{sub}, nil
}

func (s *BoardPoseSubscription) TakeMessage(out *BoardPose) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneBoardPoseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneBoardPoseSlice(dst, src []BoardPose) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var BoardPoseTypeSupport types.MessageTypeSupport = _BoardPoseTypeSupport{}

type _BoardPoseTypeSupport struct{}

func (t _BoardPoseTypeSupport) New() types.Message {
	return NewBoardPose()
}

func (t _BoardPoseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.aruco_opencv_msgs__msg__BoardPose
	return (unsafe.Pointer)(C.aruco_opencv_msgs__msg__BoardPose__create())
}

func (t _BoardPoseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.aruco_opencv_msgs__msg__BoardPose__destroy((*C.aruco_opencv_msgs__msg__BoardPose)(pointer_to_free))
}

func (t _BoardPoseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*BoardPose)
	mem := (*C.aruco_opencv_msgs__msg__BoardPose)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.board_name), m.BoardName)
	geometry_msgs_msg.PoseTypeSupport.AsCStruct(unsafe.Pointer(&mem.pose), &m.Pose)
}

func (t _BoardPoseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*BoardPose)
	mem := (*C.aruco_opencv_msgs__msg__BoardPose)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.BoardName, unsafe.Pointer(&mem.board_name))
	geometry_msgs_msg.PoseTypeSupport.AsGoStruct(&m.Pose, unsafe.Pointer(&mem.pose))
}

func (t _BoardPoseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__aruco_opencv_msgs__msg__BoardPose())
}

type CBoardPose = C.aruco_opencv_msgs__msg__BoardPose
type CBoardPose__Sequence = C.aruco_opencv_msgs__msg__BoardPose__Sequence

func BoardPose__Sequence_to_Go(goSlice *[]BoardPose, cSlice CBoardPose__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]BoardPose, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		BoardPoseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func BoardPose__Sequence_to_C(cSlice *CBoardPose__Sequence, goSlice []BoardPose) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.aruco_opencv_msgs__msg__BoardPose)(C.malloc(C.sizeof_struct_aruco_opencv_msgs__msg__BoardPose * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		BoardPoseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func BoardPose__Array_to_Go(goSlice []BoardPose, cSlice []CBoardPose) {
	for i := 0; i < len(cSlice); i++ {
		BoardPoseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func BoardPose__Array_to_C(cSlice []CBoardPose, goSlice []BoardPose) {
	for i := 0; i < len(goSlice); i++ {
		BoardPoseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
