// Code generated by rclgo-gen. DO NOT EDIT.

package aruco_opencv_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geometry_msgs_msg "dog-stream-gateway/internal/msgs/geometry_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <aruco_opencv_msgs/msg/marker_pose.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("aruco_opencv_msgs/MarkerPose", MarkerPoseTypeSupport)
	typemap.RegisterMessage("aruco_opencv_msgs/msg/MarkerPose", MarkerPoseTypeSupport)
}

type MarkerPose struct {
	MarkerId uint16 `yaml:"marker_id"`
	Pose geometry_msgs_msg.Pose `yaml:"pose"`
}

// NewMarkerPose creates a new MarkerPose with default values.
func NewMarkerPose() *MarkerPose {
	self := MarkerPose{}
	self.SetDefaults()
	return &self
}

func (t *MarkerPose) Clone() *MarkerPose {
	c := &MarkerPose{}
	c.MarkerId = t.MarkerId
	c.Pose = *t.Pose.Clone()
	return c
}

func (t *MarkerPose) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MarkerPose) SetDefaults() {
	t.MarkerId = 0
	t.Pose.SetDefaults()
}

func (t *MarkerPose) GetTypeSupport() types.MessageTypeSupport {
	return MarkerPoseTypeSupport
}

// MarkerPosePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MarkerPosePublisher struct {
	*rclgo.Publisher
}

// NewMarkerPosePublisher creates and returns a new publisher for the
// MarkerPose
func NewMarkerPosePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MarkerPosePublisher, error) {
	pub, err := node.NewPublisher(topic_name, MarkerPoseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MarkerPosePublisher{pub}, nil
}

func (p *MarkerPosePublisher) Publish(msg *MarkerPose) error {
	return p.Publisher.Publish(msg)
}

// MarkerPoseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MarkerPoseSubscription struct {
	*rclgo.Subscription
}

// MarkerPoseSubscriptionCallback type is used to provide a subscription
// handler function for a MarkerPoseSubscription.
type MarkerPoseSubscriptionCallback func(msg *MarkerPose, info *rclgo.MessageInfo, err error)

// NewMarkerPoseSubscription creates and returns a new subscription for the
// MarkerPose
func NewMarkerPoseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MarkerPoseSubscriptionCallback) (*MarkerPoseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MarkerPose
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MarkerPoseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MarkerPoseSubscription{sub}, nil
}

func (s *MarkerPoseSubscription) TakeMessage(out *MarkerPose) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMarkerPoseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMarkerPoseSlice(dst, src []MarkerPose) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MarkerPoseTypeSupport types.MessageTypeSupport = _MarkerPoseTypeSupport{}

type _MarkerPoseTypeSupport struct{}

func (t _MarkerPoseTypeSupport) New() types.Message {
	return NewMarkerPose()
}

func (t _MarkerPoseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.aruco_opencv_msgs__msg__MarkerPose
	return (unsafe.Pointer)(C.aruco_opencv_msgs__msg__MarkerPose__create())
}

func (t _MarkerPoseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.aruco_opencv_msgs__msg__MarkerPose__destroy((*C.aruco_opencv_msgs__msg__MarkerPose)(pointer_to_free))
}

func (t _MarkerPoseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MarkerPose)
	mem := (*C.aruco_opencv_msgs__msg__MarkerPose)(dst)
	mem.marker_id = C.uint16_t(m.MarkerId)
	geometry_msgs_msg.PoseTypeSupport.AsCStruct(unsafe.Pointer(&mem.pose), &m.Pose)
}

func (t _MarkerPoseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MarkerPose)
	mem := (*C.aruco_opencv_msgs__msg__MarkerPose)(ros2_message_buffer)
	m.MarkerId = uint16(mem.marker_id)
	geometry_msgs_msg.PoseTypeSupport.AsGoStruct(&m.Pose, unsafe.Pointer(&mem.pose))
}

func (t _MarkerPoseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__aruco_opencv_msgs__msg__MarkerPose())
}

type CMarkerPose = C.aruco_opencv_msgs__msg__MarkerPose
type CMarkerPose__Sequence = C.aruco_opencv_msgs__msg__MarkerPose__Sequence

func MarkerPose__Sequence_to_Go(goSlice *[]MarkerPose, cSlice CMarkerPose__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MarkerPose, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MarkerPoseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MarkerPose__Sequence_to_C(cSlice *CMarkerPose__Sequence, goSlice []MarkerPose) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.aruco_opencv_msgs__msg__MarkerPose)(C.malloc(C.sizeof_struct_aruco_opencv_msgs__msg__MarkerPose * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MarkerPoseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MarkerPose__Array_to_Go(goSlice []MarkerPose, cSlice []CMarkerPose) {
	for i := 0; i < len(cSlice); i++ {
		MarkerPoseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MarkerPose__Array_to_C(cSlice []CMarkerPose, goSlice []MarkerPose) {
	for i := 0; i < len(goSlice); i++ {
		MarkerPoseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
