// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "dog-stream-gateway/internal/msgs/std_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/msg/env_sensor.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/EnvSensor", EnvSensorTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/msg/EnvSensor", EnvSensorTypeSupport)
}

type EnvSensor struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Type int32 `yaml:"type"`// EnvSensor
	Value float64 `yaml:"value"`
}

// NewEnvSensor creates a new EnvSensor with default values.
func NewEnvSensor() *EnvSensor {
	self := EnvSensor{}
	self.SetDefaults()
	return &self
}

func (t *EnvSensor) Clone() *EnvSensor {
	c := &EnvSensor{}
	c.Header = *t.Header.Clone()
	c.Type = t.Type
	c.Value = t.Value
	return c
}

func (t *EnvSensor) CloneMsg() types.Message {
	return t.Clone()
}

func (t *EnvSensor) SetDefaults() {
	t.Header.SetDefaults()
	t.Type = 0
	t.Value = 0
}

func (t *EnvSensor) GetTypeSupport() types.MessageTypeSupport {
	return EnvSensorTypeSupport
}

// EnvSensorPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type EnvSensorPublisher struct {
	*rclgo.Publisher
}

// NewEnvSensorPublisher creates and returns a new publisher for the
// EnvSensor
func NewEnvSensorPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*EnvSensorPublisher, error) {
	pub, err := node.NewPublisher(topic_name, EnvSensorTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &EnvSensorPublisher{pub}, nil
}

func (p *EnvSensorPublisher) Publish(msg *EnvSensor) error {
	return p.Publisher.Publish(msg)
}

// EnvSensorSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type EnvSensorSubscription struct {
	*rclgo.Subscription
}

// EnvSensorSubscriptionCallback type is used to provide a subscription
// handler function for a EnvSensorSubscription.
type EnvSensorSubscriptionCallback func(msg *EnvSensor, info *rclgo.MessageInfo, err error)

// NewEnvSensorSubscription creates and returns a new subscription for the
// EnvSensor
func NewEnvSensorSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback EnvSensorSubscriptionCallback) (*EnvSensorSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg EnvSensor
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, EnvSensorTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &EnvSensorSubscription{sub}, nil
}

func (s *EnvSensorSubscription) TakeMessage(out *EnvSensor) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneEnvSensorSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneEnvSensorSlice(dst, src []EnvSensor) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var EnvSensorTypeSupport types.MessageTypeSupport = _EnvSensorTypeSupport{}

type _EnvSensorTypeSupport struct{}

func (t _EnvSensorTypeSupport) New() types.Message {
	return NewEnvSensor()
}

func (t _EnvSensorTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__msg__EnvSensor
	return (unsafe.Pointer)(C.rtabmap_msgs__msg__EnvSensor__create())
}

func (t _EnvSensorTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__msg__EnvSensor__destroy((*C.rtabmap_msgs__msg__EnvSensor)(pointer_to_free))
}

func (t _EnvSensorTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*EnvSensor)
	mem := (*C.rtabmap_msgs__msg__EnvSensor)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	mem._type = C.int32_t(m.Type)
	mem.value = C.double(m.Value)
}

func (t _EnvSensorTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*EnvSensor)
	mem := (*C.rtabmap_msgs__msg__EnvSensor)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	m.Type = int32(mem._type)
	m.Value = float64(mem.value)
}

func (t _EnvSensorTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__msg__EnvSensor())
}

type CEnvSensor = C.rtabmap_msgs__msg__EnvSensor
type CEnvSensor__Sequence = C.rtabmap_msgs__msg__EnvSensor__Sequence

func EnvSensor__Sequence_to_Go(goSlice *[]EnvSensor, cSlice CEnvSensor__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]EnvSensor, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		EnvSensorTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func EnvSensor__Sequence_to_C(cSlice *CEnvSensor__Sequence, goSlice []EnvSensor) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__msg__EnvSensor)(C.malloc(C.sizeof_struct_rtabmap_msgs__msg__EnvSensor * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		EnvSensorTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func EnvSensor__Array_to_Go(goSlice []EnvSensor, cSlice []CEnvSensor) {
	for i := 0; i < len(cSlice); i++ {
		EnvSensorTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func EnvSensor__Array_to_C(cSlice []CEnvSensor, goSlice []EnvSensor) {
	for i := 0; i < len(goSlice); i++ {
		EnvSensorTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
