// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "dog-stream-gateway/internal/msgs/std_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/msg/goal.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/Goal", GoalTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/msg/Goal", GoalTypeSupport)
}

type Goal struct {
	Header std_msgs_msg.Header `yaml:"header"`
	NodeId int32 `yaml:"node_id"`// Set either node_id or node_label
	NodeLabel string `yaml:"node_label"`
	FrameId string `yaml:"frame_id"`// optional: if not set, the base frame of the robot is used
}

// NewGoal creates a new Goal with default values.
func NewGoal() *Goal {
	self := Goal{}
	self.SetDefaults()
	return &self
}

func (t *Goal) Clone() *Goal {
	c := &Goal{}
	c.Header = *t.Header.Clone()
	c.NodeId = t.NodeId
	c.NodeLabel = t.NodeLabel
	c.FrameId = t.FrameId
	return c
}

func (t *Goal) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Goal) SetDefaults() {
	t.Header.SetDefaults()
	t.NodeId = 0
	t.NodeLabel = ""
	t.FrameId = ""
}

func (t *Goal) GetTypeSupport() types.MessageTypeSupport {
	return GoalTypeSupport
}

// GoalPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GoalPublisher struct {
	*rclgo.Publisher
}

// NewGoalPublisher creates and returns a new publisher for the
// Goal
func NewGoalPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GoalPublisher, error) {
	pub, err := node.NewPublisher(topic_name, GoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GoalPublisher{pub}, nil
}

func (p *GoalPublisher) Publish(msg *Goal) error {
	return p.Publisher.Publish(msg)
}

// GoalSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GoalSubscription struct {
	*rclgo.Subscription
}

// GoalSubscriptionCallback type is used to provide a subscription
// handler function for a GoalSubscription.
type GoalSubscriptionCallback func(msg *Goal, info *rclgo.MessageInfo, err error)

// NewGoalSubscription creates and returns a new subscription for the
// Goal
func NewGoalSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GoalSubscriptionCallback) (*GoalSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Goal
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GoalTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GoalSubscription{sub}, nil
}

func (s *GoalSubscription) TakeMessage(out *Goal) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGoalSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGoalSlice(dst, src []Goal) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GoalTypeSupport types.MessageTypeSupport = _GoalTypeSupport{}

type _GoalTypeSupport struct{}

func (t _GoalTypeSupport) New() types.Message {
	return NewGoal()
}

func (t _GoalTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__msg__Goal
	return (unsafe.Pointer)(C.rtabmap_msgs__msg__Goal__create())
}

func (t _GoalTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__msg__Goal__destroy((*C.rtabmap_msgs__msg__Goal)(pointer_to_free))
}

func (t _GoalTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Goal)
	mem := (*C.rtabmap_msgs__msg__Goal)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	mem.node_id = C.int32_t(m.NodeId)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.node_label), m.NodeLabel)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.frame_id), m.FrameId)
}

func (t _GoalTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Goal)
	mem := (*C.rtabmap_msgs__msg__Goal)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	m.NodeId = int32(mem.node_id)
	primitives.StringAsGoStruct(&m.NodeLabel, unsafe.Pointer(&mem.node_label))
	primitives.StringAsGoStruct(&m.FrameId, unsafe.Pointer(&mem.frame_id))
}

func (t _GoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__msg__Goal())
}

type CGoal = C.rtabmap_msgs__msg__Goal
type CGoal__Sequence = C.rtabmap_msgs__msg__Goal__Sequence

func Goal__Sequence_to_Go(goSlice *[]Goal, cSlice CGoal__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Goal, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GoalTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Goal__Sequence_to_C(cSlice *CGoal__Sequence, goSlice []Goal) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__msg__Goal)(C.malloc(C.sizeof_struct_rtabmap_msgs__msg__Goal * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GoalTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Goal__Array_to_Go(goSlice []Goal, cSlice []CGoal) {
	for i := 0; i < len(cSlice); i++ {
		GoalTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Goal__Array_to_C(cSlice []CGoal, goSlice []Goal) {
	for i := 0; i < len(goSlice); i++ {
		GoalTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
