// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "dog-stream-gateway/internal/msgs/std_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/msg/map_data.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/MapData", MapDataTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/msg/MapData", MapDataTypeSupport)
}

type MapData struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Graph MapGraph `yaml:"graph"`// #################Optimized graph#################
	Nodes []Node `yaml:"nodes"`// #################Graph data#################
}

// NewMapData creates a new MapData with default values.
func NewMapData() *MapData {
	self := MapData{}
	self.SetDefaults()
	return &self
}

func (t *MapData) Clone() *MapData {
	c := &MapData{}
	c.Header = *t.Header.Clone()
	c.Graph = *t.Graph.Clone()
	if t.Nodes != nil {
		c.Nodes = make([]Node, len(t.Nodes))
		CloneNodeSlice(c.Nodes, t.Nodes)
	}
	return c
}

func (t *MapData) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MapData) SetDefaults() {
	t.Header.SetDefaults()
	t.Graph.SetDefaults()
	t.Nodes = nil
}

func (t *MapData) GetTypeSupport() types.MessageTypeSupport {
	return MapDataTypeSupport
}

// MapDataPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MapDataPublisher struct {
	*rclgo.Publisher
}

// NewMapDataPublisher creates and returns a new publisher for the
// MapData
func NewMapDataPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MapDataPublisher, error) {
	pub, err := node.NewPublisher(topic_name, MapDataTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MapDataPublisher{pub}, nil
}

func (p *MapDataPublisher) Publish(msg *MapData) error {
	return p.Publisher.Publish(msg)
}

// MapDataSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MapDataSubscription struct {
	*rclgo.Subscription
}

// MapDataSubscriptionCallback type is used to provide a subscription
// handler function for a MapDataSubscription.
type MapDataSubscriptionCallback func(msg *MapData, info *rclgo.MessageInfo, err error)

// NewMapDataSubscription creates and returns a new subscription for the
// MapData
func NewMapDataSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MapDataSubscriptionCallback) (*MapDataSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MapData
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MapDataTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MapDataSubscription{sub}, nil
}

func (s *MapDataSubscription) TakeMessage(out *MapData) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMapDataSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMapDataSlice(dst, src []MapData) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MapDataTypeSupport types.MessageTypeSupport = _MapDataTypeSupport{}

type _MapDataTypeSupport struct{}

func (t _MapDataTypeSupport) New() types.Message {
	return NewMapData()
}

func (t _MapDataTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__msg__MapData
	return (unsafe.Pointer)(C.rtabmap_msgs__msg__MapData__create())
}

func (t _MapDataTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__msg__MapData__destroy((*C.rtabmap_msgs__msg__MapData)(pointer_to_free))
}

func (t _MapDataTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MapData)
	mem := (*C.rtabmap_msgs__msg__MapData)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	MapGraphTypeSupport.AsCStruct(unsafe.Pointer(&mem.graph), &m.Graph)
	Node__Sequence_to_C(&mem.nodes, m.Nodes)
}

func (t _MapDataTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MapData)
	mem := (*C.rtabmap_msgs__msg__MapData)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	MapGraphTypeSupport.AsGoStruct(&m.Graph, unsafe.Pointer(&mem.graph))
	Node__Sequence_to_Go(&m.Nodes, mem.nodes)
}

func (t _MapDataTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__msg__MapData())
}

type CMapData = C.rtabmap_msgs__msg__MapData
type CMapData__Sequence = C.rtabmap_msgs__msg__MapData__Sequence

func MapData__Sequence_to_Go(goSlice *[]MapData, cSlice CMapData__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MapData, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MapDataTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MapData__Sequence_to_C(cSlice *CMapData__Sequence, goSlice []MapData) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__msg__MapData)(C.malloc(C.sizeof_struct_rtabmap_msgs__msg__MapData * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MapDataTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MapData__Array_to_Go(goSlice []MapData, cSlice []CMapData) {
	for i := 0; i < len(cSlice); i++ {
		MapDataTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MapData__Array_to_C(cSlice []CMapData, goSlice []MapData) {
	for i := 0; i < len(goSlice); i++ {
		MapDataTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
