// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geometry_msgs_msg "dog-stream-gateway/internal/msgs/geometry_msgs/msg"
	sensor_msgs_msg "dog-stream-gateway/internal/msgs/sensor_msgs/msg"
	std_msgs_msg "dog-stream-gateway/internal/msgs/std_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/msg/odom_info.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/OdomInfo", OdomInfoTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/msg/OdomInfo", OdomInfoTypeSupport)
}

type OdomInfo struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Lost bool `yaml:"lost"`
	Matches int32 `yaml:"matches"`
	Inliers int32 `yaml:"inliers"`
	IcpInliersRatio float32 `yaml:"icp_inliers_ratio"`
	IcpRotation float32 `yaml:"icp_rotation"`
	IcpTranslation float32 `yaml:"icp_translation"`
	IcpStructuralComplexity float32 `yaml:"icp_structural_complexity"`
	IcpStructuralDistribution float32 `yaml:"icp_structural_distribution"`
	IcpCorrespondences int32 `yaml:"icp_correspondences"`
	Covariance [36]float64 `yaml:"covariance"`
	Features int32 `yaml:"features"`
	LocalMapSize int32 `yaml:"local_map_size"`
	LocalScanMapSize int32 `yaml:"local_scan_map_size"`
	LocalKeyFrames int32 `yaml:"local_key_frames"`
	LocalBundleOutliers int32 `yaml:"local_bundle_outliers"`
	LocalBundleConstraints int32 `yaml:"local_bundle_constraints"`
	LocalBundleTime float32 `yaml:"local_bundle_time"`
	LocalBundleAvgInlierDistance float32 `yaml:"local_bundle_avg_inlier_distance"`
	LocalBundleMaxKeyFramesForInlier int32 `yaml:"local_bundle_max_key_frames_for_inlier"`
	KeyFrameAdded bool `yaml:"key_frame_added"`
	TimeEstimation float32 `yaml:"time_estimation"`
	TimeParticleFiltering float32 `yaml:"time_particle_filtering"`
	Stamp float32 `yaml:"stamp"`
	Interval float32 `yaml:"interval"`
	DistanceTravelled float32 `yaml:"distance_travelled"`
	MemoryUsage int32 `yaml:"memory_usage"`// MB
	GravityRollError float32 `yaml:"gravity_roll_error"`
	GravityPitchError float32 `yaml:"gravity_pitch_error"`
	LocalBundleIds []int32 `yaml:"local_bundle_ids"`// Local bundle camera ids
	LocalBundleModels []CameraModels `yaml:"local_bundle_models"`// Local bundle camera models
	LocalBundlePoses []geometry_msgs_msg.Pose `yaml:"local_bundle_poses"`// Local bundle camera poses
	Transform geometry_msgs_msg.Transform `yaml:"transform"`
	TransformFiltered geometry_msgs_msg.Transform `yaml:"transform_filtered"`
	TransformGroundTruth geometry_msgs_msg.Transform `yaml:"transform_ground_truth"`
	Guess geometry_msgs_msg.Transform `yaml:"guess"`
	Type int32 `yaml:"type"`// 0=F2M, 1=F2F
	WordsKeys []int32 `yaml:"words_keys"`// F2M odometrystd::multimap<int, cv::KeyPoint> words;std::vector<int> wordMatches;std::vector<int> wordInliers;
	WordsValues []KeyPoint `yaml:"words_values"`
	WordMatches []int32 `yaml:"word_matches"`
	WordInliers []int32 `yaml:"word_inliers"`
	LocalMapKeys []int32 `yaml:"local_map_keys"`
	LocalMapValues []Point3f `yaml:"local_map_values"`
	LocalScanMap sensor_msgs_msg.PointCloud2 `yaml:"local_scan_map"`// local scan map data
	RefCorners []Point2f `yaml:"ref_corners"`// F2F odometrystd::vector<cv::Point2f> ref_corners;std::vector<cv::Point2f> new_corners;std::vector<int> corner_inliers;
	NewCorners []Point2f `yaml:"new_corners"`
	CornerInliers []int32 `yaml:"corner_inliers"`
}

// NewOdomInfo creates a new OdomInfo with default values.
func NewOdomInfo() *OdomInfo {
	self := OdomInfo{}
	self.SetDefaults()
	return &self
}

func (t *OdomInfo) Clone() *OdomInfo {
	c := &OdomInfo{}
	c.Header = *t.Header.Clone()
	c.Lost = t.Lost
	c.Matches = t.Matches
	c.Inliers = t.Inliers
	c.IcpInliersRatio = t.IcpInliersRatio
	c.IcpRotation = t.IcpRotation
	c.IcpTranslation = t.IcpTranslation
	c.IcpStructuralComplexity = t.IcpStructuralComplexity
	c.IcpStructuralDistribution = t.IcpStructuralDistribution
	c.IcpCorrespondences = t.IcpCorrespondences
	c.Covariance = t.Covariance
	c.Features = t.Features
	c.LocalMapSize = t.LocalMapSize
	c.LocalScanMapSize = t.LocalScanMapSize
	c.LocalKeyFrames = t.LocalKeyFrames
	c.LocalBundleOutliers = t.LocalBundleOutliers
	c.LocalBundleConstraints = t.LocalBundleConstraints
	c.LocalBundleTime = t.LocalBundleTime
	c.LocalBundleAvgInlierDistance = t.LocalBundleAvgInlierDistance
	c.LocalBundleMaxKeyFramesForInlier = t.LocalBundleMaxKeyFramesForInlier
	c.KeyFrameAdded = t.KeyFrameAdded
	c.TimeEstimation = t.TimeEstimation
	c.TimeParticleFiltering = t.TimeParticleFiltering
	c.Stamp = t.Stamp
	c.Interval = t.Interval
	c.DistanceTravelled = t.DistanceTravelled
	c.MemoryUsage = t.MemoryUsage
	c.GravityRollError = t.GravityRollError
	c.GravityPitchError = t.GravityPitchError
	if t.LocalBundleIds != nil {
		c.LocalBundleIds = make([]int32, len(t.LocalBundleIds))
		copy(c.LocalBundleIds, t.LocalBundleIds)
	}
	if t.LocalBundleModels != nil {
		c.LocalBundleModels = make([]CameraModels, len(t.LocalBundleModels))
		CloneCameraModelsSlice(c.LocalBundleModels, t.LocalBundleModels)
	}
	if t.LocalBundlePoses != nil {
		c.LocalBundlePoses = make([]geometry_msgs_msg.Pose, len(t.LocalBundlePoses))
		geometry_msgs_msg.ClonePoseSlice(c.LocalBundlePoses, t.LocalBundlePoses)
	}
	c.Transform = *t.Transform.Clone()
	c.TransformFiltered = *t.TransformFiltered.Clone()
	c.TransformGroundTruth = *t.TransformGroundTruth.Clone()
	c.Guess = *t.Guess.Clone()
	c.Type = t.Type
	if t.WordsKeys != nil {
		c.WordsKeys = make([]int32, len(t.WordsKeys))
		copy(c.WordsKeys, t.WordsKeys)
	}
	if t.WordsValues != nil {
		c.WordsValues = make([]KeyPoint, len(t.WordsValues))
		CloneKeyPointSlice(c.WordsValues, t.WordsValues)
	}
	if t.WordMatches != nil {
		c.WordMatches = make([]int32, len(t.WordMatches))
		copy(c.WordMatches, t.WordMatches)
	}
	if t.WordInliers != nil {
		c.WordInliers = make([]int32, len(t.WordInliers))
		copy(c.WordInliers, t.WordInliers)
	}
	if t.LocalMapKeys != nil {
		c.LocalMapKeys = make([]int32, len(t.LocalMapKeys))
		copy(c.LocalMapKeys, t.LocalMapKeys)
	}
	if t.LocalMapValues != nil {
		c.LocalMapValues = make([]Point3f, len(t.LocalMapValues))
		ClonePoint3fSlice(c.LocalMapValues, t.LocalMapValues)
	}
	c.LocalScanMap = *t.LocalScanMap.Clone()
	if t.RefCorners != nil {
		c.RefCorners = make([]Point2f, len(t.RefCorners))
		ClonePoint2fSlice(c.RefCorners, t.RefCorners)
	}
	if t.NewCorners != nil {
		c.NewCorners = make([]Point2f, len(t.NewCorners))
		ClonePoint2fSlice(c.NewCorners, t.NewCorners)
	}
	if t.CornerInliers != nil {
		c.CornerInliers = make([]int32, len(t.CornerInliers))
		copy(c.CornerInliers, t.CornerInliers)
	}
	return c
}

func (t *OdomInfo) CloneMsg() types.Message {
	return t.Clone()
}

func (t *OdomInfo) SetDefaults() {
	t.Header.SetDefaults()
	t.Lost = false
	t.Matches = 0
	t.Inliers = 0
	t.IcpInliersRatio = 0
	t.IcpRotation = 0
	t.IcpTranslation = 0
	t.IcpStructuralComplexity = 0
	t.IcpStructuralDistribution = 0
	t.IcpCorrespondences = 0
	t.Covariance = [36]float64{}
	t.Features = 0
	t.LocalMapSize = 0
	t.LocalScanMapSize = 0
	t.LocalKeyFrames = 0
	t.LocalBundleOutliers = 0
	t.LocalBundleConstraints = 0
	t.LocalBundleTime = 0
	t.LocalBundleAvgInlierDistance = 0
	t.LocalBundleMaxKeyFramesForInlier = 0
	t.KeyFrameAdded = false
	t.TimeEstimation = 0
	t.TimeParticleFiltering = 0
	t.Stamp = 0
	t.Interval = 0
	t.DistanceTravelled = 0
	t.MemoryUsage = 0
	t.GravityRollError = 0
	t.GravityPitchError = 0
	t.LocalBundleIds = nil
	t.LocalBundleModels = nil
	t.LocalBundlePoses = nil
	t.Transform.SetDefaults()
	t.TransformFiltered.SetDefaults()
	t.TransformGroundTruth.SetDefaults()
	t.Guess.SetDefaults()
	t.Type = 0
	t.WordsKeys = nil
	t.WordsValues = nil
	t.WordMatches = nil
	t.WordInliers = nil
	t.LocalMapKeys = nil
	t.LocalMapValues = nil
	t.LocalScanMap.SetDefaults()
	t.RefCorners = nil
	t.NewCorners = nil
	t.CornerInliers = nil
}

func (t *OdomInfo) GetTypeSupport() types.MessageTypeSupport {
	return OdomInfoTypeSupport
}

// OdomInfoPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type OdomInfoPublisher struct {
	*rclgo.Publisher
}

// NewOdomInfoPublisher creates and returns a new publisher for the
// OdomInfo
func NewOdomInfoPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*OdomInfoPublisher, error) {
	pub, err := node.NewPublisher(topic_name, OdomInfoTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &OdomInfoPublisher{pub}, nil
}

func (p *OdomInfoPublisher) Publish(msg *OdomInfo) error {
	return p.Publisher.Publish(msg)
}

// OdomInfoSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type OdomInfoSubscription struct {
	*rclgo.Subscription
}

// OdomInfoSubscriptionCallback type is used to provide a subscription
// handler function for a OdomInfoSubscription.
type OdomInfoSubscriptionCallback func(msg *OdomInfo, info *rclgo.MessageInfo, err error)

// NewOdomInfoSubscription creates and returns a new subscription for the
// OdomInfo
func NewOdomInfoSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback OdomInfoSubscriptionCallback) (*OdomInfoSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg OdomInfo
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, OdomInfoTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &OdomInfoSubscription{sub}, nil
}

func (s *OdomInfoSubscription) TakeMessage(out *OdomInfo) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneOdomInfoSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneOdomInfoSlice(dst, src []OdomInfo) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var OdomInfoTypeSupport types.MessageTypeSupport = _OdomInfoTypeSupport{}

type _OdomInfoTypeSupport struct{}

func (t _OdomInfoTypeSupport) New() types.Message {
	return NewOdomInfo()
}

func (t _OdomInfoTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__msg__OdomInfo
	return (unsafe.Pointer)(C.rtabmap_msgs__msg__OdomInfo__create())
}

func (t _OdomInfoTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__msg__OdomInfo__destroy((*C.rtabmap_msgs__msg__OdomInfo)(pointer_to_free))
}

func (t _OdomInfoTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*OdomInfo)
	mem := (*C.rtabmap_msgs__msg__OdomInfo)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	mem.lost = C.bool(m.Lost)
	mem.matches = C.int32_t(m.Matches)
	mem.inliers = C.int32_t(m.Inliers)
	mem.icp_inliers_ratio = C.float(m.IcpInliersRatio)
	mem.icp_rotation = C.float(m.IcpRotation)
	mem.icp_translation = C.float(m.IcpTranslation)
	mem.icp_structural_complexity = C.float(m.IcpStructuralComplexity)
	mem.icp_structural_distribution = C.float(m.IcpStructuralDistribution)
	mem.icp_correspondences = C.int32_t(m.IcpCorrespondences)
	cSlice_covariance := mem.covariance[:]
	primitives.Float64__Array_to_C(*(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_covariance)), m.Covariance[:])
	mem.features = C.int32_t(m.Features)
	mem.local_map_size = C.int32_t(m.LocalMapSize)
	mem.local_scan_map_size = C.int32_t(m.LocalScanMapSize)
	mem.local_key_frames = C.int32_t(m.LocalKeyFrames)
	mem.local_bundle_outliers = C.int32_t(m.LocalBundleOutliers)
	mem.local_bundle_constraints = C.int32_t(m.LocalBundleConstraints)
	mem.local_bundle_time = C.float(m.LocalBundleTime)
	mem.local_bundle_avg_inlier_distance = C.float(m.LocalBundleAvgInlierDistance)
	mem.local_bundle_max_key_frames_for_inlier = C.int32_t(m.LocalBundleMaxKeyFramesForInlier)
	mem.key_frame_added = C.bool(m.KeyFrameAdded)
	mem.time_estimation = C.float(m.TimeEstimation)
	mem.time_particle_filtering = C.float(m.TimeParticleFiltering)
	mem.stamp = C.float(m.Stamp)
	mem.interval = C.float(m.Interval)
	mem.distance_travelled = C.float(m.DistanceTravelled)
	mem.memory_usage = C.int32_t(m.MemoryUsage)
	mem.gravity_roll_error = C.float(m.GravityRollError)
	mem.gravity_pitch_error = C.float(m.GravityPitchError)
	primitives.Int32__Sequence_to_C((*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.local_bundle_ids)), m.LocalBundleIds)
	CameraModels__Sequence_to_C(&mem.local_bundle_models, m.LocalBundleModels)
	geometry_msgs_msg.Pose__Sequence_to_C((*geometry_msgs_msg.CPose__Sequence)(unsafe.Pointer(&mem.local_bundle_poses)), m.LocalBundlePoses)
	geometry_msgs_msg.TransformTypeSupport.AsCStruct(unsafe.Pointer(&mem.transform), &m.Transform)
	geometry_msgs_msg.TransformTypeSupport.AsCStruct(unsafe.Pointer(&mem.transform_filtered), &m.TransformFiltered)
	geometry_msgs_msg.TransformTypeSupport.AsCStruct(unsafe.Pointer(&mem.transform_ground_truth), &m.TransformGroundTruth)
	geometry_msgs_msg.TransformTypeSupport.AsCStruct(unsafe.Pointer(&mem.guess), &m.Guess)
	mem._type = C.int32_t(m.Type)
	primitives.Int32__Sequence_to_C((*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.words_keys)), m.WordsKeys)
	KeyPoint__Sequence_to_C(&mem.words_values, m.WordsValues)
	primitives.Int32__Sequence_to_C((*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.word_matches)), m.WordMatches)
	primitives.Int32__Sequence_to_C((*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.word_inliers)), m.WordInliers)
	primitives.Int32__Sequence_to_C((*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.local_map_keys)), m.LocalMapKeys)
	Point3f__Sequence_to_C(&mem.local_map_values, m.LocalMapValues)
	sensor_msgs_msg.PointCloud2TypeSupport.AsCStruct(unsafe.Pointer(&mem.local_scan_map), &m.LocalScanMap)
	Point2f__Sequence_to_C(&mem.ref_corners, m.RefCorners)
	Point2f__Sequence_to_C(&mem.new_corners, m.NewCorners)
	primitives.Int32__Sequence_to_C((*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.corner_inliers)), m.CornerInliers)
}

func (t _OdomInfoTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*OdomInfo)
	mem := (*C.rtabmap_msgs__msg__OdomInfo)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	m.Lost = bool(mem.lost)
	m.Matches = int32(mem.matches)
	m.Inliers = int32(mem.inliers)
	m.IcpInliersRatio = float32(mem.icp_inliers_ratio)
	m.IcpRotation = float32(mem.icp_rotation)
	m.IcpTranslation = float32(mem.icp_translation)
	m.IcpStructuralComplexity = float32(mem.icp_structural_complexity)
	m.IcpStructuralDistribution = float32(mem.icp_structural_distribution)
	m.IcpCorrespondences = int32(mem.icp_correspondences)
	cSlice_covariance := mem.covariance[:]
	primitives.Float64__Array_to_Go(m.Covariance[:], *(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_covariance)))
	m.Features = int32(mem.features)
	m.LocalMapSize = int32(mem.local_map_size)
	m.LocalScanMapSize = int32(mem.local_scan_map_size)
	m.LocalKeyFrames = int32(mem.local_key_frames)
	m.LocalBundleOutliers = int32(mem.local_bundle_outliers)
	m.LocalBundleConstraints = int32(mem.local_bundle_constraints)
	m.LocalBundleTime = float32(mem.local_bundle_time)
	m.LocalBundleAvgInlierDistance = float32(mem.local_bundle_avg_inlier_distance)
	m.LocalBundleMaxKeyFramesForInlier = int32(mem.local_bundle_max_key_frames_for_inlier)
	m.KeyFrameAdded = bool(mem.key_frame_added)
	m.TimeEstimation = float32(mem.time_estimation)
	m.TimeParticleFiltering = float32(mem.time_particle_filtering)
	m.Stamp = float32(mem.stamp)
	m.Interval = float32(mem.interval)
	m.DistanceTravelled = float32(mem.distance_travelled)
	m.MemoryUsage = int32(mem.memory_usage)
	m.GravityRollError = float32(mem.gravity_roll_error)
	m.GravityPitchError = float32(mem.gravity_pitch_error)
	primitives.Int32__Sequence_to_Go(&m.LocalBundleIds, *(*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.local_bundle_ids)))
	CameraModels__Sequence_to_Go(&m.LocalBundleModels, mem.local_bundle_models)
	geometry_msgs_msg.Pose__Sequence_to_Go(&m.LocalBundlePoses, *(*geometry_msgs_msg.CPose__Sequence)(unsafe.Pointer(&mem.local_bundle_poses)))
	geometry_msgs_msg.TransformTypeSupport.AsGoStruct(&m.Transform, unsafe.Pointer(&mem.transform))
	geometry_msgs_msg.TransformTypeSupport.AsGoStruct(&m.TransformFiltered, unsafe.Pointer(&mem.transform_filtered))
	geometry_msgs_msg.TransformTypeSupport.AsGoStruct(&m.TransformGroundTruth, unsafe.Pointer(&mem.transform_ground_truth))
	geometry_msgs_msg.TransformTypeSupport.AsGoStruct(&m.Guess, unsafe.Pointer(&mem.guess))
	m.Type = int32(mem._type)
	primitives.Int32__Sequence_to_Go(&m.WordsKeys, *(*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.words_keys)))
	KeyPoint__Sequence_to_Go(&m.WordsValues, mem.words_values)
	primitives.Int32__Sequence_to_Go(&m.WordMatches, *(*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.word_matches)))
	primitives.Int32__Sequence_to_Go(&m.WordInliers, *(*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.word_inliers)))
	primitives.Int32__Sequence_to_Go(&m.LocalMapKeys, *(*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.local_map_keys)))
	Point3f__Sequence_to_Go(&m.LocalMapValues, mem.local_map_values)
	sensor_msgs_msg.PointCloud2TypeSupport.AsGoStruct(&m.LocalScanMap, unsafe.Pointer(&mem.local_scan_map))
	Point2f__Sequence_to_Go(&m.RefCorners, mem.ref_corners)
	Point2f__Sequence_to_Go(&m.NewCorners, mem.new_corners)
	primitives.Int32__Sequence_to_Go(&m.CornerInliers, *(*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.corner_inliers)))
}

func (t _OdomInfoTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__msg__OdomInfo())
}

type COdomInfo = C.rtabmap_msgs__msg__OdomInfo
type COdomInfo__Sequence = C.rtabmap_msgs__msg__OdomInfo__Sequence

func OdomInfo__Sequence_to_Go(goSlice *[]OdomInfo, cSlice COdomInfo__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]OdomInfo, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		OdomInfoTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func OdomInfo__Sequence_to_C(cSlice *COdomInfo__Sequence, goSlice []OdomInfo) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__msg__OdomInfo)(C.malloc(C.sizeof_struct_rtabmap_msgs__msg__OdomInfo * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		OdomInfoTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func OdomInfo__Array_to_Go(goSlice []OdomInfo, cSlice []COdomInfo) {
	for i := 0; i < len(cSlice); i++ {
		OdomInfoTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func OdomInfo__Array_to_C(cSlice []COdomInfo, goSlice []OdomInfo) {
	for i := 0; i < len(goSlice); i++ {
		OdomInfoTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
