// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/msg/point2f.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/Point2f", Point2fTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/msg/Point2f", Point2fTypeSupport)
}

type Point2f struct {
	X float32 `yaml:"x"`
	Y float32 `yaml:"y"`
}

// NewPoint2f creates a new Point2f with default values.
func NewPoint2f() *Point2f {
	self := Point2f{}
	self.SetDefaults()
	return &self
}

func (t *Point2f) Clone() *Point2f {
	c := &Point2f{}
	c.X = t.X
	c.Y = t.Y
	return c
}

func (t *Point2f) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Point2f) SetDefaults() {
	t.X = 0
	t.Y = 0
}

func (t *Point2f) GetTypeSupport() types.MessageTypeSupport {
	return Point2fTypeSupport
}

// Point2fPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Point2fPublisher struct {
	*rclgo.Publisher
}

// NewPoint2fPublisher creates and returns a new publisher for the
// Point2f
func NewPoint2fPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Point2fPublisher, error) {
	pub, err := node.NewPublisher(topic_name, Point2fTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Point2fPublisher{pub}, nil
}

func (p *Point2fPublisher) Publish(msg *Point2f) error {
	return p.Publisher.Publish(msg)
}

// Point2fSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Point2fSubscription struct {
	*rclgo.Subscription
}

// Point2fSubscriptionCallback type is used to provide a subscription
// handler function for a Point2fSubscription.
type Point2fSubscriptionCallback func(msg *Point2f, info *rclgo.MessageInfo, err error)

// NewPoint2fSubscription creates and returns a new subscription for the
// Point2f
func NewPoint2fSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Point2fSubscriptionCallback) (*Point2fSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Point2f
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Point2fTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Point2fSubscription{sub}, nil
}

func (s *Point2fSubscription) TakeMessage(out *Point2f) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// ClonePoint2fSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePoint2fSlice(dst, src []Point2f) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Point2fTypeSupport types.MessageTypeSupport = _Point2fTypeSupport{}

type _Point2fTypeSupport struct{}

func (t _Point2fTypeSupport) New() types.Message {
	return NewPoint2f()
}

func (t _Point2fTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__msg__Point2f
	return (unsafe.Pointer)(C.rtabmap_msgs__msg__Point2f__create())
}

func (t _Point2fTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__msg__Point2f__destroy((*C.rtabmap_msgs__msg__Point2f)(pointer_to_free))
}

func (t _Point2fTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Point2f)
	mem := (*C.rtabmap_msgs__msg__Point2f)(dst)
	mem.x = C.float(m.X)
	mem.y = C.float(m.Y)
}

func (t _Point2fTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Point2f)
	mem := (*C.rtabmap_msgs__msg__Point2f)(ros2_message_buffer)
	m.X = float32(mem.x)
	m.Y = float32(mem.y)
}

func (t _Point2fTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__msg__Point2f())
}

type CPoint2f = C.rtabmap_msgs__msg__Point2f
type CPoint2f__Sequence = C.rtabmap_msgs__msg__Point2f__Sequence

func Point2f__Sequence_to_Go(goSlice *[]Point2f, cSlice CPoint2f__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Point2f, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Point2fTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Point2f__Sequence_to_C(cSlice *CPoint2f__Sequence, goSlice []Point2f) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__msg__Point2f)(C.malloc(C.sizeof_struct_rtabmap_msgs__msg__Point2f * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Point2fTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Point2f__Array_to_Go(goSlice []Point2f, cSlice []CPoint2f) {
	for i := 0; i < len(cSlice); i++ {
		Point2fTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Point2f__Array_to_C(cSlice []CPoint2f, goSlice []Point2f) {
	for i := 0; i < len(goSlice); i++ {
		Point2fTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
