// Code generated by rclgo-gen. DO NOT EDIT.

package rtabmap_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "dog-stream-gateway/internal/msgs/std_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rtabmap_msgs/msg/rgbd_images.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rtabmap_msgs/RGBDImages", RGBDImagesTypeSupport)
	typemap.RegisterMessage("rtabmap_msgs/msg/RGBDImages", RGBDImagesTypeSupport)
}

type RGBDImages struct {
	Header std_msgs_msg.Header `yaml:"header"`
	RgbdImages []RGBDImage `yaml:"rgbd_images"`
}

// NewRGBDImages creates a new RGBDImages with default values.
func NewRGBDImages() *RGBDImages {
	self := RGBDImages{}
	self.SetDefaults()
	return &self
}

func (t *RGBDImages) Clone() *RGBDImages {
	c := &RGBDImages{}
	c.Header = *t.Header.Clone()
	if t.RgbdImages != nil {
		c.RgbdImages = make([]RGBDImage, len(t.RgbdImages))
		CloneRGBDImageSlice(c.RgbdImages, t.RgbdImages)
	}
	return c
}

func (t *RGBDImages) CloneMsg() types.Message {
	return t.Clone()
}

func (t *RGBDImages) SetDefaults() {
	t.Header.SetDefaults()
	t.RgbdImages = nil
}

func (t *RGBDImages) GetTypeSupport() types.MessageTypeSupport {
	return RGBDImagesTypeSupport
}

// RGBDImagesPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type RGBDImagesPublisher struct {
	*rclgo.Publisher
}

// NewRGBDImagesPublisher creates and returns a new publisher for the
// RGBDImages
func NewRGBDImagesPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*RGBDImagesPublisher, error) {
	pub, err := node.NewPublisher(topic_name, RGBDImagesTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &RGBDImagesPublisher{pub}, nil
}

func (p *RGBDImagesPublisher) Publish(msg *RGBDImages) error {
	return p.Publisher.Publish(msg)
}

// RGBDImagesSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type RGBDImagesSubscription struct {
	*rclgo.Subscription
}

// RGBDImagesSubscriptionCallback type is used to provide a subscription
// handler function for a RGBDImagesSubscription.
type RGBDImagesSubscriptionCallback func(msg *RGBDImages, info *rclgo.MessageInfo, err error)

// NewRGBDImagesSubscription creates and returns a new subscription for the
// RGBDImages
func NewRGBDImagesSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback RGBDImagesSubscriptionCallback) (*RGBDImagesSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg RGBDImages
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, RGBDImagesTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &RGBDImagesSubscription{sub}, nil
}

func (s *RGBDImagesSubscription) TakeMessage(out *RGBDImages) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneRGBDImagesSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneRGBDImagesSlice(dst, src []RGBDImages) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var RGBDImagesTypeSupport types.MessageTypeSupport = _RGBDImagesTypeSupport{}

type _RGBDImagesTypeSupport struct{}

func (t _RGBDImagesTypeSupport) New() types.Message {
	return NewRGBDImages()
}

func (t _RGBDImagesTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rtabmap_msgs__msg__RGBDImages
	return (unsafe.Pointer)(C.rtabmap_msgs__msg__RGBDImages__create())
}

func (t _RGBDImagesTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rtabmap_msgs__msg__RGBDImages__destroy((*C.rtabmap_msgs__msg__RGBDImages)(pointer_to_free))
}

func (t _RGBDImagesTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*RGBDImages)
	mem := (*C.rtabmap_msgs__msg__RGBDImages)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	RGBDImage__Sequence_to_C(&mem.rgbd_images, m.RgbdImages)
}

func (t _RGBDImagesTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*RGBDImages)
	mem := (*C.rtabmap_msgs__msg__RGBDImages)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	RGBDImage__Sequence_to_Go(&m.RgbdImages, mem.rgbd_images)
}

func (t _RGBDImagesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rtabmap_msgs__msg__RGBDImages())
}

type CRGBDImages = C.rtabmap_msgs__msg__RGBDImages
type CRGBDImages__Sequence = C.rtabmap_msgs__msg__RGBDImages__Sequence

func RGBDImages__Sequence_to_Go(goSlice *[]RGBDImages, cSlice CRGBDImages__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]RGBDImages, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		RGBDImagesTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func RGBDImages__Sequence_to_C(cSlice *CRGBDImages__Sequence, goSlice []RGBDImages) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rtabmap_msgs__msg__RGBDImages)(C.malloc(C.sizeof_struct_rtabmap_msgs__msg__RGBDImages * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		RGBDImagesTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func RGBDImages__Array_to_Go(goSlice []RGBDImages, cSlice []CRGBDImages) {
	for i := 0; i < len(cSlice); i++ {
		RGBDImagesTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func RGBDImages__Array_to_C(cSlice []CRGBDImages, goSlice []RGBDImages) {
	for i := 0; i < len(goSlice); i++ {
		RGBDImagesTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
