// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <nav2_msgs/srv/get_costmap.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("nav2_msgs/GetCostmap", GetCostmapTypeSupport)
	typemap.RegisterService("nav2_msgs/srv/GetCostmap", GetCostmapTypeSupport)
}

type _GetCostmapTypeSupport struct {}

func (s _GetCostmapTypeSupport) Request() types.MessageTypeSupport {
	return GetCostmap_RequestTypeSupport
}

func (s _GetCostmapTypeSupport) Response() types.MessageTypeSupport {
	return GetCostmap_ResponseTypeSupport
}

func (s _GetCostmapTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__nav2_msgs__srv__GetCostmap())
}

// Modifying this variable is undefined behavior.
var GetCostmapTypeSupport types.ServiceTypeSupport = _GetCostmapTypeSupport{}

// GetCostmapClient wraps rclgo.Client to provide type safe helper
// functions
type GetCostmapClient struct {
	*rclgo.Client
}

// NewGetCostmapClient creates and returns a new client for the
// GetCostmap
func NewGetCostmapClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GetCostmapClient, error) {
	client, err := node.NewClient(serviceName, GetCostmapTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetCostmapClient{client}, nil
}

func (s *GetCostmapClient) Send(ctx context.Context, req *GetCostmap_Request) (*GetCostmap_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetCostmap_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetCostmapServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GetCostmapServiceResponseSender) SendResponse(resp *GetCostmap_Response) error {
	return s.sender.SendResponse(resp)
}

type GetCostmapServiceRequestHandler func(*rclgo.ServiceInfo, *GetCostmap_Request, GetCostmapServiceResponseSender)

// GetCostmapService wraps rclgo.Service to provide type safe helper
// functions
type GetCostmapService struct {
	*rclgo.Service
}

// NewGetCostmapService creates and returns a new service for the
// GetCostmap
func NewGetCostmapService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GetCostmapServiceRequestHandler) (*GetCostmapService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GetCostmap_Request)
		responseSender := GetCostmapServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetCostmapTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetCostmapService{service}, nil
}