// Code generated by rclgo-gen. DO NOT EDIT.

package nav2_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav2_msgs/srv/is_path_valid.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav2_msgs/IsPathValid_Response", IsPathValid_ResponseTypeSupport)
	typemap.RegisterMessage("nav2_msgs/srv/IsPathValid_Response", IsPathValid_ResponseTypeSupport)
}

type IsPathValid_Response struct {
	IsValid bool `yaml:"is_valid"`
	InvalidPoseIndices []int32 `yaml:"invalid_pose_indices"`
}

// NewIsPathValid_Response creates a new IsPathValid_Response with default values.
func NewIsPathValid_Response() *IsPathValid_Response {
	self := IsPathValid_Response{}
	self.SetDefaults()
	return &self
}

func (t *IsPathValid_Response) Clone() *IsPathValid_Response {
	c := &IsPathValid_Response{}
	c.IsValid = t.IsValid
	if t.InvalidPoseIndices != nil {
		c.InvalidPoseIndices = make([]int32, len(t.InvalidPoseIndices))
		copy(c.InvalidPoseIndices, t.InvalidPoseIndices)
	}
	return c
}

func (t *IsPathValid_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *IsPathValid_Response) SetDefaults() {
	t.IsValid = false
	t.InvalidPoseIndices = nil
}

func (t *IsPathValid_Response) GetTypeSupport() types.MessageTypeSupport {
	return IsPathValid_ResponseTypeSupport
}

// IsPathValid_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type IsPathValid_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewIsPathValid_ResponsePublisher creates and returns a new publisher for the
// IsPathValid_Response
func NewIsPathValid_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*IsPathValid_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, IsPathValid_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IsPathValid_ResponsePublisher{pub}, nil
}

func (p *IsPathValid_ResponsePublisher) Publish(msg *IsPathValid_Response) error {
	return p.Publisher.Publish(msg)
}

// IsPathValid_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type IsPathValid_ResponseSubscription struct {
	*rclgo.Subscription
}

// IsPathValid_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a IsPathValid_ResponseSubscription.
type IsPathValid_ResponseSubscriptionCallback func(msg *IsPathValid_Response, info *rclgo.MessageInfo, err error)

// NewIsPathValid_ResponseSubscription creates and returns a new subscription for the
// IsPathValid_Response
func NewIsPathValid_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback IsPathValid_ResponseSubscriptionCallback) (*IsPathValid_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg IsPathValid_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, IsPathValid_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &IsPathValid_ResponseSubscription{sub}, nil
}

func (s *IsPathValid_ResponseSubscription) TakeMessage(out *IsPathValid_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneIsPathValid_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneIsPathValid_ResponseSlice(dst, src []IsPathValid_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var IsPathValid_ResponseTypeSupport types.MessageTypeSupport = _IsPathValid_ResponseTypeSupport{}

type _IsPathValid_ResponseTypeSupport struct{}

func (t _IsPathValid_ResponseTypeSupport) New() types.Message {
	return NewIsPathValid_Response()
}

func (t _IsPathValid_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav2_msgs__srv__IsPathValid_Response
	return (unsafe.Pointer)(C.nav2_msgs__srv__IsPathValid_Response__create())
}

func (t _IsPathValid_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav2_msgs__srv__IsPathValid_Response__destroy((*C.nav2_msgs__srv__IsPathValid_Response)(pointer_to_free))
}

func (t _IsPathValid_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*IsPathValid_Response)
	mem := (*C.nav2_msgs__srv__IsPathValid_Response)(dst)
	mem.is_valid = C.bool(m.IsValid)
	primitives.Int32__Sequence_to_C((*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.invalid_pose_indices)), m.InvalidPoseIndices)
}

func (t _IsPathValid_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*IsPathValid_Response)
	mem := (*C.nav2_msgs__srv__IsPathValid_Response)(ros2_message_buffer)
	m.IsValid = bool(mem.is_valid)
	primitives.Int32__Sequence_to_Go(&m.InvalidPoseIndices, *(*primitives.CInt32__Sequence)(unsafe.Pointer(&mem.invalid_pose_indices)))
}

func (t _IsPathValid_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav2_msgs__srv__IsPathValid_Response())
}

type CIsPathValid_Response = C.nav2_msgs__srv__IsPathValid_Response
type CIsPathValid_Response__Sequence = C.nav2_msgs__srv__IsPathValid_Response__Sequence

func IsPathValid_Response__Sequence_to_Go(goSlice *[]IsPathValid_Response, cSlice CIsPathValid_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]IsPathValid_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		IsPathValid_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func IsPathValid_Response__Sequence_to_C(cSlice *CIsPathValid_Response__Sequence, goSlice []IsPathValid_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.nav2_msgs__srv__IsPathValid_Response)(C.malloc(C.sizeof_struct_nav2_msgs__srv__IsPathValid_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		IsPathValid_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func IsPathValid_Response__Array_to_Go(goSlice []IsPathValid_Response, cSlice []CIsPathValid_Response) {
	for i := 0; i < len(cSlice); i++ {
		IsPathValid_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func IsPathValid_Response__Array_to_C(cSlice []CIsPathValid_Response, goSlice []IsPathValid_Response) {
	for i := 0; i < len(goSlice); i++ {
		IsPathValid_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
