// Code generated by rclgo-gen. DO NOT EDIT.

package slam_toolbox_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <slam_toolbox/srv/clear.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("slam_toolbox/Clear_Response", Clear_ResponseTypeSupport)
	typemap.RegisterMessage("slam_toolbox/srv/Clear_Response", Clear_ResponseTypeSupport)
}

type Clear_Response struct {
}

// NewClear_Response creates a new Clear_Response with default values.
func NewClear_Response() *Clear_Response {
	self := Clear_Response{}
	self.SetDefaults()
	return &self
}

func (t *Clear_Response) Clone() *Clear_Response {
	c := &Clear_Response{}
	return c
}

func (t *Clear_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Clear_Response) SetDefaults() {
}

func (t *Clear_Response) GetTypeSupport() types.MessageTypeSupport {
	return Clear_ResponseTypeSupport
}

// Clear_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type Clear_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewClear_ResponsePublisher creates and returns a new publisher for the
// Clear_Response
func NewClear_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*Clear_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, Clear_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Clear_ResponsePublisher{pub}, nil
}

func (p *Clear_ResponsePublisher) Publish(msg *Clear_Response) error {
	return p.Publisher.Publish(msg)
}

// Clear_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type Clear_ResponseSubscription struct {
	*rclgo.Subscription
}

// Clear_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Clear_ResponseSubscription.
type Clear_ResponseSubscriptionCallback func(msg *Clear_Response, info *rclgo.MessageInfo, err error)

// NewClear_ResponseSubscription creates and returns a new subscription for the
// Clear_Response
func NewClear_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback Clear_ResponseSubscriptionCallback) (*Clear_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg Clear_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, Clear_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Clear_ResponseSubscription{sub}, nil
}

func (s *Clear_ResponseSubscription) TakeMessage(out *Clear_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneClear_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneClear_ResponseSlice(dst, src []Clear_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Clear_ResponseTypeSupport types.MessageTypeSupport = _Clear_ResponseTypeSupport{}

type _Clear_ResponseTypeSupport struct{}

func (t _Clear_ResponseTypeSupport) New() types.Message {
	return NewClear_Response()
}

func (t _Clear_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.slam_toolbox__srv__Clear_Response
	return (unsafe.Pointer)(C.slam_toolbox__srv__Clear_Response__create())
}

func (t _Clear_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.slam_toolbox__srv__Clear_Response__destroy((*C.slam_toolbox__srv__Clear_Response)(pointer_to_free))
}

func (t _Clear_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _Clear_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _Clear_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__slam_toolbox__srv__Clear_Response())
}

type CClear_Response = C.slam_toolbox__srv__Clear_Response
type CClear_Response__Sequence = C.slam_toolbox__srv__Clear_Response__Sequence

func Clear_Response__Sequence_to_Go(goSlice *[]Clear_Response, cSlice CClear_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Clear_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Clear_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func Clear_Response__Sequence_to_C(cSlice *CClear_Response__Sequence, goSlice []Clear_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.slam_toolbox__srv__Clear_Response)(C.malloc(C.sizeof_struct_slam_toolbox__srv__Clear_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Clear_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func Clear_Response__Array_to_Go(goSlice []Clear_Response, cSlice []CClear_Response) {
	for i := 0; i < len(cSlice); i++ {
		Clear_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Clear_Response__Array_to_C(cSlice []CClear_Response, goSlice []Clear_Response) {
	for i := 0; i < len(goSlice); i++ {
		Clear_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
