// Code generated by rclgo-gen. DO NOT EDIT.

package slam_toolbox_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <slam_toolbox/srv/deserialize_pose_graph.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("slam_toolbox/DeserializePoseGraph_Response", DeserializePoseGraph_ResponseTypeSupport)
	typemap.RegisterMessage("slam_toolbox/srv/DeserializePoseGraph_Response", DeserializePoseGraph_ResponseTypeSupport)
}

type DeserializePoseGraph_Response struct {
}

// NewDeserializePoseGraph_Response creates a new DeserializePoseGraph_Response with default values.
func NewDeserializePoseGraph_Response() *DeserializePoseGraph_Response {
	self := DeserializePoseGraph_Response{}
	self.SetDefaults()
	return &self
}

func (t *DeserializePoseGraph_Response) Clone() *DeserializePoseGraph_Response {
	c := &DeserializePoseGraph_Response{}
	return c
}

func (t *DeserializePoseGraph_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *DeserializePoseGraph_Response) SetDefaults() {
}

func (t *DeserializePoseGraph_Response) GetTypeSupport() types.MessageTypeSupport {
	return DeserializePoseGraph_ResponseTypeSupport
}

// DeserializePoseGraph_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type DeserializePoseGraph_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewDeserializePoseGraph_ResponsePublisher creates and returns a new publisher for the
// DeserializePoseGraph_Response
func NewDeserializePoseGraph_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*DeserializePoseGraph_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, DeserializePoseGraph_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DeserializePoseGraph_ResponsePublisher{pub}, nil
}

func (p *DeserializePoseGraph_ResponsePublisher) Publish(msg *DeserializePoseGraph_Response) error {
	return p.Publisher.Publish(msg)
}

// DeserializePoseGraph_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type DeserializePoseGraph_ResponseSubscription struct {
	*rclgo.Subscription
}

// DeserializePoseGraph_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a DeserializePoseGraph_ResponseSubscription.
type DeserializePoseGraph_ResponseSubscriptionCallback func(msg *DeserializePoseGraph_Response, info *rclgo.MessageInfo, err error)

// NewDeserializePoseGraph_ResponseSubscription creates and returns a new subscription for the
// DeserializePoseGraph_Response
func NewDeserializePoseGraph_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback DeserializePoseGraph_ResponseSubscriptionCallback) (*DeserializePoseGraph_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg DeserializePoseGraph_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, DeserializePoseGraph_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &DeserializePoseGraph_ResponseSubscription{sub}, nil
}

func (s *DeserializePoseGraph_ResponseSubscription) TakeMessage(out *DeserializePoseGraph_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneDeserializePoseGraph_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneDeserializePoseGraph_ResponseSlice(dst, src []DeserializePoseGraph_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var DeserializePoseGraph_ResponseTypeSupport types.MessageTypeSupport = _DeserializePoseGraph_ResponseTypeSupport{}

type _DeserializePoseGraph_ResponseTypeSupport struct{}

func (t _DeserializePoseGraph_ResponseTypeSupport) New() types.Message {
	return NewDeserializePoseGraph_Response()
}

func (t _DeserializePoseGraph_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.slam_toolbox__srv__DeserializePoseGraph_Response
	return (unsafe.Pointer)(C.slam_toolbox__srv__DeserializePoseGraph_Response__create())
}

func (t _DeserializePoseGraph_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.slam_toolbox__srv__DeserializePoseGraph_Response__destroy((*C.slam_toolbox__srv__DeserializePoseGraph_Response)(pointer_to_free))
}

func (t _DeserializePoseGraph_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _DeserializePoseGraph_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _DeserializePoseGraph_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__slam_toolbox__srv__DeserializePoseGraph_Response())
}

type CDeserializePoseGraph_Response = C.slam_toolbox__srv__DeserializePoseGraph_Response
type CDeserializePoseGraph_Response__Sequence = C.slam_toolbox__srv__DeserializePoseGraph_Response__Sequence

func DeserializePoseGraph_Response__Sequence_to_Go(goSlice *[]DeserializePoseGraph_Response, cSlice CDeserializePoseGraph_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]DeserializePoseGraph_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		DeserializePoseGraph_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func DeserializePoseGraph_Response__Sequence_to_C(cSlice *CDeserializePoseGraph_Response__Sequence, goSlice []DeserializePoseGraph_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.slam_toolbox__srv__DeserializePoseGraph_Response)(C.malloc(C.sizeof_struct_slam_toolbox__srv__DeserializePoseGraph_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		DeserializePoseGraph_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func DeserializePoseGraph_Response__Array_to_Go(goSlice []DeserializePoseGraph_Response, cSlice []CDeserializePoseGraph_Response) {
	for i := 0; i < len(cSlice); i++ {
		DeserializePoseGraph_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func DeserializePoseGraph_Response__Array_to_C(cSlice []CDeserializePoseGraph_Response, goSlice []DeserializePoseGraph_Response) {
	for i := 0; i < len(goSlice); i++ {
		DeserializePoseGraph_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
