// Code generated by rclgo-gen. DO NOT EDIT.

package slam_toolbox_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <slam_toolbox/srv/merge_maps.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("slam_toolbox/MergeMaps_Request", MergeMaps_RequestTypeSupport)
	typemap.RegisterMessage("slam_toolbox/srv/MergeMaps_Request", MergeMaps_RequestTypeSupport)
}

type MergeMaps_Request struct {
}

// NewMergeMaps_Request creates a new MergeMaps_Request with default values.
func NewMergeMaps_Request() *MergeMaps_Request {
	self := MergeMaps_Request{}
	self.SetDefaults()
	return &self
}

func (t *MergeMaps_Request) Clone() *MergeMaps_Request {
	c := &MergeMaps_Request{}
	return c
}

func (t *MergeMaps_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MergeMaps_Request) SetDefaults() {
}

func (t *MergeMaps_Request) GetTypeSupport() types.MessageTypeSupport {
	return MergeMaps_RequestTypeSupport
}

// MergeMaps_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MergeMaps_RequestPublisher struct {
	*rclgo.Publisher
}

// NewMergeMaps_RequestPublisher creates and returns a new publisher for the
// MergeMaps_Request
func NewMergeMaps_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MergeMaps_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, MergeMaps_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MergeMaps_RequestPublisher{pub}, nil
}

func (p *MergeMaps_RequestPublisher) Publish(msg *MergeMaps_Request) error {
	return p.Publisher.Publish(msg)
}

// MergeMaps_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MergeMaps_RequestSubscription struct {
	*rclgo.Subscription
}

// MergeMaps_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a MergeMaps_RequestSubscription.
type MergeMaps_RequestSubscriptionCallback func(msg *MergeMaps_Request, info *rclgo.MessageInfo, err error)

// NewMergeMaps_RequestSubscription creates and returns a new subscription for the
// MergeMaps_Request
func NewMergeMaps_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MergeMaps_RequestSubscriptionCallback) (*MergeMaps_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MergeMaps_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MergeMaps_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MergeMaps_RequestSubscription{sub}, nil
}

func (s *MergeMaps_RequestSubscription) TakeMessage(out *MergeMaps_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMergeMaps_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMergeMaps_RequestSlice(dst, src []MergeMaps_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MergeMaps_RequestTypeSupport types.MessageTypeSupport = _MergeMaps_RequestTypeSupport{}

type _MergeMaps_RequestTypeSupport struct{}

func (t _MergeMaps_RequestTypeSupport) New() types.Message {
	return NewMergeMaps_Request()
}

func (t _MergeMaps_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.slam_toolbox__srv__MergeMaps_Request
	return (unsafe.Pointer)(C.slam_toolbox__srv__MergeMaps_Request__create())
}

func (t _MergeMaps_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.slam_toolbox__srv__MergeMaps_Request__destroy((*C.slam_toolbox__srv__MergeMaps_Request)(pointer_to_free))
}

func (t _MergeMaps_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _MergeMaps_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _MergeMaps_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__slam_toolbox__srv__MergeMaps_Request())
}

type CMergeMaps_Request = C.slam_toolbox__srv__MergeMaps_Request
type CMergeMaps_Request__Sequence = C.slam_toolbox__srv__MergeMaps_Request__Sequence

func MergeMaps_Request__Sequence_to_Go(goSlice *[]MergeMaps_Request, cSlice CMergeMaps_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MergeMaps_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MergeMaps_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MergeMaps_Request__Sequence_to_C(cSlice *CMergeMaps_Request__Sequence, goSlice []MergeMaps_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.slam_toolbox__srv__MergeMaps_Request)(C.malloc(C.sizeof_struct_slam_toolbox__srv__MergeMaps_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MergeMaps_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MergeMaps_Request__Array_to_Go(goSlice []MergeMaps_Request, cSlice []CMergeMaps_Request) {
	for i := 0; i < len(cSlice); i++ {
		MergeMaps_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MergeMaps_Request__Array_to_C(cSlice []CMergeMaps_Request, goSlice []MergeMaps_Request) {
	for i := 0; i < len(goSlice); i++ {
		MergeMaps_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
