// Code generated by rclgo-gen. DO NOT EDIT.

package slam_toolbox_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <slam_toolbox/srv/merge_maps.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("slam_toolbox/MergeMaps_Response", MergeMaps_ResponseTypeSupport)
	typemap.RegisterMessage("slam_toolbox/srv/MergeMaps_Response", MergeMaps_ResponseTypeSupport)
}

type MergeMaps_Response struct {
}

// NewMergeMaps_Response creates a new MergeMaps_Response with default values.
func NewMergeMaps_Response() *MergeMaps_Response {
	self := MergeMaps_Response{}
	self.SetDefaults()
	return &self
}

func (t *MergeMaps_Response) Clone() *MergeMaps_Response {
	c := &MergeMaps_Response{}
	return c
}

func (t *MergeMaps_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MergeMaps_Response) SetDefaults() {
}

func (t *MergeMaps_Response) GetTypeSupport() types.MessageTypeSupport {
	return MergeMaps_ResponseTypeSupport
}

// MergeMaps_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type MergeMaps_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewMergeMaps_ResponsePublisher creates and returns a new publisher for the
// MergeMaps_Response
func NewMergeMaps_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*MergeMaps_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, MergeMaps_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &MergeMaps_ResponsePublisher{pub}, nil
}

func (p *MergeMaps_ResponsePublisher) Publish(msg *MergeMaps_Response) error {
	return p.Publisher.Publish(msg)
}

// MergeMaps_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type MergeMaps_ResponseSubscription struct {
	*rclgo.Subscription
}

// MergeMaps_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a MergeMaps_ResponseSubscription.
type MergeMaps_ResponseSubscriptionCallback func(msg *MergeMaps_Response, info *rclgo.MessageInfo, err error)

// NewMergeMaps_ResponseSubscription creates and returns a new subscription for the
// MergeMaps_Response
func NewMergeMaps_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback MergeMaps_ResponseSubscriptionCallback) (*MergeMaps_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg MergeMaps_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, MergeMaps_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &MergeMaps_ResponseSubscription{sub}, nil
}

func (s *MergeMaps_ResponseSubscription) TakeMessage(out *MergeMaps_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneMergeMaps_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMergeMaps_ResponseSlice(dst, src []MergeMaps_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MergeMaps_ResponseTypeSupport types.MessageTypeSupport = _MergeMaps_ResponseTypeSupport{}

type _MergeMaps_ResponseTypeSupport struct{}

func (t _MergeMaps_ResponseTypeSupport) New() types.Message {
	return NewMergeMaps_Response()
}

func (t _MergeMaps_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.slam_toolbox__srv__MergeMaps_Response
	return (unsafe.Pointer)(C.slam_toolbox__srv__MergeMaps_Response__create())
}

func (t _MergeMaps_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.slam_toolbox__srv__MergeMaps_Response__destroy((*C.slam_toolbox__srv__MergeMaps_Response)(pointer_to_free))
}

func (t _MergeMaps_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _MergeMaps_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _MergeMaps_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__slam_toolbox__srv__MergeMaps_Response())
}

type CMergeMaps_Response = C.slam_toolbox__srv__MergeMaps_Response
type CMergeMaps_Response__Sequence = C.slam_toolbox__srv__MergeMaps_Response__Sequence

func MergeMaps_Response__Sequence_to_Go(goSlice *[]MergeMaps_Response, cSlice CMergeMaps_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MergeMaps_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		MergeMaps_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func MergeMaps_Response__Sequence_to_C(cSlice *CMergeMaps_Response__Sequence, goSlice []MergeMaps_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.slam_toolbox__srv__MergeMaps_Response)(C.malloc(C.sizeof_struct_slam_toolbox__srv__MergeMaps_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		MergeMaps_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func MergeMaps_Response__Array_to_Go(goSlice []MergeMaps_Response, cSlice []CMergeMaps_Response) {
	for i := 0; i < len(cSlice); i++ {
		MergeMaps_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MergeMaps_Response__Array_to_C(cSlice []CMergeMaps_Response, goSlice []MergeMaps_Response) {
	for i := 0; i < len(goSlice); i++ {
		MergeMaps_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
