// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <realsense2_camera_msgs/srv/application_config_write.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("realsense2_camera_msgs/ApplicationConfigWrite", ApplicationConfigWriteTypeSupport)
	typemap.RegisterService("realsense2_camera_msgs/srv/ApplicationConfigWrite", ApplicationConfigWriteTypeSupport)
}

type _ApplicationConfigWriteTypeSupport struct {}

func (s _ApplicationConfigWriteTypeSupport) Request() types.MessageTypeSupport {
	return ApplicationConfigWrite_RequestTypeSupport
}

func (s _ApplicationConfigWriteTypeSupport) Response() types.MessageTypeSupport {
	return ApplicationConfigWrite_ResponseTypeSupport
}

func (s _ApplicationConfigWriteTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__realsense2_camera_msgs__srv__ApplicationConfigWrite())
}

// Modifying this variable is undefined behavior.
var ApplicationConfigWriteTypeSupport types.ServiceTypeSupport = _ApplicationConfigWriteTypeSupport{}

// ApplicationConfigWriteClient wraps rclgo.Client to provide type safe helper
// functions
type ApplicationConfigWriteClient struct {
	*rclgo.Client
}

// NewApplicationConfigWriteClient creates and returns a new client for the
// ApplicationConfigWrite
func NewApplicationConfigWriteClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ApplicationConfigWriteClient, error) {
	client, err := node.NewClient(serviceName, ApplicationConfigWriteTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ApplicationConfigWriteClient{client}, nil
}

func (s *ApplicationConfigWriteClient) Send(ctx context.Context, req *ApplicationConfigWrite_Request) (*ApplicationConfigWrite_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ApplicationConfigWrite_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ApplicationConfigWriteServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ApplicationConfigWriteServiceResponseSender) SendResponse(resp *ApplicationConfigWrite_Response) error {
	return s.sender.SendResponse(resp)
}

type ApplicationConfigWriteServiceRequestHandler func(*rclgo.ServiceInfo, *ApplicationConfigWrite_Request, ApplicationConfigWriteServiceResponseSender)

// ApplicationConfigWriteService wraps rclgo.Service to provide type safe helper
// functions
type ApplicationConfigWriteService struct {
	*rclgo.Service
}

// NewApplicationConfigWriteService creates and returns a new service for the
// ApplicationConfigWrite
func NewApplicationConfigWriteService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ApplicationConfigWriteServiceRequestHandler) (*ApplicationConfigWriteService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ApplicationConfigWrite_Request)
		responseSender := ApplicationConfigWriteServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ApplicationConfigWriteTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ApplicationConfigWriteService{service}, nil
}