// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <realsense2_camera_msgs/srv/calib_config_read.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("realsense2_camera_msgs/CalibConfigRead_Response", CalibConfigRead_ResponseTypeSupport)
	typemap.RegisterMessage("realsense2_camera_msgs/srv/CalibConfigRead_Response", CalibConfigRead_ResponseTypeSupport)
}

type CalibConfigRead_Response struct {
	Success bool `yaml:"success"`
	ErrorMessage string `yaml:"error_message"`
	CalibConfig string `yaml:"calib_config"`
}

// NewCalibConfigRead_Response creates a new CalibConfigRead_Response with default values.
func NewCalibConfigRead_Response() *CalibConfigRead_Response {
	self := CalibConfigRead_Response{}
	self.SetDefaults()
	return &self
}

func (t *CalibConfigRead_Response) Clone() *CalibConfigRead_Response {
	c := &CalibConfigRead_Response{}
	c.Success = t.Success
	c.ErrorMessage = t.ErrorMessage
	c.CalibConfig = t.CalibConfig
	return c
}

func (t *CalibConfigRead_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *CalibConfigRead_Response) SetDefaults() {
	t.Success = false
	t.ErrorMessage = ""
	t.CalibConfig = ""
}

func (t *CalibConfigRead_Response) GetTypeSupport() types.MessageTypeSupport {
	return CalibConfigRead_ResponseTypeSupport
}

// CalibConfigRead_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type CalibConfigRead_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewCalibConfigRead_ResponsePublisher creates and returns a new publisher for the
// CalibConfigRead_Response
func NewCalibConfigRead_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*CalibConfigRead_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, CalibConfigRead_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &CalibConfigRead_ResponsePublisher{pub}, nil
}

func (p *CalibConfigRead_ResponsePublisher) Publish(msg *CalibConfigRead_Response) error {
	return p.Publisher.Publish(msg)
}

// CalibConfigRead_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type CalibConfigRead_ResponseSubscription struct {
	*rclgo.Subscription
}

// CalibConfigRead_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a CalibConfigRead_ResponseSubscription.
type CalibConfigRead_ResponseSubscriptionCallback func(msg *CalibConfigRead_Response, info *rclgo.MessageInfo, err error)

// NewCalibConfigRead_ResponseSubscription creates and returns a new subscription for the
// CalibConfigRead_Response
func NewCalibConfigRead_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback CalibConfigRead_ResponseSubscriptionCallback) (*CalibConfigRead_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg CalibConfigRead_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, CalibConfigRead_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &CalibConfigRead_ResponseSubscription{sub}, nil
}

func (s *CalibConfigRead_ResponseSubscription) TakeMessage(out *CalibConfigRead_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneCalibConfigRead_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneCalibConfigRead_ResponseSlice(dst, src []CalibConfigRead_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var CalibConfigRead_ResponseTypeSupport types.MessageTypeSupport = _CalibConfigRead_ResponseTypeSupport{}

type _CalibConfigRead_ResponseTypeSupport struct{}

func (t _CalibConfigRead_ResponseTypeSupport) New() types.Message {
	return NewCalibConfigRead_Response()
}

func (t _CalibConfigRead_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.realsense2_camera_msgs__srv__CalibConfigRead_Response
	return (unsafe.Pointer)(C.realsense2_camera_msgs__srv__CalibConfigRead_Response__create())
}

func (t _CalibConfigRead_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.realsense2_camera_msgs__srv__CalibConfigRead_Response__destroy((*C.realsense2_camera_msgs__srv__CalibConfigRead_Response)(pointer_to_free))
}

func (t _CalibConfigRead_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*CalibConfigRead_Response)
	mem := (*C.realsense2_camera_msgs__srv__CalibConfigRead_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.error_message), m.ErrorMessage)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.calib_config), m.CalibConfig)
}

func (t _CalibConfigRead_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*CalibConfigRead_Response)
	mem := (*C.realsense2_camera_msgs__srv__CalibConfigRead_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.ErrorMessage, unsafe.Pointer(&mem.error_message))
	primitives.StringAsGoStruct(&m.CalibConfig, unsafe.Pointer(&mem.calib_config))
}

func (t _CalibConfigRead_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__realsense2_camera_msgs__srv__CalibConfigRead_Response())
}

type CCalibConfigRead_Response = C.realsense2_camera_msgs__srv__CalibConfigRead_Response
type CCalibConfigRead_Response__Sequence = C.realsense2_camera_msgs__srv__CalibConfigRead_Response__Sequence

func CalibConfigRead_Response__Sequence_to_Go(goSlice *[]CalibConfigRead_Response, cSlice CCalibConfigRead_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]CalibConfigRead_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		CalibConfigRead_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func CalibConfigRead_Response__Sequence_to_C(cSlice *CCalibConfigRead_Response__Sequence, goSlice []CalibConfigRead_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.realsense2_camera_msgs__srv__CalibConfigRead_Response)(C.malloc(C.sizeof_struct_realsense2_camera_msgs__srv__CalibConfigRead_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		CalibConfigRead_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func CalibConfigRead_Response__Array_to_Go(goSlice []CalibConfigRead_Response, cSlice []CCalibConfigRead_Response) {
	for i := 0; i < len(cSlice); i++ {
		CalibConfigRead_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func CalibConfigRead_Response__Array_to_C(cSlice []CCalibConfigRead_Response, goSlice []CalibConfigRead_Response) {
	for i := 0; i < len(goSlice); i++ {
		CalibConfigRead_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
