// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <realsense2_camera_msgs/srv/device_info.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("realsense2_camera_msgs/DeviceInfo", DeviceInfoTypeSupport)
	typemap.RegisterService("realsense2_camera_msgs/srv/DeviceInfo", DeviceInfoTypeSupport)
}

type _DeviceInfoTypeSupport struct {}

func (s _DeviceInfoTypeSupport) Request() types.MessageTypeSupport {
	return DeviceInfo_RequestTypeSupport
}

func (s _DeviceInfoTypeSupport) Response() types.MessageTypeSupport {
	return DeviceInfo_ResponseTypeSupport
}

func (s _DeviceInfoTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__realsense2_camera_msgs__srv__DeviceInfo())
}

// Modifying this variable is undefined behavior.
var DeviceInfoTypeSupport types.ServiceTypeSupport = _DeviceInfoTypeSupport{}

// DeviceInfoClient wraps rclgo.Client to provide type safe helper
// functions
type DeviceInfoClient struct {
	*rclgo.Client
}

// NewDeviceInfoClient creates and returns a new client for the
// DeviceInfo
func NewDeviceInfoClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*DeviceInfoClient, error) {
	client, err := node.NewClient(serviceName, DeviceInfoTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DeviceInfoClient{client}, nil
}

func (s *DeviceInfoClient) Send(ctx context.Context, req *DeviceInfo_Request) (*DeviceInfo_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*DeviceInfo_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type DeviceInfoServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s DeviceInfoServiceResponseSender) SendResponse(resp *DeviceInfo_Response) error {
	return s.sender.SendResponse(resp)
}

type DeviceInfoServiceRequestHandler func(*rclgo.ServiceInfo, *DeviceInfo_Request, DeviceInfoServiceResponseSender)

// DeviceInfoService wraps rclgo.Service to provide type safe helper
// functions
type DeviceInfoService struct {
	*rclgo.Service
}

// NewDeviceInfoService creates and returns a new service for the
// DeviceInfo
func NewDeviceInfoService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler DeviceInfoServiceRequestHandler) (*DeviceInfoService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*DeviceInfo_Request)
		responseSender := DeviceInfoServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, DeviceInfoTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &DeviceInfoService{service}, nil
}