// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <realsense2_camera_msgs/srv/safety_interface_config_write.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("realsense2_camera_msgs/SafetyInterfaceConfigWrite", SafetyInterfaceConfigWriteTypeSupport)
	typemap.RegisterService("realsense2_camera_msgs/srv/SafetyInterfaceConfigWrite", SafetyInterfaceConfigWriteTypeSupport)
}

type _SafetyInterfaceConfigWriteTypeSupport struct {}

func (s _SafetyInterfaceConfigWriteTypeSupport) Request() types.MessageTypeSupport {
	return SafetyInterfaceConfigWrite_RequestTypeSupport
}

func (s _SafetyInterfaceConfigWriteTypeSupport) Response() types.MessageTypeSupport {
	return SafetyInterfaceConfigWrite_ResponseTypeSupport
}

func (s _SafetyInterfaceConfigWriteTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__realsense2_camera_msgs__srv__SafetyInterfaceConfigWrite())
}

// Modifying this variable is undefined behavior.
var SafetyInterfaceConfigWriteTypeSupport types.ServiceTypeSupport = _SafetyInterfaceConfigWriteTypeSupport{}

// SafetyInterfaceConfigWriteClient wraps rclgo.Client to provide type safe helper
// functions
type SafetyInterfaceConfigWriteClient struct {
	*rclgo.Client
}

// NewSafetyInterfaceConfigWriteClient creates and returns a new client for the
// SafetyInterfaceConfigWrite
func NewSafetyInterfaceConfigWriteClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SafetyInterfaceConfigWriteClient, error) {
	client, err := node.NewClient(serviceName, SafetyInterfaceConfigWriteTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SafetyInterfaceConfigWriteClient{client}, nil
}

func (s *SafetyInterfaceConfigWriteClient) Send(ctx context.Context, req *SafetyInterfaceConfigWrite_Request) (*SafetyInterfaceConfigWrite_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SafetyInterfaceConfigWrite_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SafetyInterfaceConfigWriteServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SafetyInterfaceConfigWriteServiceResponseSender) SendResponse(resp *SafetyInterfaceConfigWrite_Response) error {
	return s.sender.SendResponse(resp)
}

type SafetyInterfaceConfigWriteServiceRequestHandler func(*rclgo.ServiceInfo, *SafetyInterfaceConfigWrite_Request, SafetyInterfaceConfigWriteServiceResponseSender)

// SafetyInterfaceConfigWriteService wraps rclgo.Service to provide type safe helper
// functions
type SafetyInterfaceConfigWriteService struct {
	*rclgo.Service
}

// NewSafetyInterfaceConfigWriteService creates and returns a new service for the
// SafetyInterfaceConfigWrite
func NewSafetyInterfaceConfigWriteService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SafetyInterfaceConfigWriteServiceRequestHandler) (*SafetyInterfaceConfigWriteService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*SafetyInterfaceConfigWrite_Request)
		responseSender := SafetyInterfaceConfigWriteServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SafetyInterfaceConfigWriteTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SafetyInterfaceConfigWriteService{service}, nil
}