// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <realsense2_camera_msgs/srv/safety_preset_write.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("realsense2_camera_msgs/SafetyPresetWrite_Response", SafetyPresetWrite_ResponseTypeSupport)
	typemap.RegisterMessage("realsense2_camera_msgs/srv/SafetyPresetWrite_Response", SafetyPresetWrite_ResponseTypeSupport)
}

type SafetyPresetWrite_Response struct {
	Success bool `yaml:"success"`
	ErrorMessage string `yaml:"error_message"`
}

// NewSafetyPresetWrite_Response creates a new SafetyPresetWrite_Response with default values.
func NewSafetyPresetWrite_Response() *SafetyPresetWrite_Response {
	self := SafetyPresetWrite_Response{}
	self.SetDefaults()
	return &self
}

func (t *SafetyPresetWrite_Response) Clone() *SafetyPresetWrite_Response {
	c := &SafetyPresetWrite_Response{}
	c.Success = t.Success
	c.ErrorMessage = t.ErrorMessage
	return c
}

func (t *SafetyPresetWrite_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SafetyPresetWrite_Response) SetDefaults() {
	t.Success = false
	t.ErrorMessage = ""
}

func (t *SafetyPresetWrite_Response) GetTypeSupport() types.MessageTypeSupport {
	return SafetyPresetWrite_ResponseTypeSupport
}

// SafetyPresetWrite_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SafetyPresetWrite_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewSafetyPresetWrite_ResponsePublisher creates and returns a new publisher for the
// SafetyPresetWrite_Response
func NewSafetyPresetWrite_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SafetyPresetWrite_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, SafetyPresetWrite_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SafetyPresetWrite_ResponsePublisher{pub}, nil
}

func (p *SafetyPresetWrite_ResponsePublisher) Publish(msg *SafetyPresetWrite_Response) error {
	return p.Publisher.Publish(msg)
}

// SafetyPresetWrite_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SafetyPresetWrite_ResponseSubscription struct {
	*rclgo.Subscription
}

// SafetyPresetWrite_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SafetyPresetWrite_ResponseSubscription.
type SafetyPresetWrite_ResponseSubscriptionCallback func(msg *SafetyPresetWrite_Response, info *rclgo.MessageInfo, err error)

// NewSafetyPresetWrite_ResponseSubscription creates and returns a new subscription for the
// SafetyPresetWrite_Response
func NewSafetyPresetWrite_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SafetyPresetWrite_ResponseSubscriptionCallback) (*SafetyPresetWrite_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SafetyPresetWrite_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SafetyPresetWrite_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SafetyPresetWrite_ResponseSubscription{sub}, nil
}

func (s *SafetyPresetWrite_ResponseSubscription) TakeMessage(out *SafetyPresetWrite_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSafetyPresetWrite_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSafetyPresetWrite_ResponseSlice(dst, src []SafetyPresetWrite_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SafetyPresetWrite_ResponseTypeSupport types.MessageTypeSupport = _SafetyPresetWrite_ResponseTypeSupport{}

type _SafetyPresetWrite_ResponseTypeSupport struct{}

func (t _SafetyPresetWrite_ResponseTypeSupport) New() types.Message {
	return NewSafetyPresetWrite_Response()
}

func (t _SafetyPresetWrite_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response
	return (unsafe.Pointer)(C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response__create())
}

func (t _SafetyPresetWrite_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response__destroy((*C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response)(pointer_to_free))
}

func (t _SafetyPresetWrite_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SafetyPresetWrite_Response)
	mem := (*C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.error_message), m.ErrorMessage)
}

func (t _SafetyPresetWrite_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SafetyPresetWrite_Response)
	mem := (*C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.ErrorMessage, unsafe.Pointer(&mem.error_message))
}

func (t _SafetyPresetWrite_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__realsense2_camera_msgs__srv__SafetyPresetWrite_Response())
}

type CSafetyPresetWrite_Response = C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response
type CSafetyPresetWrite_Response__Sequence = C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response__Sequence

func SafetyPresetWrite_Response__Sequence_to_Go(goSlice *[]SafetyPresetWrite_Response, cSlice CSafetyPresetWrite_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SafetyPresetWrite_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SafetyPresetWrite_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SafetyPresetWrite_Response__Sequence_to_C(cSlice *CSafetyPresetWrite_Response__Sequence, goSlice []SafetyPresetWrite_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.realsense2_camera_msgs__srv__SafetyPresetWrite_Response)(C.malloc(C.sizeof_struct_realsense2_camera_msgs__srv__SafetyPresetWrite_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SafetyPresetWrite_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SafetyPresetWrite_Response__Array_to_Go(goSlice []SafetyPresetWrite_Response, cSlice []CSafetyPresetWrite_Response) {
	for i := 0; i < len(cSlice); i++ {
		SafetyPresetWrite_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SafetyPresetWrite_Response__Array_to_C(cSlice []CSafetyPresetWrite_Response, goSlice []SafetyPresetWrite_Response) {
	for i := 0; i < len(goSlice); i++ {
		SafetyPresetWrite_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
