// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <realsense2_camera_msgs/srv/safety_preset_read.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("realsense2_camera_msgs/SafetyPresetRead_Response", SafetyPresetRead_ResponseTypeSupport)
	typemap.RegisterMessage("realsense2_camera_msgs/srv/SafetyPresetRead_Response", SafetyPresetRead_ResponseTypeSupport)
}

type SafetyPresetRead_Response struct {
	Success bool `yaml:"success"`
	ErrorMessage string `yaml:"error_message"`
	SafetyPreset string `yaml:"safety_preset"`
}

// NewSafetyPresetRead_Response creates a new SafetyPresetRead_Response with default values.
func NewSafetyPresetRead_Response() *SafetyPresetRead_Response {
	self := SafetyPresetRead_Response{}
	self.SetDefaults()
	return &self
}

func (t *SafetyPresetRead_Response) Clone() *SafetyPresetRead_Response {
	c := &SafetyPresetRead_Response{}
	c.Success = t.Success
	c.ErrorMessage = t.ErrorMessage
	c.SafetyPreset = t.SafetyPreset
	return c
}

func (t *SafetyPresetRead_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SafetyPresetRead_Response) SetDefaults() {
	t.Success = false
	t.ErrorMessage = ""
	t.SafetyPreset = ""
}

func (t *SafetyPresetRead_Response) GetTypeSupport() types.MessageTypeSupport {
	return SafetyPresetRead_ResponseTypeSupport
}

// SafetyPresetRead_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SafetyPresetRead_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewSafetyPresetRead_ResponsePublisher creates and returns a new publisher for the
// SafetyPresetRead_Response
func NewSafetyPresetRead_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SafetyPresetRead_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, SafetyPresetRead_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SafetyPresetRead_ResponsePublisher{pub}, nil
}

func (p *SafetyPresetRead_ResponsePublisher) Publish(msg *SafetyPresetRead_Response) error {
	return p.Publisher.Publish(msg)
}

// SafetyPresetRead_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SafetyPresetRead_ResponseSubscription struct {
	*rclgo.Subscription
}

// SafetyPresetRead_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SafetyPresetRead_ResponseSubscription.
type SafetyPresetRead_ResponseSubscriptionCallback func(msg *SafetyPresetRead_Response, info *rclgo.MessageInfo, err error)

// NewSafetyPresetRead_ResponseSubscription creates and returns a new subscription for the
// SafetyPresetRead_Response
func NewSafetyPresetRead_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SafetyPresetRead_ResponseSubscriptionCallback) (*SafetyPresetRead_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SafetyPresetRead_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SafetyPresetRead_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SafetyPresetRead_ResponseSubscription{sub}, nil
}

func (s *SafetyPresetRead_ResponseSubscription) TakeMessage(out *SafetyPresetRead_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSafetyPresetRead_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSafetyPresetRead_ResponseSlice(dst, src []SafetyPresetRead_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SafetyPresetRead_ResponseTypeSupport types.MessageTypeSupport = _SafetyPresetRead_ResponseTypeSupport{}

type _SafetyPresetRead_ResponseTypeSupport struct{}

func (t _SafetyPresetRead_ResponseTypeSupport) New() types.Message {
	return NewSafetyPresetRead_Response()
}

func (t _SafetyPresetRead_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.realsense2_camera_msgs__srv__SafetyPresetRead_Response
	return (unsafe.Pointer)(C.realsense2_camera_msgs__srv__SafetyPresetRead_Response__create())
}

func (t _SafetyPresetRead_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.realsense2_camera_msgs__srv__SafetyPresetRead_Response__destroy((*C.realsense2_camera_msgs__srv__SafetyPresetRead_Response)(pointer_to_free))
}

func (t _SafetyPresetRead_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SafetyPresetRead_Response)
	mem := (*C.realsense2_camera_msgs__srv__SafetyPresetRead_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.error_message), m.ErrorMessage)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.safety_preset), m.SafetyPreset)
}

func (t _SafetyPresetRead_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SafetyPresetRead_Response)
	mem := (*C.realsense2_camera_msgs__srv__SafetyPresetRead_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.ErrorMessage, unsafe.Pointer(&mem.error_message))
	primitives.StringAsGoStruct(&m.SafetyPreset, unsafe.Pointer(&mem.safety_preset))
}

func (t _SafetyPresetRead_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__realsense2_camera_msgs__srv__SafetyPresetRead_Response())
}

type CSafetyPresetRead_Response = C.realsense2_camera_msgs__srv__SafetyPresetRead_Response
type CSafetyPresetRead_Response__Sequence = C.realsense2_camera_msgs__srv__SafetyPresetRead_Response__Sequence

func SafetyPresetRead_Response__Sequence_to_Go(goSlice *[]SafetyPresetRead_Response, cSlice CSafetyPresetRead_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SafetyPresetRead_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SafetyPresetRead_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SafetyPresetRead_Response__Sequence_to_C(cSlice *CSafetyPresetRead_Response__Sequence, goSlice []SafetyPresetRead_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.realsense2_camera_msgs__srv__SafetyPresetRead_Response)(C.malloc(C.sizeof_struct_realsense2_camera_msgs__srv__SafetyPresetRead_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SafetyPresetRead_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SafetyPresetRead_Response__Array_to_Go(goSlice []SafetyPresetRead_Response, cSlice []CSafetyPresetRead_Response) {
	for i := 0; i < len(cSlice); i++ {
		SafetyPresetRead_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SafetyPresetRead_Response__Array_to_C(cSlice []CSafetyPresetRead_Response, goSlice []SafetyPresetRead_Response) {
	for i := 0; i < len(goSlice); i++ {
		SafetyPresetRead_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
