// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <realsense2_camera_msgs/srv/safety_preset_read.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("realsense2_camera_msgs/SafetyPresetRead", SafetyPresetReadTypeSupport)
	typemap.RegisterService("realsense2_camera_msgs/srv/SafetyPresetRead", SafetyPresetReadTypeSupport)
}

type _SafetyPresetReadTypeSupport struct {}

func (s _SafetyPresetReadTypeSupport) Request() types.MessageTypeSupport {
	return SafetyPresetRead_RequestTypeSupport
}

func (s _SafetyPresetReadTypeSupport) Response() types.MessageTypeSupport {
	return SafetyPresetRead_ResponseTypeSupport
}

func (s _SafetyPresetReadTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__realsense2_camera_msgs__srv__SafetyPresetRead())
}

// Modifying this variable is undefined behavior.
var SafetyPresetReadTypeSupport types.ServiceTypeSupport = _SafetyPresetReadTypeSupport{}

// SafetyPresetReadClient wraps rclgo.Client to provide type safe helper
// functions
type SafetyPresetReadClient struct {
	*rclgo.Client
}

// NewSafetyPresetReadClient creates and returns a new client for the
// SafetyPresetRead
func NewSafetyPresetReadClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SafetyPresetReadClient, error) {
	client, err := node.NewClient(serviceName, SafetyPresetReadTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SafetyPresetReadClient{client}, nil
}

func (s *SafetyPresetReadClient) Send(ctx context.Context, req *SafetyPresetRead_Request) (*SafetyPresetRead_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SafetyPresetRead_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SafetyPresetReadServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SafetyPresetReadServiceResponseSender) SendResponse(resp *SafetyPresetRead_Response) error {
	return s.sender.SendResponse(resp)
}

type SafetyPresetReadServiceRequestHandler func(*rclgo.ServiceInfo, *SafetyPresetRead_Request, SafetyPresetReadServiceResponseSender)

// SafetyPresetReadService wraps rclgo.Service to provide type safe helper
// functions
type SafetyPresetReadService struct {
	*rclgo.Service
}

// NewSafetyPresetReadService creates and returns a new service for the
// SafetyPresetRead
func NewSafetyPresetReadService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SafetyPresetReadServiceRequestHandler) (*SafetyPresetReadService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*SafetyPresetRead_Request)
		responseSender := SafetyPresetReadServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SafetyPresetReadTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SafetyPresetReadService{service}, nil
}