// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <realsense2_camera_msgs/srv/safety_preset_write.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("realsense2_camera_msgs/SafetyPresetWrite_Request", SafetyPresetWrite_RequestTypeSupport)
	typemap.RegisterMessage("realsense2_camera_msgs/srv/SafetyPresetWrite_Request", SafetyPresetWrite_RequestTypeSupport)
}

type SafetyPresetWrite_Request struct {
	SafetyPreset string `yaml:"safety_preset"`
	Index uint8 `yaml:"index"`
}

// NewSafetyPresetWrite_Request creates a new SafetyPresetWrite_Request with default values.
func NewSafetyPresetWrite_Request() *SafetyPresetWrite_Request {
	self := SafetyPresetWrite_Request{}
	self.SetDefaults()
	return &self
}

func (t *SafetyPresetWrite_Request) Clone() *SafetyPresetWrite_Request {
	c := &SafetyPresetWrite_Request{}
	c.SafetyPreset = t.SafetyPreset
	c.Index = t.Index
	return c
}

func (t *SafetyPresetWrite_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SafetyPresetWrite_Request) SetDefaults() {
	t.SafetyPreset = ""
	t.Index = 0
}

func (t *SafetyPresetWrite_Request) GetTypeSupport() types.MessageTypeSupport {
	return SafetyPresetWrite_RequestTypeSupport
}

// SafetyPresetWrite_RequestPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type SafetyPresetWrite_RequestPublisher struct {
	*rclgo.Publisher
}

// NewSafetyPresetWrite_RequestPublisher creates and returns a new publisher for the
// SafetyPresetWrite_Request
func NewSafetyPresetWrite_RequestPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*SafetyPresetWrite_RequestPublisher, error) {
	pub, err := node.NewPublisher(topic_name, SafetyPresetWrite_RequestTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SafetyPresetWrite_RequestPublisher{pub}, nil
}

func (p *SafetyPresetWrite_RequestPublisher) Publish(msg *SafetyPresetWrite_Request) error {
	return p.Publisher.Publish(msg)
}

// SafetyPresetWrite_RequestSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type SafetyPresetWrite_RequestSubscription struct {
	*rclgo.Subscription
}

// SafetyPresetWrite_RequestSubscriptionCallback type is used to provide a subscription
// handler function for a SafetyPresetWrite_RequestSubscription.
type SafetyPresetWrite_RequestSubscriptionCallback func(msg *SafetyPresetWrite_Request, info *rclgo.MessageInfo, err error)

// NewSafetyPresetWrite_RequestSubscription creates and returns a new subscription for the
// SafetyPresetWrite_Request
func NewSafetyPresetWrite_RequestSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback SafetyPresetWrite_RequestSubscriptionCallback) (*SafetyPresetWrite_RequestSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg SafetyPresetWrite_Request
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, SafetyPresetWrite_RequestTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SafetyPresetWrite_RequestSubscription{sub}, nil
}

func (s *SafetyPresetWrite_RequestSubscription) TakeMessage(out *SafetyPresetWrite_Request) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSafetyPresetWrite_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSafetyPresetWrite_RequestSlice(dst, src []SafetyPresetWrite_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SafetyPresetWrite_RequestTypeSupport types.MessageTypeSupport = _SafetyPresetWrite_RequestTypeSupport{}

type _SafetyPresetWrite_RequestTypeSupport struct{}

func (t _SafetyPresetWrite_RequestTypeSupport) New() types.Message {
	return NewSafetyPresetWrite_Request()
}

func (t _SafetyPresetWrite_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request
	return (unsafe.Pointer)(C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request__create())
}

func (t _SafetyPresetWrite_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request__destroy((*C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request)(pointer_to_free))
}

func (t _SafetyPresetWrite_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SafetyPresetWrite_Request)
	mem := (*C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.safety_preset), m.SafetyPreset)
	mem.index = C.uint8_t(m.Index)
}

func (t _SafetyPresetWrite_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SafetyPresetWrite_Request)
	mem := (*C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.SafetyPreset, unsafe.Pointer(&mem.safety_preset))
	m.Index = uint8(mem.index)
}

func (t _SafetyPresetWrite_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__realsense2_camera_msgs__srv__SafetyPresetWrite_Request())
}

type CSafetyPresetWrite_Request = C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request
type CSafetyPresetWrite_Request__Sequence = C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request__Sequence

func SafetyPresetWrite_Request__Sequence_to_Go(goSlice *[]SafetyPresetWrite_Request, cSlice CSafetyPresetWrite_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SafetyPresetWrite_Request, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SafetyPresetWrite_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func SafetyPresetWrite_Request__Sequence_to_C(cSlice *CSafetyPresetWrite_Request__Sequence, goSlice []SafetyPresetWrite_Request) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.realsense2_camera_msgs__srv__SafetyPresetWrite_Request)(C.malloc(C.sizeof_struct_realsense2_camera_msgs__srv__SafetyPresetWrite_Request * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SafetyPresetWrite_RequestTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func SafetyPresetWrite_Request__Array_to_Go(goSlice []SafetyPresetWrite_Request, cSlice []CSafetyPresetWrite_Request) {
	for i := 0; i < len(cSlice); i++ {
		SafetyPresetWrite_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SafetyPresetWrite_Request__Array_to_C(cSlice []CSafetyPresetWrite_Request, goSlice []SafetyPresetWrite_Request) {
	for i := 0; i < len(goSlice); i++ {
		SafetyPresetWrite_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
