// Code generated by rclgo-gen. DO NOT EDIT.

package grid_map_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <grid_map_msgs/srv/get_grid_map.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("grid_map_msgs/GetGridMap", GetGridMapTypeSupport)
	typemap.RegisterService("grid_map_msgs/srv/GetGridMap", GetGridMapTypeSupport)
}

type _GetGridMapTypeSupport struct {}

func (s _GetGridMapTypeSupport) Request() types.MessageTypeSupport {
	return GetGridMap_RequestTypeSupport
}

func (s _GetGridMapTypeSupport) Response() types.MessageTypeSupport {
	return GetGridMap_ResponseTypeSupport
}

func (s _GetGridMapTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__grid_map_msgs__srv__GetGridMap())
}

// Modifying this variable is undefined behavior.
var GetGridMapTypeSupport types.ServiceTypeSupport = _GetGridMapTypeSupport{}

// GetGridMapClient wraps rclgo.Client to provide type safe helper
// functions
type GetGridMapClient struct {
	*rclgo.Client
}

// NewGetGridMapClient creates and returns a new client for the
// GetGridMap
func NewGetGridMapClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*GetGridMapClient, error) {
	client, err := node.NewClient(serviceName, GetGridMapTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetGridMapClient{client}, nil
}

func (s *GetGridMapClient) Send(ctx context.Context, req *GetGridMap_Request) (*GetGridMap_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetGridMap_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetGridMapServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s GetGridMapServiceResponseSender) SendResponse(resp *GetGridMap_Response) error {
	return s.sender.SendResponse(resp)
}

type GetGridMapServiceRequestHandler func(*rclgo.ServiceInfo, *GetGridMap_Request, GetGridMapServiceResponseSender)

// GetGridMapService wraps rclgo.Service to provide type safe helper
// functions
type GetGridMapService struct {
	*rclgo.Service
}

// NewGetGridMapService creates and returns a new service for the
// GetGridMap
func NewGetGridMapService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler GetGridMapServiceRequestHandler) (*GetGridMapService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*GetGridMap_Request)
		responseSender := GetGridMapServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetGridMapTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetGridMapService{service}, nil
}