// Code generated by rclgo-gen. DO NOT EDIT.

package grid_map_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <grid_map_msgs/srv/set_grid_map.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("grid_map_msgs/SetGridMap", SetGridMapTypeSupport)
	typemap.RegisterService("grid_map_msgs/srv/SetGridMap", SetGridMapTypeSupport)
}

type _SetGridMapTypeSupport struct {}

func (s _SetGridMapTypeSupport) Request() types.MessageTypeSupport {
	return SetGridMap_RequestTypeSupport
}

func (s _SetGridMapTypeSupport) Response() types.MessageTypeSupport {
	return SetGridMap_ResponseTypeSupport
}

func (s _SetGridMapTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__grid_map_msgs__srv__SetGridMap())
}

// Modifying this variable is undefined behavior.
var SetGridMapTypeSupport types.ServiceTypeSupport = _SetGridMapTypeSupport{}

// SetGridMapClient wraps rclgo.Client to provide type safe helper
// functions
type SetGridMapClient struct {
	*rclgo.Client
}

// NewSetGridMapClient creates and returns a new client for the
// SetGridMap
func NewSetGridMapClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*SetGridMapClient, error) {
	client, err := node.NewClient(serviceName, SetGridMapTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetGridMapClient{client}, nil
}

func (s *SetGridMapClient) Send(ctx context.Context, req *SetGridMap_Request) (*SetGridMap_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetGridMap_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetGridMapServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s SetGridMapServiceResponseSender) SendResponse(resp *SetGridMap_Response) error {
	return s.sender.SendResponse(resp)
}

type SetGridMapServiceRequestHandler func(*rclgo.ServiceInfo, *SetGridMap_Request, SetGridMapServiceResponseSender)

// SetGridMapService wraps rclgo.Service to provide type safe helper
// functions
type SetGridMapService struct {
	*rclgo.Service
}

// NewSetGridMapService creates and returns a new service for the
// SetGridMap
func NewSetGridMapService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler SetGridMapServiceRequestHandler) (*SetGridMapService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*SetGridMap_Request)
		responseSender := SetGridMapServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetGridMapTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetGridMapService{service}, nil
}