// Code generated by rclgo-gen. DO NOT EDIT.

package apriltag_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <apriltag_msgs/msg/april_tag_detection.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("apriltag_msgs/AprilTagDetection", AprilTagDetectionTypeSupport)
	typemap.RegisterMessage("apriltag_msgs/msg/AprilTagDetection", AprilTagDetectionTypeSupport)
}

type AprilTagDetection struct {
	Family string `yaml:"family"`
	Id int32 `yaml:"id"`
	Hamming int32 `yaml:"hamming"`
	Goodness float32 `yaml:"goodness"`
	DecisionMargin float32 `yaml:"decision_margin"`
	Centre Point `yaml:"centre"`// centre in (x,y) pixel coordinates
	Corners [4]Point `yaml:"corners"`// corners of tag ((x1,y1),(x2,y2),...)
	Homography [9]float64 `yaml:"homography"`// 3x3 row-major homography matrix
}

// NewAprilTagDetection creates a new AprilTagDetection with default values.
func NewAprilTagDetection() *AprilTagDetection {
	self := AprilTagDetection{}
	self.SetDefaults()
	return &self
}

func (t *AprilTagDetection) Clone() *AprilTagDetection {
	c := &AprilTagDetection{}
	c.Family = t.Family
	c.Id = t.Id
	c.Hamming = t.Hamming
	c.Goodness = t.Goodness
	c.DecisionMargin = t.DecisionMargin
	c.Centre = *t.Centre.Clone()
	ClonePointSlice(c.Corners[:], t.Corners[:])
	c.Homography = t.Homography
	return c
}

func (t *AprilTagDetection) CloneMsg() types.Message {
	return t.Clone()
}

func (t *AprilTagDetection) SetDefaults() {
	t.Family = ""
	t.Id = 0
	t.Hamming = 0
	t.Goodness = 0
	t.DecisionMargin = 0
	t.Centre.SetDefaults()
	for i := range t.Corners {
		t.Corners[i].SetDefaults()
	}
	t.Homography = [9]float64{}
}

func (t *AprilTagDetection) GetTypeSupport() types.MessageTypeSupport {
	return AprilTagDetectionTypeSupport
}

// AprilTagDetectionPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type AprilTagDetectionPublisher struct {
	*rclgo.Publisher
}

// NewAprilTagDetectionPublisher creates and returns a new publisher for the
// AprilTagDetection
func NewAprilTagDetectionPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*AprilTagDetectionPublisher, error) {
	pub, err := node.NewPublisher(topic_name, AprilTagDetectionTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &AprilTagDetectionPublisher{pub}, nil
}

func (p *AprilTagDetectionPublisher) Publish(msg *AprilTagDetection) error {
	return p.Publisher.Publish(msg)
}

// AprilTagDetectionSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type AprilTagDetectionSubscription struct {
	*rclgo.Subscription
}

// AprilTagDetectionSubscriptionCallback type is used to provide a subscription
// handler function for a AprilTagDetectionSubscription.
type AprilTagDetectionSubscriptionCallback func(msg *AprilTagDetection, info *rclgo.MessageInfo, err error)

// NewAprilTagDetectionSubscription creates and returns a new subscription for the
// AprilTagDetection
func NewAprilTagDetectionSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback AprilTagDetectionSubscriptionCallback) (*AprilTagDetectionSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg AprilTagDetection
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, AprilTagDetectionTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &AprilTagDetectionSubscription{sub}, nil
}

func (s *AprilTagDetectionSubscription) TakeMessage(out *AprilTagDetection) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneAprilTagDetectionSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneAprilTagDetectionSlice(dst, src []AprilTagDetection) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var AprilTagDetectionTypeSupport types.MessageTypeSupport = _AprilTagDetectionTypeSupport{}

type _AprilTagDetectionTypeSupport struct{}

func (t _AprilTagDetectionTypeSupport) New() types.Message {
	return NewAprilTagDetection()
}

func (t _AprilTagDetectionTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.apriltag_msgs__msg__AprilTagDetection
	return (unsafe.Pointer)(C.apriltag_msgs__msg__AprilTagDetection__create())
}

func (t _AprilTagDetectionTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.apriltag_msgs__msg__AprilTagDetection__destroy((*C.apriltag_msgs__msg__AprilTagDetection)(pointer_to_free))
}

func (t _AprilTagDetectionTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*AprilTagDetection)
	mem := (*C.apriltag_msgs__msg__AprilTagDetection)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.family), m.Family)
	mem.id = C.int32_t(m.Id)
	mem.hamming = C.int32_t(m.Hamming)
	mem.goodness = C.float(m.Goodness)
	mem.decision_margin = C.float(m.DecisionMargin)
	PointTypeSupport.AsCStruct(unsafe.Pointer(&mem.centre), &m.Centre)
	Point__Array_to_C(mem.corners[:], m.Corners[:])
	cSlice_homography := mem.homography[:]
	primitives.Float64__Array_to_C(*(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_homography)), m.Homography[:])
}

func (t _AprilTagDetectionTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*AprilTagDetection)
	mem := (*C.apriltag_msgs__msg__AprilTagDetection)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Family, unsafe.Pointer(&mem.family))
	m.Id = int32(mem.id)
	m.Hamming = int32(mem.hamming)
	m.Goodness = float32(mem.goodness)
	m.DecisionMargin = float32(mem.decision_margin)
	PointTypeSupport.AsGoStruct(&m.Centre, unsafe.Pointer(&mem.centre))
	Point__Array_to_Go(m.Corners[:], mem.corners[:])
	cSlice_homography := mem.homography[:]
	primitives.Float64__Array_to_Go(m.Homography[:], *(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_homography)))
}

func (t _AprilTagDetectionTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__apriltag_msgs__msg__AprilTagDetection())
}

type CAprilTagDetection = C.apriltag_msgs__msg__AprilTagDetection
type CAprilTagDetection__Sequence = C.apriltag_msgs__msg__AprilTagDetection__Sequence

func AprilTagDetection__Sequence_to_Go(goSlice *[]AprilTagDetection, cSlice CAprilTagDetection__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]AprilTagDetection, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		AprilTagDetectionTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func AprilTagDetection__Sequence_to_C(cSlice *CAprilTagDetection__Sequence, goSlice []AprilTagDetection) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.apriltag_msgs__msg__AprilTagDetection)(C.malloc(C.sizeof_struct_apriltag_msgs__msg__AprilTagDetection * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		AprilTagDetectionTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func AprilTagDetection__Array_to_Go(goSlice []AprilTagDetection, cSlice []CAprilTagDetection) {
	for i := 0; i < len(cSlice); i++ {
		AprilTagDetectionTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func AprilTagDetection__Array_to_C(cSlice []CAprilTagDetection, goSlice []AprilTagDetection) {
	for i := 0; i < len(goSlice); i++ {
		AprilTagDetectionTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
