// Code generated by rclgo-gen. DO NOT EDIT.

package dwb_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	dwb_msgs_msg "dog-stream-gateway/internal/msgs/dwb_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <dwb_msgs/srv/get_critic_score.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("dwb_msgs/GetCriticScore_Response", GetCriticScore_ResponseTypeSupport)
	typemap.RegisterMessage("dwb_msgs/srv/GetCriticScore_Response", GetCriticScore_ResponseTypeSupport)
}

type GetCriticScore_Response struct {
	Score dwb_msgs_msg.CriticScore `yaml:"score"`
}

// NewGetCriticScore_Response creates a new GetCriticScore_Response with default values.
func NewGetCriticScore_Response() *GetCriticScore_Response {
	self := GetCriticScore_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetCriticScore_Response) Clone() *GetCriticScore_Response {
	c := &GetCriticScore_Response{}
	c.Score = *t.Score.Clone()
	return c
}

func (t *GetCriticScore_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetCriticScore_Response) SetDefaults() {
	t.Score.SetDefaults()
}

func (t *GetCriticScore_Response) GetTypeSupport() types.MessageTypeSupport {
	return GetCriticScore_ResponseTypeSupport
}

// GetCriticScore_ResponsePublisher wraps rclgo.Publisher to provide type safe helper
// functions
type GetCriticScore_ResponsePublisher struct {
	*rclgo.Publisher
}

// NewGetCriticScore_ResponsePublisher creates and returns a new publisher for the
// GetCriticScore_Response
func NewGetCriticScore_ResponsePublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*GetCriticScore_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topic_name, GetCriticScore_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetCriticScore_ResponsePublisher{pub}, nil
}

func (p *GetCriticScore_ResponsePublisher) Publish(msg *GetCriticScore_Response) error {
	return p.Publisher.Publish(msg)
}

// GetCriticScore_ResponseSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type GetCriticScore_ResponseSubscription struct {
	*rclgo.Subscription
}

// GetCriticScore_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GetCriticScore_ResponseSubscription.
type GetCriticScore_ResponseSubscriptionCallback func(msg *GetCriticScore_Response, info *rclgo.MessageInfo, err error)

// NewGetCriticScore_ResponseSubscription creates and returns a new subscription for the
// GetCriticScore_Response
func NewGetCriticScore_ResponseSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback GetCriticScore_ResponseSubscriptionCallback) (*GetCriticScore_ResponseSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg GetCriticScore_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, GetCriticScore_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GetCriticScore_ResponseSubscription{sub}, nil
}

func (s *GetCriticScore_ResponseSubscription) TakeMessage(out *GetCriticScore_Response) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGetCriticScore_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetCriticScore_ResponseSlice(dst, src []GetCriticScore_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetCriticScore_ResponseTypeSupport types.MessageTypeSupport = _GetCriticScore_ResponseTypeSupport{}

type _GetCriticScore_ResponseTypeSupport struct{}

func (t _GetCriticScore_ResponseTypeSupport) New() types.Message {
	return NewGetCriticScore_Response()
}

func (t _GetCriticScore_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.dwb_msgs__srv__GetCriticScore_Response
	return (unsafe.Pointer)(C.dwb_msgs__srv__GetCriticScore_Response__create())
}

func (t _GetCriticScore_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.dwb_msgs__srv__GetCriticScore_Response__destroy((*C.dwb_msgs__srv__GetCriticScore_Response)(pointer_to_free))
}

func (t _GetCriticScore_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetCriticScore_Response)
	mem := (*C.dwb_msgs__srv__GetCriticScore_Response)(dst)
	dwb_msgs_msg.CriticScoreTypeSupport.AsCStruct(unsafe.Pointer(&mem.score), &m.Score)
}

func (t _GetCriticScore_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetCriticScore_Response)
	mem := (*C.dwb_msgs__srv__GetCriticScore_Response)(ros2_message_buffer)
	dwb_msgs_msg.CriticScoreTypeSupport.AsGoStruct(&m.Score, unsafe.Pointer(&mem.score))
}

func (t _GetCriticScore_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__dwb_msgs__srv__GetCriticScore_Response())
}

type CGetCriticScore_Response = C.dwb_msgs__srv__GetCriticScore_Response
type CGetCriticScore_Response__Sequence = C.dwb_msgs__srv__GetCriticScore_Response__Sequence

func GetCriticScore_Response__Sequence_to_Go(goSlice *[]GetCriticScore_Response, cSlice CGetCriticScore_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetCriticScore_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GetCriticScore_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func GetCriticScore_Response__Sequence_to_C(cSlice *CGetCriticScore_Response__Sequence, goSlice []GetCriticScore_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.dwb_msgs__srv__GetCriticScore_Response)(C.malloc(C.sizeof_struct_dwb_msgs__srv__GetCriticScore_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GetCriticScore_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func GetCriticScore_Response__Array_to_Go(goSlice []GetCriticScore_Response, cSlice []CGetCriticScore_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetCriticScore_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetCriticScore_Response__Array_to_C(cSlice []CGetCriticScore_Response, goSlice []GetCriticScore_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetCriticScore_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
