// Code generated by rclgo-gen. DO NOT EDIT.

package dwb_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <dwb_msgs/srv/score_trajectory.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
)

func init() {
	typemap.RegisterService("dwb_msgs/ScoreTrajectory", ScoreTrajectoryTypeSupport)
	typemap.RegisterService("dwb_msgs/srv/ScoreTrajectory", ScoreTrajectoryTypeSupport)
}

type _ScoreTrajectoryTypeSupport struct {}

func (s _ScoreTrajectoryTypeSupport) Request() types.MessageTypeSupport {
	return ScoreTrajectory_RequestTypeSupport
}

func (s _ScoreTrajectoryTypeSupport) Response() types.MessageTypeSupport {
	return ScoreTrajectory_ResponseTypeSupport
}

func (s _ScoreTrajectoryTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__dwb_msgs__srv__ScoreTrajectory())
}

// Modifying this variable is undefined behavior.
var ScoreTrajectoryTypeSupport types.ServiceTypeSupport = _ScoreTrajectoryTypeSupport{}

// ScoreTrajectoryClient wraps rclgo.Client to provide type safe helper
// functions
type ScoreTrajectoryClient struct {
	*rclgo.Client
}

// NewScoreTrajectoryClient creates and returns a new client for the
// ScoreTrajectory
func NewScoreTrajectoryClient(node *rclgo.Node, serviceName string, options *rclgo.ClientOptions) (*ScoreTrajectoryClient, error) {
	client, err := node.NewClient(serviceName, ScoreTrajectoryTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ScoreTrajectoryClient{client}, nil
}

func (s *ScoreTrajectoryClient) Send(ctx context.Context, req *ScoreTrajectory_Request) (*ScoreTrajectory_Response, *rclgo.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ScoreTrajectory_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ScoreTrajectoryServiceResponseSender struct {
	sender rclgo.ServiceResponseSender
}

func (s ScoreTrajectoryServiceResponseSender) SendResponse(resp *ScoreTrajectory_Response) error {
	return s.sender.SendResponse(resp)
}

type ScoreTrajectoryServiceRequestHandler func(*rclgo.ServiceInfo, *ScoreTrajectory_Request, ScoreTrajectoryServiceResponseSender)

// ScoreTrajectoryService wraps rclgo.Service to provide type safe helper
// functions
type ScoreTrajectoryService struct {
	*rclgo.Service
}

// NewScoreTrajectoryService creates and returns a new service for the
// ScoreTrajectory
func NewScoreTrajectoryService(node *rclgo.Node, name string, options *rclgo.ServiceOptions, handler ScoreTrajectoryServiceRequestHandler) (*ScoreTrajectoryService, error) {
	h := func(rmw *rclgo.ServiceInfo, msg types.Message, rs rclgo.ServiceResponseSender) {
		m := msg.(*ScoreTrajectory_Request)
		responseSender := ScoreTrajectoryServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ScoreTrajectoryTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ScoreTrajectoryService{service}, nil
}