// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <realsense2_camera_msgs/action/triggered_calibration.h>
*/
import "C"

import (
	"context"
	"time"
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"

	action_msgs_msg "dog-stream-gateway/internal/msgs/action_msgs/msg"
	action_msgs_srv "dog-stream-gateway/internal/msgs/action_msgs/srv"
)

func init() {
	typemap.RegisterAction("realsense2_camera_msgs/TriggeredCalibration", TriggeredCalibrationTypeSupport)
	typemap.RegisterAction("realsense2_camera_msgs/action/TriggeredCalibration", TriggeredCalibrationTypeSupport)
}

type _TriggeredCalibrationTypeSupport struct {}

func (s _TriggeredCalibrationTypeSupport) Goal() types.MessageTypeSupport {
	return TriggeredCalibration_GoalTypeSupport
}

func (s _TriggeredCalibrationTypeSupport) SendGoal() types.ServiceTypeSupport {
	return TriggeredCalibration_SendGoalTypeSupport
}

func (s _TriggeredCalibrationTypeSupport) NewSendGoalResponse(accepted bool, stamp time.Duration) types.Message {
	msg := NewTriggeredCalibration_SendGoal_Response()
	msg.Accepted = accepted
	secs := stamp.Truncate(time.Second)
	msg.Stamp.Sec = int32(secs)
	msg.Stamp.Nanosec = uint32(stamp - secs)
	return msg
}

func (s _TriggeredCalibrationTypeSupport) Result() types.MessageTypeSupport {
	return TriggeredCalibration_ResultTypeSupport
}

func (s _TriggeredCalibrationTypeSupport) GetResult() types.ServiceTypeSupport {
	return TriggeredCalibration_GetResultTypeSupport
}

func (s _TriggeredCalibrationTypeSupport) NewGetResultResponse(status int8, result types.Message) types.Message {
	msg := NewTriggeredCalibration_GetResult_Response()
	msg.Status = status
	if result == nil {
		msg.Result = *NewTriggeredCalibration_Result()
	} else {
		msg.Result = *result.(*TriggeredCalibration_Result)
	}
	return msg
}

func (s _TriggeredCalibrationTypeSupport) CancelGoal() types.ServiceTypeSupport {
	return action_msgs_srv.CancelGoalTypeSupport
}

func (s _TriggeredCalibrationTypeSupport) Feedback() types.MessageTypeSupport {
	return TriggeredCalibration_FeedbackTypeSupport
}

func (s _TriggeredCalibrationTypeSupport) FeedbackMessage() types.MessageTypeSupport {
	return TriggeredCalibration_FeedbackMessageTypeSupport
}

func (s _TriggeredCalibrationTypeSupport) NewFeedbackMessage(goalID *types.GoalID, feedback types.Message) types.Message {
	msg := NewTriggeredCalibration_FeedbackMessage()
	msg.GoalID.Uuid = *goalID
	msg.Feedback = *feedback.(*TriggeredCalibration_Feedback)
	return msg
}

func (s _TriggeredCalibrationTypeSupport) GoalStatusArray() types.MessageTypeSupport {
	return action_msgs_msg.GoalStatusArrayTypeSupport
}

func (s _TriggeredCalibrationTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_action_type_support_handle__realsense2_camera_msgs__action__TriggeredCalibration())
}

// Modifying this variable is undefined behavior.
var TriggeredCalibrationTypeSupport types.ActionTypeSupport = _TriggeredCalibrationTypeSupport{}

type TriggeredCalibrationFeedbackSender struct {
	sender rclgo.FeedbackSender
}

func (s *TriggeredCalibrationFeedbackSender) Send(msg *TriggeredCalibration_Feedback) error {
	return s.sender.Send(msg)
}

type TriggeredCalibrationGoalHandle struct{
	*rclgo.GoalHandle

	Description *TriggeredCalibration_Goal
}

func (g *TriggeredCalibrationGoalHandle) Accept() (*TriggeredCalibrationFeedbackSender, error) {
	s, err := g.GoalHandle.Accept()
	if err != nil {
		return nil, err
	}
	return &TriggeredCalibrationFeedbackSender{*s}, nil
}

type TriggeredCalibrationAction interface {
	ExecuteGoal(context.Context, *TriggeredCalibrationGoalHandle) (*TriggeredCalibration_Result, error)
}

func NewTriggeredCalibrationAction(
	executeGoal func(context.Context, *TriggeredCalibrationGoalHandle) (*TriggeredCalibration_Result, error),
) TriggeredCalibrationAction {
	return _TriggeredCalibrationFuncAction(executeGoal)
}

type _TriggeredCalibrationFuncAction func(context.Context, *TriggeredCalibrationGoalHandle) (*TriggeredCalibration_Result, error)

func (a _TriggeredCalibrationFuncAction) ExecuteGoal(
	ctx context.Context, goal *TriggeredCalibrationGoalHandle,
) (*TriggeredCalibration_Result, error) {
	return a(ctx, goal)
}

type _TriggeredCalibrationAction struct {
	action TriggeredCalibrationAction
}

func (a _TriggeredCalibrationAction) ExecuteGoal(ctx context.Context, handle *rclgo.GoalHandle) (types.Message, error) {
	return a.action.ExecuteGoal(ctx, &TriggeredCalibrationGoalHandle{
		GoalHandle:  handle,
		Description: handle.Description.(*TriggeredCalibration_Goal),
	})
}

func (a _TriggeredCalibrationAction) TypeSupport() types.ActionTypeSupport {
	return TriggeredCalibrationTypeSupport
}

type TriggeredCalibrationServer struct{
	*rclgo.ActionServer
}

func NewTriggeredCalibrationServer(node *rclgo.Node, name string, action TriggeredCalibrationAction, opts *rclgo.ActionServerOptions) (*TriggeredCalibrationServer, error) {
	server, err := node.NewActionServer(name, _TriggeredCalibrationAction{action}, opts)
	if err != nil {
		return nil, err
	}
	return &TriggeredCalibrationServer{server}, nil
}

type TriggeredCalibrationFeedbackHandler func(context.Context, *TriggeredCalibration_FeedbackMessage)

type TriggeredCalibrationStatusHandler func(context.Context, *action_msgs_msg.GoalStatus)

type TriggeredCalibrationClient struct{
	*rclgo.ActionClient
}

func NewTriggeredCalibrationClient(node *rclgo.Node, name string, opts *rclgo.ActionClientOptions) (*TriggeredCalibrationClient, error) {
	client, err := node.NewActionClient(name, TriggeredCalibrationTypeSupport, opts)
	if err != nil {
		return nil, err
	}
	return &TriggeredCalibrationClient{client}, nil
}

func (c *TriggeredCalibrationClient) WatchGoal(ctx context.Context, goal *TriggeredCalibration_Goal, onFeedback TriggeredCalibrationFeedbackHandler) (*TriggeredCalibration_GetResult_Response, *types.GoalID, error) {
	var resp types.Message
	var goalID *types.GoalID
	var err error
	if onFeedback == nil {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, nil)
	} else {
		resp, goalID, err = c.ActionClient.WatchGoal(ctx, goal, func(ctx context.Context, msg types.Message) {
			onFeedback(ctx, msg.(*TriggeredCalibration_FeedbackMessage))
		})
	}
	if r, ok := resp.(*TriggeredCalibration_GetResult_Response); ok {
		return r, goalID, err
	}
	return nil, goalID, err
}

func (c *TriggeredCalibrationClient) SendGoal(ctx context.Context, goal *TriggeredCalibration_Goal) (*TriggeredCalibration_SendGoal_Response, *types.GoalID, error) {
	resp, id, err := c.ActionClient.SendGoal(ctx, goal)
	if r, ok := resp.(*TriggeredCalibration_SendGoal_Response); ok {
		return r, id, err
	}
	return nil, id, err
}

func (c *TriggeredCalibrationClient) SendGoalRequest(ctx context.Context, request *TriggeredCalibration_SendGoal_Request) (*TriggeredCalibration_SendGoal_Response, error) {
	resp, err := c.ActionClient.SendGoalRequest(ctx, request)
	if r, ok := resp.(*TriggeredCalibration_SendGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *TriggeredCalibrationClient) GetResult(ctx context.Context, goalID *types.GoalID) (*TriggeredCalibration_GetResult_Response, error) {
	resp, err := c.ActionClient.GetResult(ctx, goalID)
	if r, ok := resp.(*TriggeredCalibration_GetResult_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *TriggeredCalibrationClient) CancelGoal(ctx context.Context, request *action_msgs_srv.CancelGoal_Request) (*action_msgs_srv.CancelGoal_Response, error) {
	resp, err := c.ActionClient.CancelGoal(ctx, request)
	if r, ok := resp.(*action_msgs_srv.CancelGoal_Response); ok {
		return r, err
	}
	return nil, err
}

func (c *TriggeredCalibrationClient) WatchFeedback(ctx context.Context, goalID *types.GoalID, handler TriggeredCalibrationFeedbackHandler) <-chan error {
	return c.ActionClient.WatchFeedback(ctx, goalID, func(ctx context.Context, msg types.Message) {
		handler(ctx, msg.(*TriggeredCalibration_FeedbackMessage))
	})
}

func (c *TriggeredCalibrationClient) WatchStatus(ctx context.Context, goalID *types.GoalID, handler TriggeredCalibrationStatusHandler) <-chan error {
	return c.ActionClient.WatchStatus(ctx, goalID, func(ctx context.Context, msg types.Message) {
		handler(ctx, msg.(*action_msgs_msg.GoalStatus))
	})
}
