// Code generated by rclgo-gen. DO NOT EDIT.

package realsense2_camera_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "dog-stream-gateway/internal/msgs/std_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <realsense2_camera_msgs/msg/imu_info.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("realsense2_camera_msgs/IMUInfo", IMUInfoTypeSupport)
	typemap.RegisterMessage("realsense2_camera_msgs/msg/IMUInfo", IMUInfoTypeSupport)
}

type IMUInfo struct {
	Header std_msgs_msg.Header `yaml:"header"`// header.frame_id is either set to "imu_accel" or "imu_gyro"to distinguish between "accel" and "gyro" info.
	Data [12]float64 `yaml:"data"`
	NoiseVariances [3]float64 `yaml:"noise_variances"`
	BiasVariances [3]float64 `yaml:"bias_variances"`
}

// NewIMUInfo creates a new IMUInfo with default values.
func NewIMUInfo() *IMUInfo {
	self := IMUInfo{}
	self.SetDefaults()
	return &self
}

func (t *IMUInfo) Clone() *IMUInfo {
	c := &IMUInfo{}
	c.Header = *t.Header.Clone()
	c.Data = t.Data
	c.NoiseVariances = t.NoiseVariances
	c.BiasVariances = t.BiasVariances
	return c
}

func (t *IMUInfo) CloneMsg() types.Message {
	return t.Clone()
}

func (t *IMUInfo) SetDefaults() {
	t.Header.SetDefaults()
	t.Data = [12]float64{}
	t.NoiseVariances = [3]float64{}
	t.BiasVariances = [3]float64{}
}

func (t *IMUInfo) GetTypeSupport() types.MessageTypeSupport {
	return IMUInfoTypeSupport
}

// IMUInfoPublisher wraps rclgo.Publisher to provide type safe helper
// functions
type IMUInfoPublisher struct {
	*rclgo.Publisher
}

// NewIMUInfoPublisher creates and returns a new publisher for the
// IMUInfo
func NewIMUInfoPublisher(node *rclgo.Node, topic_name string, options *rclgo.PublisherOptions) (*IMUInfoPublisher, error) {
	pub, err := node.NewPublisher(topic_name, IMUInfoTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IMUInfoPublisher{pub}, nil
}

func (p *IMUInfoPublisher) Publish(msg *IMUInfo) error {
	return p.Publisher.Publish(msg)
}

// IMUInfoSubscription wraps rclgo.Subscription to provide type safe helper
// functions
type IMUInfoSubscription struct {
	*rclgo.Subscription
}

// IMUInfoSubscriptionCallback type is used to provide a subscription
// handler function for a IMUInfoSubscription.
type IMUInfoSubscriptionCallback func(msg *IMUInfo, info *rclgo.MessageInfo, err error)

// NewIMUInfoSubscription creates and returns a new subscription for the
// IMUInfo
func NewIMUInfoSubscription(node *rclgo.Node, topic_name string, opts *rclgo.SubscriptionOptions, subscriptionCallback IMUInfoSubscriptionCallback) (*IMUInfoSubscription, error) {
	callback := func(s *rclgo.Subscription) {
		var msg IMUInfo
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topic_name, IMUInfoTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &IMUInfoSubscription{sub}, nil
}

func (s *IMUInfoSubscription) TakeMessage(out *IMUInfo) (*rclgo.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneIMUInfoSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneIMUInfoSlice(dst, src []IMUInfo) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var IMUInfoTypeSupport types.MessageTypeSupport = _IMUInfoTypeSupport{}

type _IMUInfoTypeSupport struct{}

func (t _IMUInfoTypeSupport) New() types.Message {
	return NewIMUInfo()
}

func (t _IMUInfoTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.realsense2_camera_msgs__msg__IMUInfo
	return (unsafe.Pointer)(C.realsense2_camera_msgs__msg__IMUInfo__create())
}

func (t _IMUInfoTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.realsense2_camera_msgs__msg__IMUInfo__destroy((*C.realsense2_camera_msgs__msg__IMUInfo)(pointer_to_free))
}

func (t _IMUInfoTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*IMUInfo)
	mem := (*C.realsense2_camera_msgs__msg__IMUInfo)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	cSlice_data := mem.data[:]
	primitives.Float64__Array_to_C(*(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_data)), m.Data[:])
	cSlice_noise_variances := mem.noise_variances[:]
	primitives.Float64__Array_to_C(*(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_noise_variances)), m.NoiseVariances[:])
	cSlice_bias_variances := mem.bias_variances[:]
	primitives.Float64__Array_to_C(*(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_bias_variances)), m.BiasVariances[:])
}

func (t _IMUInfoTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*IMUInfo)
	mem := (*C.realsense2_camera_msgs__msg__IMUInfo)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	cSlice_data := mem.data[:]
	primitives.Float64__Array_to_Go(m.Data[:], *(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_data)))
	cSlice_noise_variances := mem.noise_variances[:]
	primitives.Float64__Array_to_Go(m.NoiseVariances[:], *(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_noise_variances)))
	cSlice_bias_variances := mem.bias_variances[:]
	primitives.Float64__Array_to_Go(m.BiasVariances[:], *(*[]primitives.CFloat64)(unsafe.Pointer(&cSlice_bias_variances)))
}

func (t _IMUInfoTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__realsense2_camera_msgs__msg__IMUInfo())
}

type CIMUInfo = C.realsense2_camera_msgs__msg__IMUInfo
type CIMUInfo__Sequence = C.realsense2_camera_msgs__msg__IMUInfo__Sequence

func IMUInfo__Sequence_to_Go(goSlice *[]IMUInfo, cSlice CIMUInfo__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]IMUInfo, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		IMUInfoTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}
func IMUInfo__Sequence_to_C(cSlice *CIMUInfo__Sequence, goSlice []IMUInfo) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.realsense2_camera_msgs__msg__IMUInfo)(C.malloc(C.sizeof_struct_realsense2_camera_msgs__msg__IMUInfo * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		IMUInfoTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}
func IMUInfo__Array_to_Go(goSlice []IMUInfo, cSlice []CIMUInfo) {
	for i := 0; i < len(cSlice); i++ {
		IMUInfoTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func IMUInfo__Array_to_C(cSlice []CIMUInfo, goSlice []IMUInfo) {
	for i := 0; i < len(goSlice); i++ {
		IMUInfoTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
